services:
  ppocr:
    image: ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlex/hps:paddlex3.5-gpu
    container_name: rm-monitor-ppocr
    restart: unless-stopped
    shm_size: 8g
    ports:
      - "48089:8000"
    volumes:
      - ./server:/app
      - ./logs:/logs
      - ./data:/paddlex/var
    environment:
      #PADDLEX_HPS_USE_HPIP: "1"
      PADDLEX_HPS_DEVICE_TYPE: "gpu"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /app
    entrypoint:
      - bash
      - server.sh
    gpus: all