// Code generated by ent, DO NOT EDIT.

package matchround

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"scutbot.cn/web/rm-monitor/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLTE(FieldID, id))
}

// RoundNo applies equality check predicate on the "round_no" field. It's identical to RoundNoEQ.
func RoundNo(v int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldRoundNo, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldEndedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldUpdatedAt, v))
}

// RoundNoEQ applies the EQ predicate on the "round_no" field.
func RoundNoEQ(v int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldRoundNo, v))
}

// RoundNoNEQ applies the NEQ predicate on the "round_no" field.
func RoundNoNEQ(v int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNEQ(FieldRoundNo, v))
}

// RoundNoIn applies the In predicate on the "round_no" field.
func RoundNoIn(vs ...int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldIn(FieldRoundNo, vs...))
}

// RoundNoNotIn applies the NotIn predicate on the "round_no" field.
func RoundNoNotIn(vs ...int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNotIn(FieldRoundNo, vs...))
}

// RoundNoGT applies the GT predicate on the "round_no" field.
func RoundNoGT(v int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGT(FieldRoundNo, v))
}

// RoundNoGTE applies the GTE predicate on the "round_no" field.
func RoundNoGTE(v int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGTE(FieldRoundNo, v))
}

// RoundNoLT applies the LT predicate on the "round_no" field.
func RoundNoLT(v int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLT(FieldRoundNo, v))
}

// RoundNoLTE applies the LTE predicate on the "round_no" field.
func RoundNoLTE(v int) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLTE(FieldRoundNo, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNotIn(FieldStatus, vs...))
}

// WinnerEQ applies the EQ predicate on the "winner" field.
func WinnerEQ(v Winner) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldWinner, v))
}

// WinnerNEQ applies the NEQ predicate on the "winner" field.
func WinnerNEQ(v Winner) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNEQ(FieldWinner, v))
}

// WinnerIn applies the In predicate on the "winner" field.
func WinnerIn(vs ...Winner) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldIn(FieldWinner, vs...))
}

// WinnerNotIn applies the NotIn predicate on the "winner" field.
func WinnerNotIn(vs ...Winner) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNotIn(FieldWinner, vs...))
}

// WinnerIsNil applies the IsNil predicate on the "winner" field.
func WinnerIsNil() predicate.MatchRound {
	return predicate.MatchRound(sql.FieldIsNull(FieldWinner))
}

// WinnerNotNil applies the NotNil predicate on the "winner" field.
func WinnerNotNil() predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNotNull(FieldWinner))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.MatchRound {
	return predicate.MatchRound(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNotNull(FieldEndedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MatchRound {
	return predicate.MatchRound(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMatch applies the HasEdge predicate on the "match" edge.
func HasMatch() predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MatchTable, MatchColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMatchWith applies the HasEdge predicate on the "match" edge with a given conditions (other predicates).
func HasMatchWith(preds ...predicate.Match) predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := newMatchStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecordTasks applies the HasEdge predicate on the "record_tasks" edge.
func HasRecordTasks() predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecordTasksTable, RecordTasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecordTasksWith applies the HasEdge predicate on the "record_tasks" edge with a given conditions (other predicates).
func HasRecordTasksWith(preds ...predicate.RecordTask) predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := newRecordTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSttTasks applies the HasEdge predicate on the "stt_tasks" edge.
func HasSttTasks() predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SttTasksTable, SttTasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSttTasksWith applies the HasEdge predicate on the "stt_tasks" edge with a given conditions (other predicates).
func HasSttTasksWith(preds ...predicate.STTTask) predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := newSttTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHighlightClips applies the HasEdge predicate on the "highlight_clips" edge.
func HasHighlightClips() predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HighlightClipsTable, HighlightClipsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHighlightClipsWith applies the HasEdge predicate on the "highlight_clips" edge with a given conditions (other predicates).
func HasHighlightClipsWith(preds ...predicate.HighlightClip) predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := newHighlightClipsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHighlightStates applies the HasEdge predicate on the "highlight_states" edge.
func HasHighlightStates() predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HighlightStatesTable, HighlightStatesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHighlightStatesWith applies the HasEdge predicate on the "highlight_states" edge with a given conditions (other predicates).
func HasHighlightStatesWith(preds ...predicate.HighlightRoundState) predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := newHighlightStatesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOcrTasks applies the HasEdge predicate on the "ocr_tasks" edge.
func HasOcrTasks() predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OcrTasksTable, OcrTasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOcrTasksWith applies the HasEdge predicate on the "ocr_tasks" edge with a given conditions (other predicates).
func HasOcrTasksWith(preds ...predicate.OCRTask) predicate.MatchRound {
	return predicate.MatchRound(func(s *sql.Selector) {
		step := newOcrTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MatchRound) predicate.MatchRound {
	return predicate.MatchRound(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MatchRound) predicate.MatchRound {
	return predicate.MatchRound(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MatchRound) predicate.MatchRound {
	return predicate.MatchRound(sql.NotPredicates(p))
}
