RecordConf:
  Res: middle
  BaseDir: /records
  PathTemplate: "{{.Event}}/{{.Zone}}/{{.MatchName}}/Round-{{.RoundNo}}/{{.Role}}.flv"
  MatchDirTemplate: "{{.Event}}/{{.Zone}}/{{.MatchName}}"
  MatchNameTemplate: "{{.Order}}. {{.RedSchool}}-{{.RedName}} VS {{.BlueSchool}}-{{.BlueName}}"
