// Code generated by ent, DO NOT EDIT.

package larkbitablerecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the larkbitablerecord type in the database.
	Label = "lark_bitable_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldAppToken holds the string denoting the app_token field in the database.
	FieldAppToken = "app_token"
	// FieldTableID holds the string denoting the table_id field in the database.
	FieldTableID = "table_id"
	// FieldRecordID holds the string denoting the record_id field in the database.
	FieldRecordID = "record_id"
	// FieldRecordURL holds the string denoting the record_url field in the database.
	FieldRecordURL = "record_url"
	// FieldAttachmentFileToken holds the string denoting the attachment_file_token field in the database.
	FieldAttachmentFileToken = "attachment_file_token"
	// FieldSourcePath holds the string denoting the source_path field in the database.
	FieldSourcePath = "source_path"
	// FieldFileSize holds the string denoting the file_size field in the database.
	FieldFileSize = "file_size"
	// FieldSourceDeletedAt holds the string denoting the source_deleted_at field in the database.
	FieldSourceDeletedAt = "source_deleted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMatchRound holds the string denoting the match_round edge name in mutations.
	EdgeMatchRound = "match_round"
	// Table holds the table name of the larkbitablerecord in the database.
	Table = "lark_bitable_records"
	// MatchRoundTable is the table that holds the match_round relation/edge.
	MatchRoundTable = "lark_bitable_records"
	// MatchRoundInverseTable is the table name for the MatchRound entity.
	// It exists in this package in order to avoid circular dependency with the "matchround" package.
	MatchRoundInverseTable = "match_rounds"
	// MatchRoundColumn is the table column denoting the match_round relation/edge.
	MatchRoundColumn = "match_round_lark_bitable_records"
)

// Columns holds all SQL columns for larkbitablerecord fields.
var Columns = []string{
	FieldID,
	FieldRole,
	FieldAppToken,
	FieldTableID,
	FieldRecordID,
	FieldRecordURL,
	FieldAttachmentFileToken,
	FieldSourcePath,
	FieldFileSize,
	FieldSourceDeletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "lark_bitable_records"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"match_round_lark_bitable_records",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFileSize holds the default value on creation for the "file_size" field.
	DefaultFileSize int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the LarkBitableRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByAppToken orders the results by the app_token field.
func ByAppToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppToken, opts...).ToFunc()
}

// ByTableID orders the results by the table_id field.
func ByTableID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTableID, opts...).ToFunc()
}

// ByRecordID orders the results by the record_id field.
func ByRecordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordID, opts...).ToFunc()
}

// ByRecordURL orders the results by the record_url field.
func ByRecordURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordURL, opts...).ToFunc()
}

// ByAttachmentFileToken orders the results by the attachment_file_token field.
func ByAttachmentFileToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttachmentFileToken, opts...).ToFunc()
}

// BySourcePath orders the results by the source_path field.
func BySourcePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourcePath, opts...).ToFunc()
}

// ByFileSize orders the results by the file_size field.
func ByFileSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSize, opts...).ToFunc()
}

// BySourceDeletedAt orders the results by the source_deleted_at field.
func BySourceDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceDeletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMatchRoundField orders the results by match_round field.
func ByMatchRoundField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMatchRoundStep(), sql.OrderByField(field, opts...))
	}
}
func newMatchRoundStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MatchRoundInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MatchRoundTable, MatchRoundColumn),
	)
}
