// Code generated by ent, DO NOT EDIT.

package larkbitablerecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"scutbot.cn/web/rm-monitor/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldID, id))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldRole, v))
}

// AppToken applies equality check predicate on the "app_token" field. It's identical to AppTokenEQ.
func AppToken(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldAppToken, v))
}

// TableID applies equality check predicate on the "table_id" field. It's identical to TableIDEQ.
func TableID(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldTableID, v))
}

// RecordID applies equality check predicate on the "record_id" field. It's identical to RecordIDEQ.
func RecordID(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldRecordID, v))
}

// RecordURL applies equality check predicate on the "record_url" field. It's identical to RecordURLEQ.
func RecordURL(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldRecordURL, v))
}

// AttachmentFileToken applies equality check predicate on the "attachment_file_token" field. It's identical to AttachmentFileTokenEQ.
func AttachmentFileToken(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldAttachmentFileToken, v))
}

// SourcePath applies equality check predicate on the "source_path" field. It's identical to SourcePathEQ.
func SourcePath(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldSourcePath, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int64) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldFileSize, v))
}

// SourceDeletedAt applies equality check predicate on the "source_deleted_at" field. It's identical to SourceDeletedAtEQ.
func SourceDeletedAt(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldSourceDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContainsFold(FieldRole, v))
}

// AppTokenEQ applies the EQ predicate on the "app_token" field.
func AppTokenEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldAppToken, v))
}

// AppTokenNEQ applies the NEQ predicate on the "app_token" field.
func AppTokenNEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldAppToken, v))
}

// AppTokenIn applies the In predicate on the "app_token" field.
func AppTokenIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldAppToken, vs...))
}

// AppTokenNotIn applies the NotIn predicate on the "app_token" field.
func AppTokenNotIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldAppToken, vs...))
}

// AppTokenGT applies the GT predicate on the "app_token" field.
func AppTokenGT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldAppToken, v))
}

// AppTokenGTE applies the GTE predicate on the "app_token" field.
func AppTokenGTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldAppToken, v))
}

// AppTokenLT applies the LT predicate on the "app_token" field.
func AppTokenLT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldAppToken, v))
}

// AppTokenLTE applies the LTE predicate on the "app_token" field.
func AppTokenLTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldAppToken, v))
}

// AppTokenContains applies the Contains predicate on the "app_token" field.
func AppTokenContains(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContains(FieldAppToken, v))
}

// AppTokenHasPrefix applies the HasPrefix predicate on the "app_token" field.
func AppTokenHasPrefix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasPrefix(FieldAppToken, v))
}

// AppTokenHasSuffix applies the HasSuffix predicate on the "app_token" field.
func AppTokenHasSuffix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasSuffix(FieldAppToken, v))
}

// AppTokenEqualFold applies the EqualFold predicate on the "app_token" field.
func AppTokenEqualFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEqualFold(FieldAppToken, v))
}

// AppTokenContainsFold applies the ContainsFold predicate on the "app_token" field.
func AppTokenContainsFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContainsFold(FieldAppToken, v))
}

// TableIDEQ applies the EQ predicate on the "table_id" field.
func TableIDEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldTableID, v))
}

// TableIDNEQ applies the NEQ predicate on the "table_id" field.
func TableIDNEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldTableID, v))
}

// TableIDIn applies the In predicate on the "table_id" field.
func TableIDIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldTableID, vs...))
}

// TableIDNotIn applies the NotIn predicate on the "table_id" field.
func TableIDNotIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldTableID, vs...))
}

// TableIDGT applies the GT predicate on the "table_id" field.
func TableIDGT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldTableID, v))
}

// TableIDGTE applies the GTE predicate on the "table_id" field.
func TableIDGTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldTableID, v))
}

// TableIDLT applies the LT predicate on the "table_id" field.
func TableIDLT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldTableID, v))
}

// TableIDLTE applies the LTE predicate on the "table_id" field.
func TableIDLTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldTableID, v))
}

// TableIDContains applies the Contains predicate on the "table_id" field.
func TableIDContains(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContains(FieldTableID, v))
}

// TableIDHasPrefix applies the HasPrefix predicate on the "table_id" field.
func TableIDHasPrefix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasPrefix(FieldTableID, v))
}

// TableIDHasSuffix applies the HasSuffix predicate on the "table_id" field.
func TableIDHasSuffix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasSuffix(FieldTableID, v))
}

// TableIDEqualFold applies the EqualFold predicate on the "table_id" field.
func TableIDEqualFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEqualFold(FieldTableID, v))
}

// TableIDContainsFold applies the ContainsFold predicate on the "table_id" field.
func TableIDContainsFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContainsFold(FieldTableID, v))
}

// RecordIDEQ applies the EQ predicate on the "record_id" field.
func RecordIDEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldRecordID, v))
}

// RecordIDNEQ applies the NEQ predicate on the "record_id" field.
func RecordIDNEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldRecordID, v))
}

// RecordIDIn applies the In predicate on the "record_id" field.
func RecordIDIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldRecordID, vs...))
}

// RecordIDNotIn applies the NotIn predicate on the "record_id" field.
func RecordIDNotIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldRecordID, vs...))
}

// RecordIDGT applies the GT predicate on the "record_id" field.
func RecordIDGT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldRecordID, v))
}

// RecordIDGTE applies the GTE predicate on the "record_id" field.
func RecordIDGTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldRecordID, v))
}

// RecordIDLT applies the LT predicate on the "record_id" field.
func RecordIDLT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldRecordID, v))
}

// RecordIDLTE applies the LTE predicate on the "record_id" field.
func RecordIDLTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldRecordID, v))
}

// RecordIDContains applies the Contains predicate on the "record_id" field.
func RecordIDContains(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContains(FieldRecordID, v))
}

// RecordIDHasPrefix applies the HasPrefix predicate on the "record_id" field.
func RecordIDHasPrefix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasPrefix(FieldRecordID, v))
}

// RecordIDHasSuffix applies the HasSuffix predicate on the "record_id" field.
func RecordIDHasSuffix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasSuffix(FieldRecordID, v))
}

// RecordIDEqualFold applies the EqualFold predicate on the "record_id" field.
func RecordIDEqualFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEqualFold(FieldRecordID, v))
}

// RecordIDContainsFold applies the ContainsFold predicate on the "record_id" field.
func RecordIDContainsFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContainsFold(FieldRecordID, v))
}

// RecordURLEQ applies the EQ predicate on the "record_url" field.
func RecordURLEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldRecordURL, v))
}

// RecordURLNEQ applies the NEQ predicate on the "record_url" field.
func RecordURLNEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldRecordURL, v))
}

// RecordURLIn applies the In predicate on the "record_url" field.
func RecordURLIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldRecordURL, vs...))
}

// RecordURLNotIn applies the NotIn predicate on the "record_url" field.
func RecordURLNotIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldRecordURL, vs...))
}

// RecordURLGT applies the GT predicate on the "record_url" field.
func RecordURLGT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldRecordURL, v))
}

// RecordURLGTE applies the GTE predicate on the "record_url" field.
func RecordURLGTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldRecordURL, v))
}

// RecordURLLT applies the LT predicate on the "record_url" field.
func RecordURLLT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldRecordURL, v))
}

// RecordURLLTE applies the LTE predicate on the "record_url" field.
func RecordURLLTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldRecordURL, v))
}

// RecordURLContains applies the Contains predicate on the "record_url" field.
func RecordURLContains(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContains(FieldRecordURL, v))
}

// RecordURLHasPrefix applies the HasPrefix predicate on the "record_url" field.
func RecordURLHasPrefix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasPrefix(FieldRecordURL, v))
}

// RecordURLHasSuffix applies the HasSuffix predicate on the "record_url" field.
func RecordURLHasSuffix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasSuffix(FieldRecordURL, v))
}

// RecordURLIsNil applies the IsNil predicate on the "record_url" field.
func RecordURLIsNil() predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIsNull(FieldRecordURL))
}

// RecordURLNotNil applies the NotNil predicate on the "record_url" field.
func RecordURLNotNil() predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotNull(FieldRecordURL))
}

// RecordURLEqualFold applies the EqualFold predicate on the "record_url" field.
func RecordURLEqualFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEqualFold(FieldRecordURL, v))
}

// RecordURLContainsFold applies the ContainsFold predicate on the "record_url" field.
func RecordURLContainsFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContainsFold(FieldRecordURL, v))
}

// AttachmentFileTokenEQ applies the EQ predicate on the "attachment_file_token" field.
func AttachmentFileTokenEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldAttachmentFileToken, v))
}

// AttachmentFileTokenNEQ applies the NEQ predicate on the "attachment_file_token" field.
func AttachmentFileTokenNEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldAttachmentFileToken, v))
}

// AttachmentFileTokenIn applies the In predicate on the "attachment_file_token" field.
func AttachmentFileTokenIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldAttachmentFileToken, vs...))
}

// AttachmentFileTokenNotIn applies the NotIn predicate on the "attachment_file_token" field.
func AttachmentFileTokenNotIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldAttachmentFileToken, vs...))
}

// AttachmentFileTokenGT applies the GT predicate on the "attachment_file_token" field.
func AttachmentFileTokenGT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldAttachmentFileToken, v))
}

// AttachmentFileTokenGTE applies the GTE predicate on the "attachment_file_token" field.
func AttachmentFileTokenGTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldAttachmentFileToken, v))
}

// AttachmentFileTokenLT applies the LT predicate on the "attachment_file_token" field.
func AttachmentFileTokenLT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldAttachmentFileToken, v))
}

// AttachmentFileTokenLTE applies the LTE predicate on the "attachment_file_token" field.
func AttachmentFileTokenLTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldAttachmentFileToken, v))
}

// AttachmentFileTokenContains applies the Contains predicate on the "attachment_file_token" field.
func AttachmentFileTokenContains(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContains(FieldAttachmentFileToken, v))
}

// AttachmentFileTokenHasPrefix applies the HasPrefix predicate on the "attachment_file_token" field.
func AttachmentFileTokenHasPrefix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasPrefix(FieldAttachmentFileToken, v))
}

// AttachmentFileTokenHasSuffix applies the HasSuffix predicate on the "attachment_file_token" field.
func AttachmentFileTokenHasSuffix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasSuffix(FieldAttachmentFileToken, v))
}

// AttachmentFileTokenIsNil applies the IsNil predicate on the "attachment_file_token" field.
func AttachmentFileTokenIsNil() predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIsNull(FieldAttachmentFileToken))
}

// AttachmentFileTokenNotNil applies the NotNil predicate on the "attachment_file_token" field.
func AttachmentFileTokenNotNil() predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotNull(FieldAttachmentFileToken))
}

// AttachmentFileTokenEqualFold applies the EqualFold predicate on the "attachment_file_token" field.
func AttachmentFileTokenEqualFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEqualFold(FieldAttachmentFileToken, v))
}

// AttachmentFileTokenContainsFold applies the ContainsFold predicate on the "attachment_file_token" field.
func AttachmentFileTokenContainsFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContainsFold(FieldAttachmentFileToken, v))
}

// SourcePathEQ applies the EQ predicate on the "source_path" field.
func SourcePathEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldSourcePath, v))
}

// SourcePathNEQ applies the NEQ predicate on the "source_path" field.
func SourcePathNEQ(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldSourcePath, v))
}

// SourcePathIn applies the In predicate on the "source_path" field.
func SourcePathIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldSourcePath, vs...))
}

// SourcePathNotIn applies the NotIn predicate on the "source_path" field.
func SourcePathNotIn(vs ...string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldSourcePath, vs...))
}

// SourcePathGT applies the GT predicate on the "source_path" field.
func SourcePathGT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldSourcePath, v))
}

// SourcePathGTE applies the GTE predicate on the "source_path" field.
func SourcePathGTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldSourcePath, v))
}

// SourcePathLT applies the LT predicate on the "source_path" field.
func SourcePathLT(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldSourcePath, v))
}

// SourcePathLTE applies the LTE predicate on the "source_path" field.
func SourcePathLTE(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldSourcePath, v))
}

// SourcePathContains applies the Contains predicate on the "source_path" field.
func SourcePathContains(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContains(FieldSourcePath, v))
}

// SourcePathHasPrefix applies the HasPrefix predicate on the "source_path" field.
func SourcePathHasPrefix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasPrefix(FieldSourcePath, v))
}

// SourcePathHasSuffix applies the HasSuffix predicate on the "source_path" field.
func SourcePathHasSuffix(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldHasSuffix(FieldSourcePath, v))
}

// SourcePathEqualFold applies the EqualFold predicate on the "source_path" field.
func SourcePathEqualFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEqualFold(FieldSourcePath, v))
}

// SourcePathContainsFold applies the ContainsFold predicate on the "source_path" field.
func SourcePathContainsFold(v string) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldContainsFold(FieldSourcePath, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int64) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int64) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int64) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int64) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int64) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int64) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int64) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int64) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldFileSize, v))
}

// SourceDeletedAtEQ applies the EQ predicate on the "source_deleted_at" field.
func SourceDeletedAtEQ(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldSourceDeletedAt, v))
}

// SourceDeletedAtNEQ applies the NEQ predicate on the "source_deleted_at" field.
func SourceDeletedAtNEQ(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldSourceDeletedAt, v))
}

// SourceDeletedAtIn applies the In predicate on the "source_deleted_at" field.
func SourceDeletedAtIn(vs ...time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldSourceDeletedAt, vs...))
}

// SourceDeletedAtNotIn applies the NotIn predicate on the "source_deleted_at" field.
func SourceDeletedAtNotIn(vs ...time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldSourceDeletedAt, vs...))
}

// SourceDeletedAtGT applies the GT predicate on the "source_deleted_at" field.
func SourceDeletedAtGT(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldSourceDeletedAt, v))
}

// SourceDeletedAtGTE applies the GTE predicate on the "source_deleted_at" field.
func SourceDeletedAtGTE(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldSourceDeletedAt, v))
}

// SourceDeletedAtLT applies the LT predicate on the "source_deleted_at" field.
func SourceDeletedAtLT(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldSourceDeletedAt, v))
}

// SourceDeletedAtLTE applies the LTE predicate on the "source_deleted_at" field.
func SourceDeletedAtLTE(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldSourceDeletedAt, v))
}

// SourceDeletedAtIsNil applies the IsNil predicate on the "source_deleted_at" field.
func SourceDeletedAtIsNil() predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIsNull(FieldSourceDeletedAt))
}

// SourceDeletedAtNotNil applies the NotNil predicate on the "source_deleted_at" field.
func SourceDeletedAtNotNil() predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotNull(FieldSourceDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMatchRound applies the HasEdge predicate on the "match_round" edge.
func HasMatchRound() predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MatchRoundTable, MatchRoundColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMatchRoundWith applies the HasEdge predicate on the "match_round" edge with a given conditions (other predicates).
func HasMatchRoundWith(preds ...predicate.MatchRound) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(func(s *sql.Selector) {
		step := newMatchRoundStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LarkBitableRecord) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LarkBitableRecord) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LarkBitableRecord) predicate.LarkBitableRecord {
	return predicate.LarkBitableRecord(sql.NotPredicates(p))
}
