apiVersion: v1
kind: PersistentVolume
metadata:
  name: rm-monitor-records
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rm-monitor-records
  local:
    path: /data/rm-monitor/records
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: rm-monitor/storage
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rm-monitor-records
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rm-monitor-records
  resources:
    requests:
      storage: 500Gi
