// Code generated by ent, DO NOT EDIT.

package highlightpublishtask

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the highlightpublishtask type in the database.
	Label = "highlight_publish_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldK8sJobName holds the string denoting the k8s_job_name field in the database.
	FieldK8sJobName = "k8s_job_name"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldPublishURL holds the string denoting the publish_url field in the database.
	FieldPublishURL = "publish_url"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeHighlightClip holds the string denoting the highlight_clip edge name in mutations.
	EdgeHighlightClip = "highlight_clip"
	// Table holds the table name of the highlightpublishtask in the database.
	Table = "highlight_publish_tasks"
	// HighlightClipTable is the table that holds the highlight_clip relation/edge.
	HighlightClipTable = "highlight_publish_tasks"
	// HighlightClipInverseTable is the table name for the HighlightClip entity.
	// It exists in this package in order to avoid circular dependency with the "highlightclip" package.
	HighlightClipInverseTable = "highlight_clips"
	// HighlightClipColumn is the table column denoting the highlight_clip relation/edge.
	HighlightClipColumn = "highlight_clip_publish_tasks"
)

// Columns holds all SQL columns for highlightpublishtask fields.
var Columns = []string{
	FieldID,
	FieldPlatform,
	FieldStatus,
	FieldPriority,
	FieldK8sJobName,
	FieldAttempts,
	FieldPublishURL,
	FieldExternalID,
	FieldErrorMessage,
	FieldStartedAt,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "highlight_publish_tasks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"highlight_clip_publish_tasks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Platform defines the type for the "platform" enum field.
type Platform string

// Platform values.
const (
	PlatformBilibili Platform = "bilibili"
)

func (pl Platform) String() string {
	return string(pl)
}

// PlatformValidator is a validator for the "platform" field enum values. It is called by the builders before save.
func PlatformValidator(pl Platform) error {
	switch pl {
	case PlatformBilibili:
		return nil
	default:
		return fmt.Errorf("highlightpublishtask: invalid enum value for platform field: %q", pl)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING     Status = "PENDING"
	StatusDISPATCHING Status = "DISPATCHING"
	StatusRUNNING     Status = "RUNNING"
	StatusSUCCEEDED   Status = "SUCCEEDED"
	StatusFAILED      Status = "FAILED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusDISPATCHING, StatusRUNNING, StatusSUCCEEDED, StatusFAILED:
		return nil
	default:
		return fmt.Errorf("highlightpublishtask: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the HighlightPublishTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByK8sJobName orders the results by the k8s_job_name field.
func ByK8sJobName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldK8sJobName, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByPublishURL orders the results by the publish_url field.
func ByPublishURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishURL, opts...).ToFunc()
}

// ByExternalID orders the results by the external_id field.
func ByExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalID, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByHighlightClipField orders the results by highlight_clip field.
func ByHighlightClipField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHighlightClipStep(), sql.OrderByField(field, opts...))
	}
}
func newHighlightClipStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HighlightClipInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HighlightClipTable, HighlightClipColumn),
	)
}
