services:
  ppocr:
    build:
      args:
        PADDLE_DEVICE: gpu
    environment:
      OCR_DEVICE: gpu:0
      OCR_ENABLE_MKLDNN: "false"
      OCR_CPU_THREADS: "4"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

