// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BilibiliHighlightPublicationsColumns holds the columns for the "bilibili_highlight_publications" table.
	BilibiliHighlightPublicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "highlight_clip_bilibili_publications", Type: field.TypeInt},
	}
	// BilibiliHighlightPublicationsTable holds the schema information for the "bilibili_highlight_publications" table.
	BilibiliHighlightPublicationsTable = &schema.Table{
		Name:       "bilibili_highlight_publications",
		Columns:    BilibiliHighlightPublicationsColumns,
		PrimaryKey: []*schema.Column{BilibiliHighlightPublicationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bilibili_highlight_publications_highlight_clips_bilibili_publications",
				Columns:    []*schema.Column{BilibiliHighlightPublicationsColumns[8]},
				RefColumns: []*schema.Column{HighlightClipsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "bilibilihighlightpublication_highlight_clip_bilibili_publications",
				Unique:  true,
				Columns: []*schema.Column{BilibiliHighlightPublicationsColumns[8]},
			},
			{
				Name:    "bilibilihighlightpublication_updated_at",
				Unique:  false,
				Columns: []*schema.Column{BilibiliHighlightPublicationsColumns[7]},
			},
		},
	}
	// HighlightClipsColumns holds the columns for the "highlight_clips" table.
	HighlightClipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "highlight_index", Type: field.TypeInt},
		{Name: "role", Type: field.TypeString},
		{Name: "algorithm_version", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"AVAILABLE", "FAILED", "SKIPPED"}, Default: "AVAILABLE"},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "start_seconds", Type: field.TypeFloat64},
		{Name: "end_seconds", Type: field.TypeFloat64},
		{Name: "peak_seconds", Type: field.TypeFloat64},
		{Name: "source_path", Type: field.TypeString},
		{Name: "output_dir", Type: field.TypeString},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "score", Type: field.TypeFloat64, Default: 0},
		{Name: "model_payload", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "match_round_highlight_clips", Type: field.TypeInt},
	}
	// HighlightClipsTable holds the schema information for the "highlight_clips" table.
	HighlightClipsTable = &schema.Table{
		Name:       "highlight_clips",
		Columns:    HighlightClipsColumns,
		PrimaryKey: []*schema.Column{HighlightClipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "highlight_clips_match_rounds_highlight_clips",
				Columns:    []*schema.Column{HighlightClipsColumns[19]},
				RefColumns: []*schema.Column{MatchRoundsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "highlightclip_role_algorithm_version_highlight_index_match_round_highlight_clips",
				Unique:  true,
				Columns: []*schema.Column{HighlightClipsColumns[2], HighlightClipsColumns[3], HighlightClipsColumns[1], HighlightClipsColumns[19]},
			},
			{
				Name:    "highlightclip_status",
				Unique:  false,
				Columns: []*schema.Column{HighlightClipsColumns[4]},
			},
		},
	}
	// LarkBitableRecordsColumns holds the columns for the "lark_bitable_records" table.
	LarkBitableRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role", Type: field.TypeString},
		{Name: "app_token", Type: field.TypeString},
		{Name: "table_id", Type: field.TypeString},
		{Name: "record_id", Type: field.TypeString},
		{Name: "record_url", Type: field.TypeString, Nullable: true},
		{Name: "attachment_file_token", Type: field.TypeString, Nullable: true},
		{Name: "source_path", Type: field.TypeString},
		{Name: "file_size", Type: field.TypeInt64, Default: 0},
		{Name: "source_deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "match_round_lark_bitable_records", Type: field.TypeInt},
	}
	// LarkBitableRecordsTable holds the schema information for the "lark_bitable_records" table.
	LarkBitableRecordsTable = &schema.Table{
		Name:       "lark_bitable_records",
		Columns:    LarkBitableRecordsColumns,
		PrimaryKey: []*schema.Column{LarkBitableRecordsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "lark_bitable_records_match_rounds_lark_bitable_records",
				Columns:    []*schema.Column{LarkBitableRecordsColumns[12]},
				RefColumns: []*schema.Column{MatchRoundsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "larkbitablerecord_role_match_round_lark_bitable_records",
				Unique:  true,
				Columns: []*schema.Column{LarkBitableRecordsColumns[1], LarkBitableRecordsColumns[12]},
			},
			{
				Name:    "larkbitablerecord_updated_at",
				Unique:  false,
				Columns: []*schema.Column{LarkBitableRecordsColumns[11]},
			},
		},
	}
	// LarkMessagesColumns holds the columns for the "lark_messages" table.
	LarkMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "message_id", Type: field.TypeString, Unique: true},
		{Name: "chat_id", Type: field.TypeString, Nullable: true},
		{Name: "card_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "card_payload", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "match_lark_messages", Type: field.TypeString},
	}
	// LarkMessagesTable holds the schema information for the "lark_messages" table.
	LarkMessagesTable = &schema.Table{
		Name:       "lark_messages",
		Columns:    LarkMessagesColumns,
		PrimaryKey: []*schema.Column{LarkMessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "lark_messages_matches_lark_messages",
				Columns:    []*schema.Column{LarkMessagesColumns[7]},
				RefColumns: []*schema.Column{MatchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "larkmessage_chat_id_match_lark_messages",
				Unique:  true,
				Columns: []*schema.Column{LarkMessagesColumns[2], LarkMessagesColumns[7]},
			},
		},
	}
	// MatchesColumns holds the columns for the "matches" table.
	MatchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "event", Type: field.TypeString},
		{Name: "zone", Type: field.TypeString},
		{Name: "order", Type: field.TypeInt},
		{Name: "match_type", Type: field.TypeString, Default: ""},
		{Name: "match_slug", Type: field.TypeString, Nullable: true},
		{Name: "total_rounds", Type: field.TypeInt, Default: 0},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "result", Type: field.TypeEnum, Enums: []string{"RED", "BLUE", "DRAW", "UNKNOWN"}, Default: "UNKNOWN"},
		{Name: "winner_placeholder_name", Type: field.TypeString, Nullable: true},
		{Name: "loser_placeholder_name", Type: field.TypeString, Nullable: true},
		{Name: "latest_status", Type: field.TypeString, Default: ""},
		{Name: "workflow_name", Type: field.TypeString, Nullable: true},
		{Name: "workflow_uid", Type: field.TypeString, Nullable: true},
		{Name: "workflow_phase", Type: field.TypeString, Nullable: true},
		{Name: "report", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "team_red_matches", Type: field.TypeString},
		{Name: "team_blue_matches", Type: field.TypeString},
	}
	// MatchesTable holds the schema information for the "matches" table.
	MatchesTable = &schema.Table{
		Name:       "matches",
		Columns:    MatchesColumns,
		PrimaryKey: []*schema.Column{MatchesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "matches_teams_red_matches",
				Columns:    []*schema.Column{MatchesColumns[18]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "matches_teams_blue_matches",
				Columns:    []*schema.Column{MatchesColumns[19]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "match_updated_at",
				Unique:  false,
				Columns: []*schema.Column{MatchesColumns[17]},
			},
			{
				Name:    "match_latest_status_updated_at",
				Unique:  false,
				Columns: []*schema.Column{MatchesColumns[11], MatchesColumns[17]},
			},
		},
	}
	// MatchRoundsColumns holds the columns for the "match_rounds" table.
	MatchRoundsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "round_no", Type: field.TypeInt},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"STARTED", "ENDED"}},
		{Name: "winner", Type: field.TypeEnum, Nullable: true, Enums: []string{"blue", "red", "draw"}},
		{Name: "workflow_name", Type: field.TypeString, Nullable: true},
		{Name: "workflow_uid", Type: field.TypeString, Nullable: true},
		{Name: "workflow_phase", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "ended_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "match_rounds", Type: field.TypeString},
	}
	// MatchRoundsTable holds the schema information for the "match_rounds" table.
	MatchRoundsTable = &schema.Table{
		Name:       "match_rounds",
		Columns:    MatchRoundsColumns,
		PrimaryKey: []*schema.Column{MatchRoundsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "match_rounds_matches_rounds",
				Columns:    []*schema.Column{MatchRoundsColumns[11]},
				RefColumns: []*schema.Column{MatchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "matchround_round_no_match_rounds",
				Unique:  true,
				Columns: []*schema.Column{MatchRoundsColumns[1], MatchRoundsColumns[11]},
			},
			{
				Name:    "matchround_status",
				Unique:  false,
				Columns: []*schema.Column{MatchRoundsColumns[2]},
			},
			{
				Name:    "matchround_updated_at",
				Unique:  false,
				Columns: []*schema.Column{MatchRoundsColumns[10]},
			},
			{
				Name:    "matchround_status_updated_at",
				Unique:  false,
				Columns: []*schema.Column{MatchRoundsColumns[2], MatchRoundsColumns[10]},
			},
		},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "school_name", Type: field.TypeString, Default: ""},
		{Name: "school_logo", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BilibiliHighlightPublicationsTable,
		HighlightClipsTable,
		LarkBitableRecordsTable,
		LarkMessagesTable,
		MatchesTable,
		MatchRoundsTable,
		TeamsTable,
	}
)

func init() {
	BilibiliHighlightPublicationsTable.ForeignKeys[0].RefTable = HighlightClipsTable
	HighlightClipsTable.ForeignKeys[0].RefTable = MatchRoundsTable
	LarkBitableRecordsTable.ForeignKeys[0].RefTable = MatchRoundsTable
	LarkMessagesTable.ForeignKeys[0].RefTable = MatchesTable
	MatchesTable.ForeignKeys[0].RefTable = TeamsTable
	MatchesTable.ForeignKeys[1].RefTable = TeamsTable
	MatchRoundsTable.ForeignKeys[0].RefTable = MatchesTable
}
