// Code generated by ent, DO NOT EDIT.

package transcodetask

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the transcodetask type in the database.
	Label = "transcode_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldK8sJobName holds the string denoting the k8s_job_name field in the database.
	FieldK8sJobName = "k8s_job_name"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSourceArtifact holds the string denoting the source_artifact edge name in mutations.
	EdgeSourceArtifact = "source_artifact"
	// EdgeArchiveArtifact holds the string denoting the archive_artifact edge name in mutations.
	EdgeArchiveArtifact = "archive_artifact"
	// Table holds the table name of the transcodetask in the database.
	Table = "transcode_tasks"
	// SourceArtifactTable is the table that holds the source_artifact relation/edge.
	SourceArtifactTable = "transcode_tasks"
	// SourceArtifactInverseTable is the table name for the MediaArtifact entity.
	// It exists in this package in order to avoid circular dependency with the "mediaartifact" package.
	SourceArtifactInverseTable = "media_artifacts"
	// SourceArtifactColumn is the table column denoting the source_artifact relation/edge.
	SourceArtifactColumn = "media_artifact_source_transcode_task"
	// ArchiveArtifactTable is the table that holds the archive_artifact relation/edge.
	ArchiveArtifactTable = "transcode_tasks"
	// ArchiveArtifactInverseTable is the table name for the MediaArtifact entity.
	// It exists in this package in order to avoid circular dependency with the "mediaartifact" package.
	ArchiveArtifactInverseTable = "media_artifacts"
	// ArchiveArtifactColumn is the table column denoting the archive_artifact relation/edge.
	ArchiveArtifactColumn = "media_artifact_archive_transcode_task"
)

// Columns holds all SQL columns for transcodetask fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldK8sJobName,
	FieldAttempts,
	FieldErrorMessage,
	FieldStartedAt,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "transcode_tasks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"media_artifact_source_transcode_task",
	"media_artifact_archive_transcode_task",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING     Status = "PENDING"
	StatusDISPATCHING Status = "DISPATCHING"
	StatusRUNNING     Status = "RUNNING"
	StatusSUCCEEDED   Status = "SUCCEEDED"
	StatusFAILED      Status = "FAILED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusDISPATCHING, StatusRUNNING, StatusSUCCEEDED, StatusFAILED:
		return nil
	default:
		return fmt.Errorf("transcodetask: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the TranscodeTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByK8sJobName orders the results by the k8s_job_name field.
func ByK8sJobName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldK8sJobName, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySourceArtifactField orders the results by source_artifact field.
func BySourceArtifactField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceArtifactStep(), sql.OrderByField(field, opts...))
	}
}

// ByArchiveArtifactField orders the results by archive_artifact field.
func ByArchiveArtifactField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArchiveArtifactStep(), sql.OrderByField(field, opts...))
	}
}
func newSourceArtifactStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceArtifactInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, SourceArtifactTable, SourceArtifactColumn),
	)
}
func newArchiveArtifactStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArchiveArtifactInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, ArchiveArtifactTable, ArchiveArtifactColumn),
	)
}
