// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"scutbot.cn/web/rm-monitor/ent/bilibilihighlightpublication"
	"scutbot.cn/web/rm-monitor/ent/highlightclip"
)

// BilibiliHighlightPublication is the model entity for the BilibiliHighlightPublication schema.
type BilibiliHighlightPublication struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID *string `json:"external_id,omitempty"`
	// URL holds the value of the "url" field.
	URL *string `json:"url,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BilibiliHighlightPublicationQuery when eager-loading is set.
	Edges                                BilibiliHighlightPublicationEdges `json:"edges"`
	highlight_clip_bilibili_publications *int
	selectValues                         sql.SelectValues
}

// BilibiliHighlightPublicationEdges holds the relations/edges for other nodes in the graph.
type BilibiliHighlightPublicationEdges struct {
	// HighlightClip holds the value of the highlight_clip edge.
	HighlightClip *HighlightClip `json:"highlight_clip,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HighlightClipOrErr returns the HighlightClip value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BilibiliHighlightPublicationEdges) HighlightClipOrErr() (*HighlightClip, error) {
	if e.HighlightClip != nil {
		return e.HighlightClip, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: highlightclip.Label}
	}
	return nil, &NotLoadedError{edge: "highlight_clip"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BilibiliHighlightPublication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bilibilihighlightpublication.FieldPayload:
			values[i] = new([]byte)
		case bilibilihighlightpublication.FieldID:
			values[i] = new(sql.NullInt64)
		case bilibilihighlightpublication.FieldExternalID, bilibilihighlightpublication.FieldURL, bilibilihighlightpublication.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case bilibilihighlightpublication.FieldPublishedAt, bilibilihighlightpublication.FieldCreatedAt, bilibilihighlightpublication.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case bilibilihighlightpublication.ForeignKeys[0]: // highlight_clip_bilibili_publications
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BilibiliHighlightPublication fields.
func (_m *BilibiliHighlightPublication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bilibilihighlightpublication.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case bilibilihighlightpublication.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = new(string)
				*_m.ExternalID = value.String
			}
		case bilibilihighlightpublication.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = new(string)
				*_m.URL = value.String
			}
		case bilibilihighlightpublication.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case bilibilihighlightpublication.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case bilibilihighlightpublication.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case bilibilihighlightpublication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case bilibilihighlightpublication.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case bilibilihighlightpublication.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field highlight_clip_bilibili_publications", value)
			} else if value.Valid {
				_m.highlight_clip_bilibili_publications = new(int)
				*_m.highlight_clip_bilibili_publications = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BilibiliHighlightPublication.
// This includes values selected through modifiers, order, etc.
func (_m *BilibiliHighlightPublication) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHighlightClip queries the "highlight_clip" edge of the BilibiliHighlightPublication entity.
func (_m *BilibiliHighlightPublication) QueryHighlightClip() *HighlightClipQuery {
	return NewBilibiliHighlightPublicationClient(_m.config).QueryHighlightClip(_m)
}

// Update returns a builder for updating this BilibiliHighlightPublication.
// Note that you need to call BilibiliHighlightPublication.Unwrap() before calling this method if this BilibiliHighlightPublication
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BilibiliHighlightPublication) Update() *BilibiliHighlightPublicationUpdateOne {
	return NewBilibiliHighlightPublicationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BilibiliHighlightPublication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BilibiliHighlightPublication) Unwrap() *BilibiliHighlightPublication {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BilibiliHighlightPublication is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BilibiliHighlightPublication) String() string {
	var builder strings.Builder
	builder.WriteString("BilibiliHighlightPublication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.ExternalID; v != nil {
		builder.WriteString("external_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.URL; v != nil {
		builder.WriteString("url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BilibiliHighlightPublications is a parsable slice of BilibiliHighlightPublication.
type BilibiliHighlightPublications []*BilibiliHighlightPublication
