// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"scutbot.cn/web/rm-monitor/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"scutbot.cn/web/rm-monitor/ent/bilibilihighlightpublication"
	"scutbot.cn/web/rm-monitor/ent/highlightclip"
	"scutbot.cn/web/rm-monitor/ent/larkbitablerecord"
	"scutbot.cn/web/rm-monitor/ent/larkmessage"
	"scutbot.cn/web/rm-monitor/ent/match"
	"scutbot.cn/web/rm-monitor/ent/matchround"
	"scutbot.cn/web/rm-monitor/ent/team"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BilibiliHighlightPublication is the client for interacting with the BilibiliHighlightPublication builders.
	BilibiliHighlightPublication *BilibiliHighlightPublicationClient
	// HighlightClip is the client for interacting with the HighlightClip builders.
	HighlightClip *HighlightClipClient
	// LarkBitableRecord is the client for interacting with the LarkBitableRecord builders.
	LarkBitableRecord *LarkBitableRecordClient
	// LarkMessage is the client for interacting with the LarkMessage builders.
	LarkMessage *LarkMessageClient
	// Match is the client for interacting with the Match builders.
	Match *MatchClient
	// MatchRound is the client for interacting with the MatchRound builders.
	MatchRound *MatchRoundClient
	// Team is the client for interacting with the Team builders.
	Team *TeamClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.BilibiliHighlightPublication = NewBilibiliHighlightPublicationClient(c.config)
	c.HighlightClip = NewHighlightClipClient(c.config)
	c.LarkBitableRecord = NewLarkBitableRecordClient(c.config)
	c.LarkMessage = NewLarkMessageClient(c.config)
	c.Match = NewMatchClient(c.config)
	c.MatchRound = NewMatchRoundClient(c.config)
	c.Team = NewTeamClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                          ctx,
		config:                       cfg,
		BilibiliHighlightPublication: NewBilibiliHighlightPublicationClient(cfg),
		HighlightClip:                NewHighlightClipClient(cfg),
		LarkBitableRecord:            NewLarkBitableRecordClient(cfg),
		LarkMessage:                  NewLarkMessageClient(cfg),
		Match:                        NewMatchClient(cfg),
		MatchRound:                   NewMatchRoundClient(cfg),
		Team:                         NewTeamClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                          ctx,
		config:                       cfg,
		BilibiliHighlightPublication: NewBilibiliHighlightPublicationClient(cfg),
		HighlightClip:                NewHighlightClipClient(cfg),
		LarkBitableRecord:            NewLarkBitableRecordClient(cfg),
		LarkMessage:                  NewLarkMessageClient(cfg),
		Match:                        NewMatchClient(cfg),
		MatchRound:                   NewMatchRoundClient(cfg),
		Team:                         NewTeamClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BilibiliHighlightPublication.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.BilibiliHighlightPublication, c.HighlightClip, c.LarkBitableRecord,
		c.LarkMessage, c.Match, c.MatchRound, c.Team,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.BilibiliHighlightPublication, c.HighlightClip, c.LarkBitableRecord,
		c.LarkMessage, c.Match, c.MatchRound, c.Team,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BilibiliHighlightPublicationMutation:
		return c.BilibiliHighlightPublication.mutate(ctx, m)
	case *HighlightClipMutation:
		return c.HighlightClip.mutate(ctx, m)
	case *LarkBitableRecordMutation:
		return c.LarkBitableRecord.mutate(ctx, m)
	case *LarkMessageMutation:
		return c.LarkMessage.mutate(ctx, m)
	case *MatchMutation:
		return c.Match.mutate(ctx, m)
	case *MatchRoundMutation:
		return c.MatchRound.mutate(ctx, m)
	case *TeamMutation:
		return c.Team.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BilibiliHighlightPublicationClient is a client for the BilibiliHighlightPublication schema.
type BilibiliHighlightPublicationClient struct {
	config
}

// NewBilibiliHighlightPublicationClient returns a client for the BilibiliHighlightPublication from the given config.
func NewBilibiliHighlightPublicationClient(c config) *BilibiliHighlightPublicationClient {
	return &BilibiliHighlightPublicationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bilibilihighlightpublication.Hooks(f(g(h())))`.
func (c *BilibiliHighlightPublicationClient) Use(hooks ...Hook) {
	c.hooks.BilibiliHighlightPublication = append(c.hooks.BilibiliHighlightPublication, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bilibilihighlightpublication.Intercept(f(g(h())))`.
func (c *BilibiliHighlightPublicationClient) Intercept(interceptors ...Interceptor) {
	c.inters.BilibiliHighlightPublication = append(c.inters.BilibiliHighlightPublication, interceptors...)
}

// Create returns a builder for creating a BilibiliHighlightPublication entity.
func (c *BilibiliHighlightPublicationClient) Create() *BilibiliHighlightPublicationCreate {
	mutation := newBilibiliHighlightPublicationMutation(c.config, OpCreate)
	return &BilibiliHighlightPublicationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BilibiliHighlightPublication entities.
func (c *BilibiliHighlightPublicationClient) CreateBulk(builders ...*BilibiliHighlightPublicationCreate) *BilibiliHighlightPublicationCreateBulk {
	return &BilibiliHighlightPublicationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BilibiliHighlightPublicationClient) MapCreateBulk(slice any, setFunc func(*BilibiliHighlightPublicationCreate, int)) *BilibiliHighlightPublicationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BilibiliHighlightPublicationCreateBulk{err: fmt.Errorf("calling to BilibiliHighlightPublicationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BilibiliHighlightPublicationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BilibiliHighlightPublicationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BilibiliHighlightPublication.
func (c *BilibiliHighlightPublicationClient) Update() *BilibiliHighlightPublicationUpdate {
	mutation := newBilibiliHighlightPublicationMutation(c.config, OpUpdate)
	return &BilibiliHighlightPublicationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BilibiliHighlightPublicationClient) UpdateOne(_m *BilibiliHighlightPublication) *BilibiliHighlightPublicationUpdateOne {
	mutation := newBilibiliHighlightPublicationMutation(c.config, OpUpdateOne, withBilibiliHighlightPublication(_m))
	return &BilibiliHighlightPublicationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BilibiliHighlightPublicationClient) UpdateOneID(id int) *BilibiliHighlightPublicationUpdateOne {
	mutation := newBilibiliHighlightPublicationMutation(c.config, OpUpdateOne, withBilibiliHighlightPublicationID(id))
	return &BilibiliHighlightPublicationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BilibiliHighlightPublication.
func (c *BilibiliHighlightPublicationClient) Delete() *BilibiliHighlightPublicationDelete {
	mutation := newBilibiliHighlightPublicationMutation(c.config, OpDelete)
	return &BilibiliHighlightPublicationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BilibiliHighlightPublicationClient) DeleteOne(_m *BilibiliHighlightPublication) *BilibiliHighlightPublicationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BilibiliHighlightPublicationClient) DeleteOneID(id int) *BilibiliHighlightPublicationDeleteOne {
	builder := c.Delete().Where(bilibilihighlightpublication.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BilibiliHighlightPublicationDeleteOne{builder}
}

// Query returns a query builder for BilibiliHighlightPublication.
func (c *BilibiliHighlightPublicationClient) Query() *BilibiliHighlightPublicationQuery {
	return &BilibiliHighlightPublicationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBilibiliHighlightPublication},
		inters: c.Interceptors(),
	}
}

// Get returns a BilibiliHighlightPublication entity by its id.
func (c *BilibiliHighlightPublicationClient) Get(ctx context.Context, id int) (*BilibiliHighlightPublication, error) {
	return c.Query().Where(bilibilihighlightpublication.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BilibiliHighlightPublicationClient) GetX(ctx context.Context, id int) *BilibiliHighlightPublication {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryHighlightClip queries the highlight_clip edge of a BilibiliHighlightPublication.
func (c *BilibiliHighlightPublicationClient) QueryHighlightClip(_m *BilibiliHighlightPublication) *HighlightClipQuery {
	query := (&HighlightClipClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bilibilihighlightpublication.Table, bilibilihighlightpublication.FieldID, id),
			sqlgraph.To(highlightclip.Table, highlightclip.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bilibilihighlightpublication.HighlightClipTable, bilibilihighlightpublication.HighlightClipColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BilibiliHighlightPublicationClient) Hooks() []Hook {
	return c.hooks.BilibiliHighlightPublication
}

// Interceptors returns the client interceptors.
func (c *BilibiliHighlightPublicationClient) Interceptors() []Interceptor {
	return c.inters.BilibiliHighlightPublication
}

func (c *BilibiliHighlightPublicationClient) mutate(ctx context.Context, m *BilibiliHighlightPublicationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BilibiliHighlightPublicationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BilibiliHighlightPublicationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BilibiliHighlightPublicationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BilibiliHighlightPublicationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BilibiliHighlightPublication mutation op: %q", m.Op())
	}
}

// HighlightClipClient is a client for the HighlightClip schema.
type HighlightClipClient struct {
	config
}

// NewHighlightClipClient returns a client for the HighlightClip from the given config.
func NewHighlightClipClient(c config) *HighlightClipClient {
	return &HighlightClipClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `highlightclip.Hooks(f(g(h())))`.
func (c *HighlightClipClient) Use(hooks ...Hook) {
	c.hooks.HighlightClip = append(c.hooks.HighlightClip, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `highlightclip.Intercept(f(g(h())))`.
func (c *HighlightClipClient) Intercept(interceptors ...Interceptor) {
	c.inters.HighlightClip = append(c.inters.HighlightClip, interceptors...)
}

// Create returns a builder for creating a HighlightClip entity.
func (c *HighlightClipClient) Create() *HighlightClipCreate {
	mutation := newHighlightClipMutation(c.config, OpCreate)
	return &HighlightClipCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of HighlightClip entities.
func (c *HighlightClipClient) CreateBulk(builders ...*HighlightClipCreate) *HighlightClipCreateBulk {
	return &HighlightClipCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *HighlightClipClient) MapCreateBulk(slice any, setFunc func(*HighlightClipCreate, int)) *HighlightClipCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &HighlightClipCreateBulk{err: fmt.Errorf("calling to HighlightClipClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*HighlightClipCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &HighlightClipCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for HighlightClip.
func (c *HighlightClipClient) Update() *HighlightClipUpdate {
	mutation := newHighlightClipMutation(c.config, OpUpdate)
	return &HighlightClipUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HighlightClipClient) UpdateOne(_m *HighlightClip) *HighlightClipUpdateOne {
	mutation := newHighlightClipMutation(c.config, OpUpdateOne, withHighlightClip(_m))
	return &HighlightClipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HighlightClipClient) UpdateOneID(id int) *HighlightClipUpdateOne {
	mutation := newHighlightClipMutation(c.config, OpUpdateOne, withHighlightClipID(id))
	return &HighlightClipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for HighlightClip.
func (c *HighlightClipClient) Delete() *HighlightClipDelete {
	mutation := newHighlightClipMutation(c.config, OpDelete)
	return &HighlightClipDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *HighlightClipClient) DeleteOne(_m *HighlightClip) *HighlightClipDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *HighlightClipClient) DeleteOneID(id int) *HighlightClipDeleteOne {
	builder := c.Delete().Where(highlightclip.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HighlightClipDeleteOne{builder}
}

// Query returns a query builder for HighlightClip.
func (c *HighlightClipClient) Query() *HighlightClipQuery {
	return &HighlightClipQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeHighlightClip},
		inters: c.Interceptors(),
	}
}

// Get returns a HighlightClip entity by its id.
func (c *HighlightClipClient) Get(ctx context.Context, id int) (*HighlightClip, error) {
	return c.Query().Where(highlightclip.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HighlightClipClient) GetX(ctx context.Context, id int) *HighlightClip {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMatchRound queries the match_round edge of a HighlightClip.
func (c *HighlightClipClient) QueryMatchRound(_m *HighlightClip) *MatchRoundQuery {
	query := (&MatchRoundClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(highlightclip.Table, highlightclip.FieldID, id),
			sqlgraph.To(matchround.Table, matchround.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, highlightclip.MatchRoundTable, highlightclip.MatchRoundColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBilibiliPublications queries the bilibili_publications edge of a HighlightClip.
func (c *HighlightClipClient) QueryBilibiliPublications(_m *HighlightClip) *BilibiliHighlightPublicationQuery {
	query := (&BilibiliHighlightPublicationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(highlightclip.Table, highlightclip.FieldID, id),
			sqlgraph.To(bilibilihighlightpublication.Table, bilibilihighlightpublication.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, highlightclip.BilibiliPublicationsTable, highlightclip.BilibiliPublicationsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *HighlightClipClient) Hooks() []Hook {
	return c.hooks.HighlightClip
}

// Interceptors returns the client interceptors.
func (c *HighlightClipClient) Interceptors() []Interceptor {
	return c.inters.HighlightClip
}

func (c *HighlightClipClient) mutate(ctx context.Context, m *HighlightClipMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&HighlightClipCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&HighlightClipUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&HighlightClipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&HighlightClipDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown HighlightClip mutation op: %q", m.Op())
	}
}

// LarkBitableRecordClient is a client for the LarkBitableRecord schema.
type LarkBitableRecordClient struct {
	config
}

// NewLarkBitableRecordClient returns a client for the LarkBitableRecord from the given config.
func NewLarkBitableRecordClient(c config) *LarkBitableRecordClient {
	return &LarkBitableRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `larkbitablerecord.Hooks(f(g(h())))`.
func (c *LarkBitableRecordClient) Use(hooks ...Hook) {
	c.hooks.LarkBitableRecord = append(c.hooks.LarkBitableRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `larkbitablerecord.Intercept(f(g(h())))`.
func (c *LarkBitableRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.LarkBitableRecord = append(c.inters.LarkBitableRecord, interceptors...)
}

// Create returns a builder for creating a LarkBitableRecord entity.
func (c *LarkBitableRecordClient) Create() *LarkBitableRecordCreate {
	mutation := newLarkBitableRecordMutation(c.config, OpCreate)
	return &LarkBitableRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LarkBitableRecord entities.
func (c *LarkBitableRecordClient) CreateBulk(builders ...*LarkBitableRecordCreate) *LarkBitableRecordCreateBulk {
	return &LarkBitableRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LarkBitableRecordClient) MapCreateBulk(slice any, setFunc func(*LarkBitableRecordCreate, int)) *LarkBitableRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LarkBitableRecordCreateBulk{err: fmt.Errorf("calling to LarkBitableRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LarkBitableRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LarkBitableRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LarkBitableRecord.
func (c *LarkBitableRecordClient) Update() *LarkBitableRecordUpdate {
	mutation := newLarkBitableRecordMutation(c.config, OpUpdate)
	return &LarkBitableRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LarkBitableRecordClient) UpdateOne(_m *LarkBitableRecord) *LarkBitableRecordUpdateOne {
	mutation := newLarkBitableRecordMutation(c.config, OpUpdateOne, withLarkBitableRecord(_m))
	return &LarkBitableRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LarkBitableRecordClient) UpdateOneID(id int) *LarkBitableRecordUpdateOne {
	mutation := newLarkBitableRecordMutation(c.config, OpUpdateOne, withLarkBitableRecordID(id))
	return &LarkBitableRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LarkBitableRecord.
func (c *LarkBitableRecordClient) Delete() *LarkBitableRecordDelete {
	mutation := newLarkBitableRecordMutation(c.config, OpDelete)
	return &LarkBitableRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LarkBitableRecordClient) DeleteOne(_m *LarkBitableRecord) *LarkBitableRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LarkBitableRecordClient) DeleteOneID(id int) *LarkBitableRecordDeleteOne {
	builder := c.Delete().Where(larkbitablerecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LarkBitableRecordDeleteOne{builder}
}

// Query returns a query builder for LarkBitableRecord.
func (c *LarkBitableRecordClient) Query() *LarkBitableRecordQuery {
	return &LarkBitableRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLarkBitableRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a LarkBitableRecord entity by its id.
func (c *LarkBitableRecordClient) Get(ctx context.Context, id int) (*LarkBitableRecord, error) {
	return c.Query().Where(larkbitablerecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LarkBitableRecordClient) GetX(ctx context.Context, id int) *LarkBitableRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMatchRound queries the match_round edge of a LarkBitableRecord.
func (c *LarkBitableRecordClient) QueryMatchRound(_m *LarkBitableRecord) *MatchRoundQuery {
	query := (&MatchRoundClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(larkbitablerecord.Table, larkbitablerecord.FieldID, id),
			sqlgraph.To(matchround.Table, matchround.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, larkbitablerecord.MatchRoundTable, larkbitablerecord.MatchRoundColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LarkBitableRecordClient) Hooks() []Hook {
	return c.hooks.LarkBitableRecord
}

// Interceptors returns the client interceptors.
func (c *LarkBitableRecordClient) Interceptors() []Interceptor {
	return c.inters.LarkBitableRecord
}

func (c *LarkBitableRecordClient) mutate(ctx context.Context, m *LarkBitableRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LarkBitableRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LarkBitableRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LarkBitableRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LarkBitableRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LarkBitableRecord mutation op: %q", m.Op())
	}
}

// LarkMessageClient is a client for the LarkMessage schema.
type LarkMessageClient struct {
	config
}

// NewLarkMessageClient returns a client for the LarkMessage from the given config.
func NewLarkMessageClient(c config) *LarkMessageClient {
	return &LarkMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `larkmessage.Hooks(f(g(h())))`.
func (c *LarkMessageClient) Use(hooks ...Hook) {
	c.hooks.LarkMessage = append(c.hooks.LarkMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `larkmessage.Intercept(f(g(h())))`.
func (c *LarkMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.LarkMessage = append(c.inters.LarkMessage, interceptors...)
}

// Create returns a builder for creating a LarkMessage entity.
func (c *LarkMessageClient) Create() *LarkMessageCreate {
	mutation := newLarkMessageMutation(c.config, OpCreate)
	return &LarkMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LarkMessage entities.
func (c *LarkMessageClient) CreateBulk(builders ...*LarkMessageCreate) *LarkMessageCreateBulk {
	return &LarkMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LarkMessageClient) MapCreateBulk(slice any, setFunc func(*LarkMessageCreate, int)) *LarkMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LarkMessageCreateBulk{err: fmt.Errorf("calling to LarkMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LarkMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LarkMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LarkMessage.
func (c *LarkMessageClient) Update() *LarkMessageUpdate {
	mutation := newLarkMessageMutation(c.config, OpUpdate)
	return &LarkMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LarkMessageClient) UpdateOne(_m *LarkMessage) *LarkMessageUpdateOne {
	mutation := newLarkMessageMutation(c.config, OpUpdateOne, withLarkMessage(_m))
	return &LarkMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LarkMessageClient) UpdateOneID(id int) *LarkMessageUpdateOne {
	mutation := newLarkMessageMutation(c.config, OpUpdateOne, withLarkMessageID(id))
	return &LarkMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LarkMessage.
func (c *LarkMessageClient) Delete() *LarkMessageDelete {
	mutation := newLarkMessageMutation(c.config, OpDelete)
	return &LarkMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LarkMessageClient) DeleteOne(_m *LarkMessage) *LarkMessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LarkMessageClient) DeleteOneID(id int) *LarkMessageDeleteOne {
	builder := c.Delete().Where(larkmessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LarkMessageDeleteOne{builder}
}

// Query returns a query builder for LarkMessage.
func (c *LarkMessageClient) Query() *LarkMessageQuery {
	return &LarkMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLarkMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a LarkMessage entity by its id.
func (c *LarkMessageClient) Get(ctx context.Context, id int) (*LarkMessage, error) {
	return c.Query().Where(larkmessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LarkMessageClient) GetX(ctx context.Context, id int) *LarkMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMatch queries the match edge of a LarkMessage.
func (c *LarkMessageClient) QueryMatch(_m *LarkMessage) *MatchQuery {
	query := (&MatchClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(larkmessage.Table, larkmessage.FieldID, id),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, larkmessage.MatchTable, larkmessage.MatchColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LarkMessageClient) Hooks() []Hook {
	return c.hooks.LarkMessage
}

// Interceptors returns the client interceptors.
func (c *LarkMessageClient) Interceptors() []Interceptor {
	return c.inters.LarkMessage
}

func (c *LarkMessageClient) mutate(ctx context.Context, m *LarkMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LarkMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LarkMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LarkMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LarkMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LarkMessage mutation op: %q", m.Op())
	}
}

// MatchClient is a client for the Match schema.
type MatchClient struct {
	config
}

// NewMatchClient returns a client for the Match from the given config.
func NewMatchClient(c config) *MatchClient {
	return &MatchClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `match.Hooks(f(g(h())))`.
func (c *MatchClient) Use(hooks ...Hook) {
	c.hooks.Match = append(c.hooks.Match, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `match.Intercept(f(g(h())))`.
func (c *MatchClient) Intercept(interceptors ...Interceptor) {
	c.inters.Match = append(c.inters.Match, interceptors...)
}

// Create returns a builder for creating a Match entity.
func (c *MatchClient) Create() *MatchCreate {
	mutation := newMatchMutation(c.config, OpCreate)
	return &MatchCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Match entities.
func (c *MatchClient) CreateBulk(builders ...*MatchCreate) *MatchCreateBulk {
	return &MatchCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MatchClient) MapCreateBulk(slice any, setFunc func(*MatchCreate, int)) *MatchCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MatchCreateBulk{err: fmt.Errorf("calling to MatchClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MatchCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MatchCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Match.
func (c *MatchClient) Update() *MatchUpdate {
	mutation := newMatchMutation(c.config, OpUpdate)
	return &MatchUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MatchClient) UpdateOne(_m *Match) *MatchUpdateOne {
	mutation := newMatchMutation(c.config, OpUpdateOne, withMatch(_m))
	return &MatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MatchClient) UpdateOneID(id string) *MatchUpdateOne {
	mutation := newMatchMutation(c.config, OpUpdateOne, withMatchID(id))
	return &MatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Match.
func (c *MatchClient) Delete() *MatchDelete {
	mutation := newMatchMutation(c.config, OpDelete)
	return &MatchDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MatchClient) DeleteOne(_m *Match) *MatchDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MatchClient) DeleteOneID(id string) *MatchDeleteOne {
	builder := c.Delete().Where(match.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MatchDeleteOne{builder}
}

// Query returns a query builder for Match.
func (c *MatchClient) Query() *MatchQuery {
	return &MatchQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMatch},
		inters: c.Interceptors(),
	}
}

// Get returns a Match entity by its id.
func (c *MatchClient) Get(ctx context.Context, id string) (*Match, error) {
	return c.Query().Where(match.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MatchClient) GetX(ctx context.Context, id string) *Match {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRedTeam queries the red_team edge of a Match.
func (c *MatchClient) QueryRedTeam(_m *Match) *TeamQuery {
	query := (&TeamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(match.Table, match.FieldID, id),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, match.RedTeamTable, match.RedTeamColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBlueTeam queries the blue_team edge of a Match.
func (c *MatchClient) QueryBlueTeam(_m *Match) *TeamQuery {
	query := (&TeamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(match.Table, match.FieldID, id),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, match.BlueTeamTable, match.BlueTeamColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRounds queries the rounds edge of a Match.
func (c *MatchClient) QueryRounds(_m *Match) *MatchRoundQuery {
	query := (&MatchRoundClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(match.Table, match.FieldID, id),
			sqlgraph.To(matchround.Table, matchround.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, match.RoundsTable, match.RoundsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLarkMessages queries the lark_messages edge of a Match.
func (c *MatchClient) QueryLarkMessages(_m *Match) *LarkMessageQuery {
	query := (&LarkMessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(match.Table, match.FieldID, id),
			sqlgraph.To(larkmessage.Table, larkmessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, match.LarkMessagesTable, match.LarkMessagesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MatchClient) Hooks() []Hook {
	return c.hooks.Match
}

// Interceptors returns the client interceptors.
func (c *MatchClient) Interceptors() []Interceptor {
	return c.inters.Match
}

func (c *MatchClient) mutate(ctx context.Context, m *MatchMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MatchCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MatchUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MatchDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Match mutation op: %q", m.Op())
	}
}

// MatchRoundClient is a client for the MatchRound schema.
type MatchRoundClient struct {
	config
}

// NewMatchRoundClient returns a client for the MatchRound from the given config.
func NewMatchRoundClient(c config) *MatchRoundClient {
	return &MatchRoundClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `matchround.Hooks(f(g(h())))`.
func (c *MatchRoundClient) Use(hooks ...Hook) {
	c.hooks.MatchRound = append(c.hooks.MatchRound, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `matchround.Intercept(f(g(h())))`.
func (c *MatchRoundClient) Intercept(interceptors ...Interceptor) {
	c.inters.MatchRound = append(c.inters.MatchRound, interceptors...)
}

// Create returns a builder for creating a MatchRound entity.
func (c *MatchRoundClient) Create() *MatchRoundCreate {
	mutation := newMatchRoundMutation(c.config, OpCreate)
	return &MatchRoundCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MatchRound entities.
func (c *MatchRoundClient) CreateBulk(builders ...*MatchRoundCreate) *MatchRoundCreateBulk {
	return &MatchRoundCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MatchRoundClient) MapCreateBulk(slice any, setFunc func(*MatchRoundCreate, int)) *MatchRoundCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MatchRoundCreateBulk{err: fmt.Errorf("calling to MatchRoundClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MatchRoundCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MatchRoundCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MatchRound.
func (c *MatchRoundClient) Update() *MatchRoundUpdate {
	mutation := newMatchRoundMutation(c.config, OpUpdate)
	return &MatchRoundUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MatchRoundClient) UpdateOne(_m *MatchRound) *MatchRoundUpdateOne {
	mutation := newMatchRoundMutation(c.config, OpUpdateOne, withMatchRound(_m))
	return &MatchRoundUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MatchRoundClient) UpdateOneID(id int) *MatchRoundUpdateOne {
	mutation := newMatchRoundMutation(c.config, OpUpdateOne, withMatchRoundID(id))
	return &MatchRoundUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MatchRound.
func (c *MatchRoundClient) Delete() *MatchRoundDelete {
	mutation := newMatchRoundMutation(c.config, OpDelete)
	return &MatchRoundDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MatchRoundClient) DeleteOne(_m *MatchRound) *MatchRoundDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MatchRoundClient) DeleteOneID(id int) *MatchRoundDeleteOne {
	builder := c.Delete().Where(matchround.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MatchRoundDeleteOne{builder}
}

// Query returns a query builder for MatchRound.
func (c *MatchRoundClient) Query() *MatchRoundQuery {
	return &MatchRoundQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMatchRound},
		inters: c.Interceptors(),
	}
}

// Get returns a MatchRound entity by its id.
func (c *MatchRoundClient) Get(ctx context.Context, id int) (*MatchRound, error) {
	return c.Query().Where(matchround.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MatchRoundClient) GetX(ctx context.Context, id int) *MatchRound {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMatch queries the match edge of a MatchRound.
func (c *MatchRoundClient) QueryMatch(_m *MatchRound) *MatchQuery {
	query := (&MatchClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(matchround.Table, matchround.FieldID, id),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, matchround.MatchTable, matchround.MatchColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryHighlightClips queries the highlight_clips edge of a MatchRound.
func (c *MatchRoundClient) QueryHighlightClips(_m *MatchRound) *HighlightClipQuery {
	query := (&HighlightClipClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(matchround.Table, matchround.FieldID, id),
			sqlgraph.To(highlightclip.Table, highlightclip.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, matchround.HighlightClipsTable, matchround.HighlightClipsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLarkBitableRecords queries the lark_bitable_records edge of a MatchRound.
func (c *MatchRoundClient) QueryLarkBitableRecords(_m *MatchRound) *LarkBitableRecordQuery {
	query := (&LarkBitableRecordClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(matchround.Table, matchround.FieldID, id),
			sqlgraph.To(larkbitablerecord.Table, larkbitablerecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, matchround.LarkBitableRecordsTable, matchround.LarkBitableRecordsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MatchRoundClient) Hooks() []Hook {
	return c.hooks.MatchRound
}

// Interceptors returns the client interceptors.
func (c *MatchRoundClient) Interceptors() []Interceptor {
	return c.inters.MatchRound
}

func (c *MatchRoundClient) mutate(ctx context.Context, m *MatchRoundMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MatchRoundCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MatchRoundUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MatchRoundUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MatchRoundDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MatchRound mutation op: %q", m.Op())
	}
}

// TeamClient is a client for the Team schema.
type TeamClient struct {
	config
}

// NewTeamClient returns a client for the Team from the given config.
func NewTeamClient(c config) *TeamClient {
	return &TeamClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `team.Hooks(f(g(h())))`.
func (c *TeamClient) Use(hooks ...Hook) {
	c.hooks.Team = append(c.hooks.Team, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `team.Intercept(f(g(h())))`.
func (c *TeamClient) Intercept(interceptors ...Interceptor) {
	c.inters.Team = append(c.inters.Team, interceptors...)
}

// Create returns a builder for creating a Team entity.
func (c *TeamClient) Create() *TeamCreate {
	mutation := newTeamMutation(c.config, OpCreate)
	return &TeamCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Team entities.
func (c *TeamClient) CreateBulk(builders ...*TeamCreate) *TeamCreateBulk {
	return &TeamCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TeamClient) MapCreateBulk(slice any, setFunc func(*TeamCreate, int)) *TeamCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TeamCreateBulk{err: fmt.Errorf("calling to TeamClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TeamCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TeamCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Team.
func (c *TeamClient) Update() *TeamUpdate {
	mutation := newTeamMutation(c.config, OpUpdate)
	return &TeamUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TeamClient) UpdateOne(_m *Team) *TeamUpdateOne {
	mutation := newTeamMutation(c.config, OpUpdateOne, withTeam(_m))
	return &TeamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TeamClient) UpdateOneID(id string) *TeamUpdateOne {
	mutation := newTeamMutation(c.config, OpUpdateOne, withTeamID(id))
	return &TeamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Team.
func (c *TeamClient) Delete() *TeamDelete {
	mutation := newTeamMutation(c.config, OpDelete)
	return &TeamDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TeamClient) DeleteOne(_m *Team) *TeamDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TeamClient) DeleteOneID(id string) *TeamDeleteOne {
	builder := c.Delete().Where(team.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TeamDeleteOne{builder}
}

// Query returns a query builder for Team.
func (c *TeamClient) Query() *TeamQuery {
	return &TeamQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTeam},
		inters: c.Interceptors(),
	}
}

// Get returns a Team entity by its id.
func (c *TeamClient) Get(ctx context.Context, id string) (*Team, error) {
	return c.Query().Where(team.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TeamClient) GetX(ctx context.Context, id string) *Team {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRedMatches queries the red_matches edge of a Team.
func (c *TeamClient) QueryRedMatches(_m *Team) *MatchQuery {
	query := (&MatchClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(team.Table, team.FieldID, id),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, team.RedMatchesTable, team.RedMatchesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBlueMatches queries the blue_matches edge of a Team.
func (c *TeamClient) QueryBlueMatches(_m *Team) *MatchQuery {
	query := (&MatchClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(team.Table, team.FieldID, id),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, team.BlueMatchesTable, team.BlueMatchesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TeamClient) Hooks() []Hook {
	return c.hooks.Team
}

// Interceptors returns the client interceptors.
func (c *TeamClient) Interceptors() []Interceptor {
	return c.inters.Team
}

func (c *TeamClient) mutate(ctx context.Context, m *TeamMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TeamCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TeamUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TeamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TeamDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Team mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		BilibiliHighlightPublication, HighlightClip, LarkBitableRecord, LarkMessage,
		Match, MatchRound, Team []ent.Hook
	}
	inters struct {
		BilibiliHighlightPublication, HighlightClip, LarkBitableRecord, LarkMessage,
		Match, MatchRound, Team []ent.Interceptor
	}
)
