// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"scutbot.cn/web/rm-monitor/ent/bilibilihighlightpublication"
	"scutbot.cn/web/rm-monitor/ent/highlightclip"
	"scutbot.cn/web/rm-monitor/ent/matchround"
	"scutbot.cn/web/rm-monitor/ent/predicate"
)

// HighlightClipUpdate is the builder for updating HighlightClip entities.
type HighlightClipUpdate struct {
	config
	hooks    []Hook
	mutation *HighlightClipMutation
}

// Where appends a list predicates to the HighlightClipUpdate builder.
func (_u *HighlightClipUpdate) Where(ps ...predicate.HighlightClip) *HighlightClipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHighlightIndex sets the "highlight_index" field.
func (_u *HighlightClipUpdate) SetHighlightIndex(v int) *HighlightClipUpdate {
	_u.mutation.ResetHighlightIndex()
	_u.mutation.SetHighlightIndex(v)
	return _u
}

// SetNillableHighlightIndex sets the "highlight_index" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableHighlightIndex(v *int) *HighlightClipUpdate {
	if v != nil {
		_u.SetHighlightIndex(*v)
	}
	return _u
}

// AddHighlightIndex adds value to the "highlight_index" field.
func (_u *HighlightClipUpdate) AddHighlightIndex(v int) *HighlightClipUpdate {
	_u.mutation.AddHighlightIndex(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *HighlightClipUpdate) SetRole(v string) *HighlightClipUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableRole(v *string) *HighlightClipUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetAlgorithmVersion sets the "algorithm_version" field.
func (_u *HighlightClipUpdate) SetAlgorithmVersion(v string) *HighlightClipUpdate {
	_u.mutation.SetAlgorithmVersion(v)
	return _u
}

// SetNillableAlgorithmVersion sets the "algorithm_version" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableAlgorithmVersion(v *string) *HighlightClipUpdate {
	if v != nil {
		_u.SetAlgorithmVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *HighlightClipUpdate) SetStatus(v highlightclip.Status) *HighlightClipUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableStatus(v *highlightclip.Status) *HighlightClipUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *HighlightClipUpdate) SetPriority(v int) *HighlightClipUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillablePriority(v *int) *HighlightClipUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *HighlightClipUpdate) AddPriority(v int) *HighlightClipUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetStartSeconds sets the "start_seconds" field.
func (_u *HighlightClipUpdate) SetStartSeconds(v float64) *HighlightClipUpdate {
	_u.mutation.ResetStartSeconds()
	_u.mutation.SetStartSeconds(v)
	return _u
}

// SetNillableStartSeconds sets the "start_seconds" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableStartSeconds(v *float64) *HighlightClipUpdate {
	if v != nil {
		_u.SetStartSeconds(*v)
	}
	return _u
}

// AddStartSeconds adds value to the "start_seconds" field.
func (_u *HighlightClipUpdate) AddStartSeconds(v float64) *HighlightClipUpdate {
	_u.mutation.AddStartSeconds(v)
	return _u
}

// SetEndSeconds sets the "end_seconds" field.
func (_u *HighlightClipUpdate) SetEndSeconds(v float64) *HighlightClipUpdate {
	_u.mutation.ResetEndSeconds()
	_u.mutation.SetEndSeconds(v)
	return _u
}

// SetNillableEndSeconds sets the "end_seconds" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableEndSeconds(v *float64) *HighlightClipUpdate {
	if v != nil {
		_u.SetEndSeconds(*v)
	}
	return _u
}

// AddEndSeconds adds value to the "end_seconds" field.
func (_u *HighlightClipUpdate) AddEndSeconds(v float64) *HighlightClipUpdate {
	_u.mutation.AddEndSeconds(v)
	return _u
}

// SetPeakSeconds sets the "peak_seconds" field.
func (_u *HighlightClipUpdate) SetPeakSeconds(v float64) *HighlightClipUpdate {
	_u.mutation.ResetPeakSeconds()
	_u.mutation.SetPeakSeconds(v)
	return _u
}

// SetNillablePeakSeconds sets the "peak_seconds" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillablePeakSeconds(v *float64) *HighlightClipUpdate {
	if v != nil {
		_u.SetPeakSeconds(*v)
	}
	return _u
}

// AddPeakSeconds adds value to the "peak_seconds" field.
func (_u *HighlightClipUpdate) AddPeakSeconds(v float64) *HighlightClipUpdate {
	_u.mutation.AddPeakSeconds(v)
	return _u
}

// SetSourcePath sets the "source_path" field.
func (_u *HighlightClipUpdate) SetSourcePath(v string) *HighlightClipUpdate {
	_u.mutation.SetSourcePath(v)
	return _u
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableSourcePath(v *string) *HighlightClipUpdate {
	if v != nil {
		_u.SetSourcePath(*v)
	}
	return _u
}

// SetOutputDir sets the "output_dir" field.
func (_u *HighlightClipUpdate) SetOutputDir(v string) *HighlightClipUpdate {
	_u.mutation.SetOutputDir(v)
	return _u
}

// SetNillableOutputDir sets the "output_dir" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableOutputDir(v *string) *HighlightClipUpdate {
	if v != nil {
		_u.SetOutputDir(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *HighlightClipUpdate) SetTitle(v string) *HighlightClipUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableTitle(v *string) *HighlightClipUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *HighlightClipUpdate) ClearTitle() *HighlightClipUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetDescription sets the "description" field.
func (_u *HighlightClipUpdate) SetDescription(v string) *HighlightClipUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableDescription(v *string) *HighlightClipUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *HighlightClipUpdate) ClearDescription() *HighlightClipUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTags sets the "tags" field.
func (_u *HighlightClipUpdate) SetTags(v []string) *HighlightClipUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *HighlightClipUpdate) AppendTags(v []string) *HighlightClipUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *HighlightClipUpdate) ClearTags() *HighlightClipUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetScore sets the "score" field.
func (_u *HighlightClipUpdate) SetScore(v float64) *HighlightClipUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableScore(v *float64) *HighlightClipUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *HighlightClipUpdate) AddScore(v float64) *HighlightClipUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetModelPayload sets the "model_payload" field.
func (_u *HighlightClipUpdate) SetModelPayload(v string) *HighlightClipUpdate {
	_u.mutation.SetModelPayload(v)
	return _u
}

// SetNillableModelPayload sets the "model_payload" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableModelPayload(v *string) *HighlightClipUpdate {
	if v != nil {
		_u.SetModelPayload(*v)
	}
	return _u
}

// ClearModelPayload clears the value of the "model_payload" field.
func (_u *HighlightClipUpdate) ClearModelPayload() *HighlightClipUpdate {
	_u.mutation.ClearModelPayload()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *HighlightClipUpdate) SetCompletedAt(v time.Time) *HighlightClipUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *HighlightClipUpdate) SetNillableCompletedAt(v *time.Time) *HighlightClipUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *HighlightClipUpdate) ClearCompletedAt() *HighlightClipUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HighlightClipUpdate) SetUpdatedAt(v time.Time) *HighlightClipUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMatchRoundID sets the "match_round" edge to the MatchRound entity by ID.
func (_u *HighlightClipUpdate) SetMatchRoundID(id int) *HighlightClipUpdate {
	_u.mutation.SetMatchRoundID(id)
	return _u
}

// SetMatchRound sets the "match_round" edge to the MatchRound entity.
func (_u *HighlightClipUpdate) SetMatchRound(v *MatchRound) *HighlightClipUpdate {
	return _u.SetMatchRoundID(v.ID)
}

// AddBilibiliPublicationIDs adds the "bilibili_publications" edge to the BilibiliHighlightPublication entity by IDs.
func (_u *HighlightClipUpdate) AddBilibiliPublicationIDs(ids ...int) *HighlightClipUpdate {
	_u.mutation.AddBilibiliPublicationIDs(ids...)
	return _u
}

// AddBilibiliPublications adds the "bilibili_publications" edges to the BilibiliHighlightPublication entity.
func (_u *HighlightClipUpdate) AddBilibiliPublications(v ...*BilibiliHighlightPublication) *HighlightClipUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBilibiliPublicationIDs(ids...)
}

// Mutation returns the HighlightClipMutation object of the builder.
func (_u *HighlightClipUpdate) Mutation() *HighlightClipMutation {
	return _u.mutation
}

// ClearMatchRound clears the "match_round" edge to the MatchRound entity.
func (_u *HighlightClipUpdate) ClearMatchRound() *HighlightClipUpdate {
	_u.mutation.ClearMatchRound()
	return _u
}

// ClearBilibiliPublications clears all "bilibili_publications" edges to the BilibiliHighlightPublication entity.
func (_u *HighlightClipUpdate) ClearBilibiliPublications() *HighlightClipUpdate {
	_u.mutation.ClearBilibiliPublications()
	return _u
}

// RemoveBilibiliPublicationIDs removes the "bilibili_publications" edge to BilibiliHighlightPublication entities by IDs.
func (_u *HighlightClipUpdate) RemoveBilibiliPublicationIDs(ids ...int) *HighlightClipUpdate {
	_u.mutation.RemoveBilibiliPublicationIDs(ids...)
	return _u
}

// RemoveBilibiliPublications removes "bilibili_publications" edges to BilibiliHighlightPublication entities.
func (_u *HighlightClipUpdate) RemoveBilibiliPublications(v ...*BilibiliHighlightPublication) *HighlightClipUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBilibiliPublicationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HighlightClipUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HighlightClipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HighlightClipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HighlightClipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HighlightClipUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := highlightclip.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HighlightClipUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := highlightclip.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HighlightClip.status": %w`, err)}
		}
	}
	if _u.mutation.MatchRoundCleared() && len(_u.mutation.MatchRoundIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HighlightClip.match_round"`)
	}
	return nil
}

func (_u *HighlightClipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(highlightclip.Table, highlightclip.Columns, sqlgraph.NewFieldSpec(highlightclip.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.HighlightIndex(); ok {
		_spec.SetField(highlightclip.FieldHighlightIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHighlightIndex(); ok {
		_spec.AddField(highlightclip.FieldHighlightIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(highlightclip.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlgorithmVersion(); ok {
		_spec.SetField(highlightclip.FieldAlgorithmVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(highlightclip.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(highlightclip.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(highlightclip.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartSeconds(); ok {
		_spec.SetField(highlightclip.FieldStartSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStartSeconds(); ok {
		_spec.AddField(highlightclip.FieldStartSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EndSeconds(); ok {
		_spec.SetField(highlightclip.FieldEndSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEndSeconds(); ok {
		_spec.AddField(highlightclip.FieldEndSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PeakSeconds(); ok {
		_spec.SetField(highlightclip.FieldPeakSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPeakSeconds(); ok {
		_spec.AddField(highlightclip.FieldPeakSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SourcePath(); ok {
		_spec.SetField(highlightclip.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputDir(); ok {
		_spec.SetField(highlightclip.FieldOutputDir, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(highlightclip.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(highlightclip.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(highlightclip.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(highlightclip.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(highlightclip.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, highlightclip.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(highlightclip.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(highlightclip.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(highlightclip.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ModelPayload(); ok {
		_spec.SetField(highlightclip.FieldModelPayload, field.TypeString, value)
	}
	if _u.mutation.ModelPayloadCleared() {
		_spec.ClearField(highlightclip.FieldModelPayload, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(highlightclip.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(highlightclip.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(highlightclip.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MatchRoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   highlightclip.MatchRoundTable,
			Columns: []string{highlightclip.MatchRoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchRoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   highlightclip.MatchRoundTable,
			Columns: []string{highlightclip.MatchRoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BilibiliPublicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   highlightclip.BilibiliPublicationsTable,
			Columns: []string{highlightclip.BilibiliPublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bilibilihighlightpublication.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBilibiliPublicationsIDs(); len(nodes) > 0 && !_u.mutation.BilibiliPublicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   highlightclip.BilibiliPublicationsTable,
			Columns: []string{highlightclip.BilibiliPublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bilibilihighlightpublication.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BilibiliPublicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   highlightclip.BilibiliPublicationsTable,
			Columns: []string{highlightclip.BilibiliPublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bilibilihighlightpublication.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{highlightclip.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HighlightClipUpdateOne is the builder for updating a single HighlightClip entity.
type HighlightClipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HighlightClipMutation
}

// SetHighlightIndex sets the "highlight_index" field.
func (_u *HighlightClipUpdateOne) SetHighlightIndex(v int) *HighlightClipUpdateOne {
	_u.mutation.ResetHighlightIndex()
	_u.mutation.SetHighlightIndex(v)
	return _u
}

// SetNillableHighlightIndex sets the "highlight_index" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableHighlightIndex(v *int) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetHighlightIndex(*v)
	}
	return _u
}

// AddHighlightIndex adds value to the "highlight_index" field.
func (_u *HighlightClipUpdateOne) AddHighlightIndex(v int) *HighlightClipUpdateOne {
	_u.mutation.AddHighlightIndex(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *HighlightClipUpdateOne) SetRole(v string) *HighlightClipUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableRole(v *string) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetAlgorithmVersion sets the "algorithm_version" field.
func (_u *HighlightClipUpdateOne) SetAlgorithmVersion(v string) *HighlightClipUpdateOne {
	_u.mutation.SetAlgorithmVersion(v)
	return _u
}

// SetNillableAlgorithmVersion sets the "algorithm_version" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableAlgorithmVersion(v *string) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetAlgorithmVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *HighlightClipUpdateOne) SetStatus(v highlightclip.Status) *HighlightClipUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableStatus(v *highlightclip.Status) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *HighlightClipUpdateOne) SetPriority(v int) *HighlightClipUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillablePriority(v *int) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *HighlightClipUpdateOne) AddPriority(v int) *HighlightClipUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetStartSeconds sets the "start_seconds" field.
func (_u *HighlightClipUpdateOne) SetStartSeconds(v float64) *HighlightClipUpdateOne {
	_u.mutation.ResetStartSeconds()
	_u.mutation.SetStartSeconds(v)
	return _u
}

// SetNillableStartSeconds sets the "start_seconds" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableStartSeconds(v *float64) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetStartSeconds(*v)
	}
	return _u
}

// AddStartSeconds adds value to the "start_seconds" field.
func (_u *HighlightClipUpdateOne) AddStartSeconds(v float64) *HighlightClipUpdateOne {
	_u.mutation.AddStartSeconds(v)
	return _u
}

// SetEndSeconds sets the "end_seconds" field.
func (_u *HighlightClipUpdateOne) SetEndSeconds(v float64) *HighlightClipUpdateOne {
	_u.mutation.ResetEndSeconds()
	_u.mutation.SetEndSeconds(v)
	return _u
}

// SetNillableEndSeconds sets the "end_seconds" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableEndSeconds(v *float64) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetEndSeconds(*v)
	}
	return _u
}

// AddEndSeconds adds value to the "end_seconds" field.
func (_u *HighlightClipUpdateOne) AddEndSeconds(v float64) *HighlightClipUpdateOne {
	_u.mutation.AddEndSeconds(v)
	return _u
}

// SetPeakSeconds sets the "peak_seconds" field.
func (_u *HighlightClipUpdateOne) SetPeakSeconds(v float64) *HighlightClipUpdateOne {
	_u.mutation.ResetPeakSeconds()
	_u.mutation.SetPeakSeconds(v)
	return _u
}

// SetNillablePeakSeconds sets the "peak_seconds" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillablePeakSeconds(v *float64) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetPeakSeconds(*v)
	}
	return _u
}

// AddPeakSeconds adds value to the "peak_seconds" field.
func (_u *HighlightClipUpdateOne) AddPeakSeconds(v float64) *HighlightClipUpdateOne {
	_u.mutation.AddPeakSeconds(v)
	return _u
}

// SetSourcePath sets the "source_path" field.
func (_u *HighlightClipUpdateOne) SetSourcePath(v string) *HighlightClipUpdateOne {
	_u.mutation.SetSourcePath(v)
	return _u
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableSourcePath(v *string) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetSourcePath(*v)
	}
	return _u
}

// SetOutputDir sets the "output_dir" field.
func (_u *HighlightClipUpdateOne) SetOutputDir(v string) *HighlightClipUpdateOne {
	_u.mutation.SetOutputDir(v)
	return _u
}

// SetNillableOutputDir sets the "output_dir" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableOutputDir(v *string) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetOutputDir(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *HighlightClipUpdateOne) SetTitle(v string) *HighlightClipUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableTitle(v *string) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *HighlightClipUpdateOne) ClearTitle() *HighlightClipUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetDescription sets the "description" field.
func (_u *HighlightClipUpdateOne) SetDescription(v string) *HighlightClipUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableDescription(v *string) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *HighlightClipUpdateOne) ClearDescription() *HighlightClipUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTags sets the "tags" field.
func (_u *HighlightClipUpdateOne) SetTags(v []string) *HighlightClipUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *HighlightClipUpdateOne) AppendTags(v []string) *HighlightClipUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *HighlightClipUpdateOne) ClearTags() *HighlightClipUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetScore sets the "score" field.
func (_u *HighlightClipUpdateOne) SetScore(v float64) *HighlightClipUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableScore(v *float64) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *HighlightClipUpdateOne) AddScore(v float64) *HighlightClipUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetModelPayload sets the "model_payload" field.
func (_u *HighlightClipUpdateOne) SetModelPayload(v string) *HighlightClipUpdateOne {
	_u.mutation.SetModelPayload(v)
	return _u
}

// SetNillableModelPayload sets the "model_payload" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableModelPayload(v *string) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetModelPayload(*v)
	}
	return _u
}

// ClearModelPayload clears the value of the "model_payload" field.
func (_u *HighlightClipUpdateOne) ClearModelPayload() *HighlightClipUpdateOne {
	_u.mutation.ClearModelPayload()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *HighlightClipUpdateOne) SetCompletedAt(v time.Time) *HighlightClipUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *HighlightClipUpdateOne) SetNillableCompletedAt(v *time.Time) *HighlightClipUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *HighlightClipUpdateOne) ClearCompletedAt() *HighlightClipUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HighlightClipUpdateOne) SetUpdatedAt(v time.Time) *HighlightClipUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMatchRoundID sets the "match_round" edge to the MatchRound entity by ID.
func (_u *HighlightClipUpdateOne) SetMatchRoundID(id int) *HighlightClipUpdateOne {
	_u.mutation.SetMatchRoundID(id)
	return _u
}

// SetMatchRound sets the "match_round" edge to the MatchRound entity.
func (_u *HighlightClipUpdateOne) SetMatchRound(v *MatchRound) *HighlightClipUpdateOne {
	return _u.SetMatchRoundID(v.ID)
}

// AddBilibiliPublicationIDs adds the "bilibili_publications" edge to the BilibiliHighlightPublication entity by IDs.
func (_u *HighlightClipUpdateOne) AddBilibiliPublicationIDs(ids ...int) *HighlightClipUpdateOne {
	_u.mutation.AddBilibiliPublicationIDs(ids...)
	return _u
}

// AddBilibiliPublications adds the "bilibili_publications" edges to the BilibiliHighlightPublication entity.
func (_u *HighlightClipUpdateOne) AddBilibiliPublications(v ...*BilibiliHighlightPublication) *HighlightClipUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBilibiliPublicationIDs(ids...)
}

// Mutation returns the HighlightClipMutation object of the builder.
func (_u *HighlightClipUpdateOne) Mutation() *HighlightClipMutation {
	return _u.mutation
}

// ClearMatchRound clears the "match_round" edge to the MatchRound entity.
func (_u *HighlightClipUpdateOne) ClearMatchRound() *HighlightClipUpdateOne {
	_u.mutation.ClearMatchRound()
	return _u
}

// ClearBilibiliPublications clears all "bilibili_publications" edges to the BilibiliHighlightPublication entity.
func (_u *HighlightClipUpdateOne) ClearBilibiliPublications() *HighlightClipUpdateOne {
	_u.mutation.ClearBilibiliPublications()
	return _u
}

// RemoveBilibiliPublicationIDs removes the "bilibili_publications" edge to BilibiliHighlightPublication entities by IDs.
func (_u *HighlightClipUpdateOne) RemoveBilibiliPublicationIDs(ids ...int) *HighlightClipUpdateOne {
	_u.mutation.RemoveBilibiliPublicationIDs(ids...)
	return _u
}

// RemoveBilibiliPublications removes "bilibili_publications" edges to BilibiliHighlightPublication entities.
func (_u *HighlightClipUpdateOne) RemoveBilibiliPublications(v ...*BilibiliHighlightPublication) *HighlightClipUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBilibiliPublicationIDs(ids...)
}

// Where appends a list predicates to the HighlightClipUpdate builder.
func (_u *HighlightClipUpdateOne) Where(ps ...predicate.HighlightClip) *HighlightClipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HighlightClipUpdateOne) Select(field string, fields ...string) *HighlightClipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HighlightClip entity.
func (_u *HighlightClipUpdateOne) Save(ctx context.Context) (*HighlightClip, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HighlightClipUpdateOne) SaveX(ctx context.Context) *HighlightClip {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HighlightClipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HighlightClipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HighlightClipUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := highlightclip.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HighlightClipUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := highlightclip.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HighlightClip.status": %w`, err)}
		}
	}
	if _u.mutation.MatchRoundCleared() && len(_u.mutation.MatchRoundIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HighlightClip.match_round"`)
	}
	return nil
}

func (_u *HighlightClipUpdateOne) sqlSave(ctx context.Context) (_node *HighlightClip, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(highlightclip.Table, highlightclip.Columns, sqlgraph.NewFieldSpec(highlightclip.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HighlightClip.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, highlightclip.FieldID)
		for _, f := range fields {
			if !highlightclip.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != highlightclip.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.HighlightIndex(); ok {
		_spec.SetField(highlightclip.FieldHighlightIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHighlightIndex(); ok {
		_spec.AddField(highlightclip.FieldHighlightIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(highlightclip.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlgorithmVersion(); ok {
		_spec.SetField(highlightclip.FieldAlgorithmVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(highlightclip.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(highlightclip.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(highlightclip.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartSeconds(); ok {
		_spec.SetField(highlightclip.FieldStartSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStartSeconds(); ok {
		_spec.AddField(highlightclip.FieldStartSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EndSeconds(); ok {
		_spec.SetField(highlightclip.FieldEndSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEndSeconds(); ok {
		_spec.AddField(highlightclip.FieldEndSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PeakSeconds(); ok {
		_spec.SetField(highlightclip.FieldPeakSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPeakSeconds(); ok {
		_spec.AddField(highlightclip.FieldPeakSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SourcePath(); ok {
		_spec.SetField(highlightclip.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputDir(); ok {
		_spec.SetField(highlightclip.FieldOutputDir, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(highlightclip.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(highlightclip.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(highlightclip.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(highlightclip.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(highlightclip.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, highlightclip.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(highlightclip.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(highlightclip.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(highlightclip.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ModelPayload(); ok {
		_spec.SetField(highlightclip.FieldModelPayload, field.TypeString, value)
	}
	if _u.mutation.ModelPayloadCleared() {
		_spec.ClearField(highlightclip.FieldModelPayload, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(highlightclip.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(highlightclip.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(highlightclip.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MatchRoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   highlightclip.MatchRoundTable,
			Columns: []string{highlightclip.MatchRoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchRoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   highlightclip.MatchRoundTable,
			Columns: []string{highlightclip.MatchRoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BilibiliPublicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   highlightclip.BilibiliPublicationsTable,
			Columns: []string{highlightclip.BilibiliPublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bilibilihighlightpublication.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBilibiliPublicationsIDs(); len(nodes) > 0 && !_u.mutation.BilibiliPublicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   highlightclip.BilibiliPublicationsTable,
			Columns: []string{highlightclip.BilibiliPublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bilibilihighlightpublication.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BilibiliPublicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   highlightclip.BilibiliPublicationsTable,
			Columns: []string{highlightclip.BilibiliPublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bilibilihighlightpublication.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &HighlightClip{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{highlightclip.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
