// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"scutbot.cn/web/rm-monitor/ent/highlightroundstate"
	"scutbot.cn/web/rm-monitor/ent/matchround"
)

// HighlightRoundState is the model entity for the HighlightRoundState schema.
type HighlightRoundState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// AlgorithmVersion holds the value of the "algorithm_version" field.
	AlgorithmVersion string `json:"algorithm_version,omitempty"`
	// Status holds the value of the "status" field.
	Status highlightroundstate.Status `json:"status,omitempty"`
	// CandidateCount holds the value of the "candidate_count" field.
	CandidateCount int `json:"candidate_count,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HighlightRoundStateQuery when eager-loading is set.
	Edges                        HighlightRoundStateEdges `json:"edges"`
	match_round_highlight_states *int
	selectValues                 sql.SelectValues
}

// HighlightRoundStateEdges holds the relations/edges for other nodes in the graph.
type HighlightRoundStateEdges struct {
	// MatchRound holds the value of the match_round edge.
	MatchRound *MatchRound `json:"match_round,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MatchRoundOrErr returns the MatchRound value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HighlightRoundStateEdges) MatchRoundOrErr() (*MatchRound, error) {
	if e.MatchRound != nil {
		return e.MatchRound, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: matchround.Label}
	}
	return nil, &NotLoadedError{edge: "match_round"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HighlightRoundState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case highlightroundstate.FieldID, highlightroundstate.FieldCandidateCount:
			values[i] = new(sql.NullInt64)
		case highlightroundstate.FieldRole, highlightroundstate.FieldAlgorithmVersion, highlightroundstate.FieldStatus:
			values[i] = new(sql.NullString)
		case highlightroundstate.FieldCompletedAt, highlightroundstate.FieldCreatedAt, highlightroundstate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case highlightroundstate.ForeignKeys[0]: // match_round_highlight_states
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HighlightRoundState fields.
func (_m *HighlightRoundState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case highlightroundstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case highlightroundstate.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case highlightroundstate.FieldAlgorithmVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field algorithm_version", values[i])
			} else if value.Valid {
				_m.AlgorithmVersion = value.String
			}
		case highlightroundstate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = highlightroundstate.Status(value.String)
			}
		case highlightroundstate.FieldCandidateCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field candidate_count", values[i])
			} else if value.Valid {
				_m.CandidateCount = int(value.Int64)
			}
		case highlightroundstate.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case highlightroundstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case highlightroundstate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case highlightroundstate.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field match_round_highlight_states", value)
			} else if value.Valid {
				_m.match_round_highlight_states = new(int)
				*_m.match_round_highlight_states = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HighlightRoundState.
// This includes values selected through modifiers, order, etc.
func (_m *HighlightRoundState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMatchRound queries the "match_round" edge of the HighlightRoundState entity.
func (_m *HighlightRoundState) QueryMatchRound() *MatchRoundQuery {
	return NewHighlightRoundStateClient(_m.config).QueryMatchRound(_m)
}

// Update returns a builder for updating this HighlightRoundState.
// Note that you need to call HighlightRoundState.Unwrap() before calling this method if this HighlightRoundState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HighlightRoundState) Update() *HighlightRoundStateUpdateOne {
	return NewHighlightRoundStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HighlightRoundState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HighlightRoundState) Unwrap() *HighlightRoundState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HighlightRoundState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HighlightRoundState) String() string {
	var builder strings.Builder
	builder.WriteString("HighlightRoundState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("algorithm_version=")
	builder.WriteString(_m.AlgorithmVersion)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("candidate_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CandidateCount))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// HighlightRoundStates is a parsable slice of HighlightRoundState.
type HighlightRoundStates []*HighlightRoundState
