// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"scutbot.cn/web/rm-monitor/ent/highlightroundstate"
	"scutbot.cn/web/rm-monitor/ent/matchround"
	"scutbot.cn/web/rm-monitor/ent/predicate"
)

// HighlightRoundStateUpdate is the builder for updating HighlightRoundState entities.
type HighlightRoundStateUpdate struct {
	config
	hooks    []Hook
	mutation *HighlightRoundStateMutation
}

// Where appends a list predicates to the HighlightRoundStateUpdate builder.
func (_u *HighlightRoundStateUpdate) Where(ps ...predicate.HighlightRoundState) *HighlightRoundStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRole sets the "role" field.
func (_u *HighlightRoundStateUpdate) SetRole(v string) *HighlightRoundStateUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *HighlightRoundStateUpdate) SetNillableRole(v *string) *HighlightRoundStateUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetAlgorithmVersion sets the "algorithm_version" field.
func (_u *HighlightRoundStateUpdate) SetAlgorithmVersion(v string) *HighlightRoundStateUpdate {
	_u.mutation.SetAlgorithmVersion(v)
	return _u
}

// SetNillableAlgorithmVersion sets the "algorithm_version" field if the given value is not nil.
func (_u *HighlightRoundStateUpdate) SetNillableAlgorithmVersion(v *string) *HighlightRoundStateUpdate {
	if v != nil {
		_u.SetAlgorithmVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *HighlightRoundStateUpdate) SetStatus(v highlightroundstate.Status) *HighlightRoundStateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HighlightRoundStateUpdate) SetNillableStatus(v *highlightroundstate.Status) *HighlightRoundStateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCandidateCount sets the "candidate_count" field.
func (_u *HighlightRoundStateUpdate) SetCandidateCount(v int) *HighlightRoundStateUpdate {
	_u.mutation.ResetCandidateCount()
	_u.mutation.SetCandidateCount(v)
	return _u
}

// SetNillableCandidateCount sets the "candidate_count" field if the given value is not nil.
func (_u *HighlightRoundStateUpdate) SetNillableCandidateCount(v *int) *HighlightRoundStateUpdate {
	if v != nil {
		_u.SetCandidateCount(*v)
	}
	return _u
}

// AddCandidateCount adds value to the "candidate_count" field.
func (_u *HighlightRoundStateUpdate) AddCandidateCount(v int) *HighlightRoundStateUpdate {
	_u.mutation.AddCandidateCount(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *HighlightRoundStateUpdate) SetCompletedAt(v time.Time) *HighlightRoundStateUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *HighlightRoundStateUpdate) SetNillableCompletedAt(v *time.Time) *HighlightRoundStateUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *HighlightRoundStateUpdate) ClearCompletedAt() *HighlightRoundStateUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HighlightRoundStateUpdate) SetUpdatedAt(v time.Time) *HighlightRoundStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMatchRoundID sets the "match_round" edge to the MatchRound entity by ID.
func (_u *HighlightRoundStateUpdate) SetMatchRoundID(id int) *HighlightRoundStateUpdate {
	_u.mutation.SetMatchRoundID(id)
	return _u
}

// SetMatchRound sets the "match_round" edge to the MatchRound entity.
func (_u *HighlightRoundStateUpdate) SetMatchRound(v *MatchRound) *HighlightRoundStateUpdate {
	return _u.SetMatchRoundID(v.ID)
}

// Mutation returns the HighlightRoundStateMutation object of the builder.
func (_u *HighlightRoundStateUpdate) Mutation() *HighlightRoundStateMutation {
	return _u.mutation
}

// ClearMatchRound clears the "match_round" edge to the MatchRound entity.
func (_u *HighlightRoundStateUpdate) ClearMatchRound() *HighlightRoundStateUpdate {
	_u.mutation.ClearMatchRound()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HighlightRoundStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HighlightRoundStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HighlightRoundStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HighlightRoundStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HighlightRoundStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := highlightroundstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HighlightRoundStateUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := highlightroundstate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HighlightRoundState.status": %w`, err)}
		}
	}
	if _u.mutation.MatchRoundCleared() && len(_u.mutation.MatchRoundIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HighlightRoundState.match_round"`)
	}
	return nil
}

func (_u *HighlightRoundStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(highlightroundstate.Table, highlightroundstate.Columns, sqlgraph.NewFieldSpec(highlightroundstate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(highlightroundstate.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlgorithmVersion(); ok {
		_spec.SetField(highlightroundstate.FieldAlgorithmVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(highlightroundstate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CandidateCount(); ok {
		_spec.SetField(highlightroundstate.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCandidateCount(); ok {
		_spec.AddField(highlightroundstate.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(highlightroundstate.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(highlightroundstate.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(highlightroundstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MatchRoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   highlightroundstate.MatchRoundTable,
			Columns: []string{highlightroundstate.MatchRoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchRoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   highlightroundstate.MatchRoundTable,
			Columns: []string{highlightroundstate.MatchRoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{highlightroundstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HighlightRoundStateUpdateOne is the builder for updating a single HighlightRoundState entity.
type HighlightRoundStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HighlightRoundStateMutation
}

// SetRole sets the "role" field.
func (_u *HighlightRoundStateUpdateOne) SetRole(v string) *HighlightRoundStateUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *HighlightRoundStateUpdateOne) SetNillableRole(v *string) *HighlightRoundStateUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetAlgorithmVersion sets the "algorithm_version" field.
func (_u *HighlightRoundStateUpdateOne) SetAlgorithmVersion(v string) *HighlightRoundStateUpdateOne {
	_u.mutation.SetAlgorithmVersion(v)
	return _u
}

// SetNillableAlgorithmVersion sets the "algorithm_version" field if the given value is not nil.
func (_u *HighlightRoundStateUpdateOne) SetNillableAlgorithmVersion(v *string) *HighlightRoundStateUpdateOne {
	if v != nil {
		_u.SetAlgorithmVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *HighlightRoundStateUpdateOne) SetStatus(v highlightroundstate.Status) *HighlightRoundStateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HighlightRoundStateUpdateOne) SetNillableStatus(v *highlightroundstate.Status) *HighlightRoundStateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCandidateCount sets the "candidate_count" field.
func (_u *HighlightRoundStateUpdateOne) SetCandidateCount(v int) *HighlightRoundStateUpdateOne {
	_u.mutation.ResetCandidateCount()
	_u.mutation.SetCandidateCount(v)
	return _u
}

// SetNillableCandidateCount sets the "candidate_count" field if the given value is not nil.
func (_u *HighlightRoundStateUpdateOne) SetNillableCandidateCount(v *int) *HighlightRoundStateUpdateOne {
	if v != nil {
		_u.SetCandidateCount(*v)
	}
	return _u
}

// AddCandidateCount adds value to the "candidate_count" field.
func (_u *HighlightRoundStateUpdateOne) AddCandidateCount(v int) *HighlightRoundStateUpdateOne {
	_u.mutation.AddCandidateCount(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *HighlightRoundStateUpdateOne) SetCompletedAt(v time.Time) *HighlightRoundStateUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *HighlightRoundStateUpdateOne) SetNillableCompletedAt(v *time.Time) *HighlightRoundStateUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *HighlightRoundStateUpdateOne) ClearCompletedAt() *HighlightRoundStateUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HighlightRoundStateUpdateOne) SetUpdatedAt(v time.Time) *HighlightRoundStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMatchRoundID sets the "match_round" edge to the MatchRound entity by ID.
func (_u *HighlightRoundStateUpdateOne) SetMatchRoundID(id int) *HighlightRoundStateUpdateOne {
	_u.mutation.SetMatchRoundID(id)
	return _u
}

// SetMatchRound sets the "match_round" edge to the MatchRound entity.
func (_u *HighlightRoundStateUpdateOne) SetMatchRound(v *MatchRound) *HighlightRoundStateUpdateOne {
	return _u.SetMatchRoundID(v.ID)
}

// Mutation returns the HighlightRoundStateMutation object of the builder.
func (_u *HighlightRoundStateUpdateOne) Mutation() *HighlightRoundStateMutation {
	return _u.mutation
}

// ClearMatchRound clears the "match_round" edge to the MatchRound entity.
func (_u *HighlightRoundStateUpdateOne) ClearMatchRound() *HighlightRoundStateUpdateOne {
	_u.mutation.ClearMatchRound()
	return _u
}

// Where appends a list predicates to the HighlightRoundStateUpdate builder.
func (_u *HighlightRoundStateUpdateOne) Where(ps ...predicate.HighlightRoundState) *HighlightRoundStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HighlightRoundStateUpdateOne) Select(field string, fields ...string) *HighlightRoundStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HighlightRoundState entity.
func (_u *HighlightRoundStateUpdateOne) Save(ctx context.Context) (*HighlightRoundState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HighlightRoundStateUpdateOne) SaveX(ctx context.Context) *HighlightRoundState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HighlightRoundStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HighlightRoundStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HighlightRoundStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := highlightroundstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HighlightRoundStateUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := highlightroundstate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HighlightRoundState.status": %w`, err)}
		}
	}
	if _u.mutation.MatchRoundCleared() && len(_u.mutation.MatchRoundIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HighlightRoundState.match_round"`)
	}
	return nil
}

func (_u *HighlightRoundStateUpdateOne) sqlSave(ctx context.Context) (_node *HighlightRoundState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(highlightroundstate.Table, highlightroundstate.Columns, sqlgraph.NewFieldSpec(highlightroundstate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HighlightRoundState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, highlightroundstate.FieldID)
		for _, f := range fields {
			if !highlightroundstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != highlightroundstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(highlightroundstate.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlgorithmVersion(); ok {
		_spec.SetField(highlightroundstate.FieldAlgorithmVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(highlightroundstate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CandidateCount(); ok {
		_spec.SetField(highlightroundstate.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCandidateCount(); ok {
		_spec.AddField(highlightroundstate.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(highlightroundstate.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(highlightroundstate.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(highlightroundstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MatchRoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   highlightroundstate.MatchRoundTable,
			Columns: []string{highlightroundstate.MatchRoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchRoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   highlightroundstate.MatchRoundTable,
			Columns: []string{highlightroundstate.MatchRoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &HighlightRoundState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{highlightroundstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
