// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"scutbot.cn/web/rm-monitor/ent/highlightclip"
	"scutbot.cn/web/rm-monitor/ent/match"
	"scutbot.cn/web/rm-monitor/ent/matchround"
	"scutbot.cn/web/rm-monitor/ent/ocrtask"
	"scutbot.cn/web/rm-monitor/ent/predicate"
	"scutbot.cn/web/rm-monitor/ent/recordtask"
)

// MatchRoundQuery is the builder for querying MatchRound entities.
type MatchRoundQuery struct {
	config
	ctx                *QueryContext
	order              []matchround.OrderOption
	inters             []Interceptor
	predicates         []predicate.MatchRound
	withMatch          *MatchQuery
	withRecordTasks    *RecordTaskQuery
	withHighlightClips *HighlightClipQuery
	withOcrTasks       *OCRTaskQuery
	withFKs            bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MatchRoundQuery builder.
func (_q *MatchRoundQuery) Where(ps ...predicate.MatchRound) *MatchRoundQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MatchRoundQuery) Limit(limit int) *MatchRoundQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MatchRoundQuery) Offset(offset int) *MatchRoundQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MatchRoundQuery) Unique(unique bool) *MatchRoundQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MatchRoundQuery) Order(o ...matchround.OrderOption) *MatchRoundQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMatch chains the current query on the "match" edge.
func (_q *MatchRoundQuery) QueryMatch() *MatchQuery {
	query := (&MatchClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(matchround.Table, matchround.FieldID, selector),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, matchround.MatchTable, matchround.MatchColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRecordTasks chains the current query on the "record_tasks" edge.
func (_q *MatchRoundQuery) QueryRecordTasks() *RecordTaskQuery {
	query := (&RecordTaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(matchround.Table, matchround.FieldID, selector),
			sqlgraph.To(recordtask.Table, recordtask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, matchround.RecordTasksTable, matchround.RecordTasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryHighlightClips chains the current query on the "highlight_clips" edge.
func (_q *MatchRoundQuery) QueryHighlightClips() *HighlightClipQuery {
	query := (&HighlightClipClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(matchround.Table, matchround.FieldID, selector),
			sqlgraph.To(highlightclip.Table, highlightclip.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, matchround.HighlightClipsTable, matchround.HighlightClipsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOcrTasks chains the current query on the "ocr_tasks" edge.
func (_q *MatchRoundQuery) QueryOcrTasks() *OCRTaskQuery {
	query := (&OCRTaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(matchround.Table, matchround.FieldID, selector),
			sqlgraph.To(ocrtask.Table, ocrtask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, matchround.OcrTasksTable, matchround.OcrTasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MatchRound entity from the query.
// Returns a *NotFoundError when no MatchRound was found.
func (_q *MatchRoundQuery) First(ctx context.Context) (*MatchRound, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{matchround.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MatchRoundQuery) FirstX(ctx context.Context) *MatchRound {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MatchRound ID from the query.
// Returns a *NotFoundError when no MatchRound ID was found.
func (_q *MatchRoundQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{matchround.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MatchRoundQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MatchRound entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MatchRound entity is found.
// Returns a *NotFoundError when no MatchRound entities are found.
func (_q *MatchRoundQuery) Only(ctx context.Context) (*MatchRound, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{matchround.Label}
	default:
		return nil, &NotSingularError{matchround.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MatchRoundQuery) OnlyX(ctx context.Context) *MatchRound {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MatchRound ID in the query.
// Returns a *NotSingularError when more than one MatchRound ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MatchRoundQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{matchround.Label}
	default:
		err = &NotSingularError{matchround.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MatchRoundQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MatchRounds.
func (_q *MatchRoundQuery) All(ctx context.Context) ([]*MatchRound, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MatchRound, *MatchRoundQuery]()
	return withInterceptors[[]*MatchRound](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MatchRoundQuery) AllX(ctx context.Context) []*MatchRound {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MatchRound IDs.
func (_q *MatchRoundQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(matchround.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MatchRoundQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MatchRoundQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MatchRoundQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MatchRoundQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MatchRoundQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MatchRoundQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MatchRoundQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MatchRoundQuery) Clone() *MatchRoundQuery {
	if _q == nil {
		return nil
	}
	return &MatchRoundQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]matchround.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.MatchRound{}, _q.predicates...),
		withMatch:          _q.withMatch.Clone(),
		withRecordTasks:    _q.withRecordTasks.Clone(),
		withHighlightClips: _q.withHighlightClips.Clone(),
		withOcrTasks:       _q.withOcrTasks.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMatch tells the query-builder to eager-load the nodes that are connected to
// the "match" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MatchRoundQuery) WithMatch(opts ...func(*MatchQuery)) *MatchRoundQuery {
	query := (&MatchClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMatch = query
	return _q
}

// WithRecordTasks tells the query-builder to eager-load the nodes that are connected to
// the "record_tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MatchRoundQuery) WithRecordTasks(opts ...func(*RecordTaskQuery)) *MatchRoundQuery {
	query := (&RecordTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRecordTasks = query
	return _q
}

// WithHighlightClips tells the query-builder to eager-load the nodes that are connected to
// the "highlight_clips" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MatchRoundQuery) WithHighlightClips(opts ...func(*HighlightClipQuery)) *MatchRoundQuery {
	query := (&HighlightClipClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHighlightClips = query
	return _q
}

// WithOcrTasks tells the query-builder to eager-load the nodes that are connected to
// the "ocr_tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MatchRoundQuery) WithOcrTasks(opts ...func(*OCRTaskQuery)) *MatchRoundQuery {
	query := (&OCRTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOcrTasks = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoundNo int `json:"round_no,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MatchRound.Query().
//		GroupBy(matchround.FieldRoundNo).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MatchRoundQuery) GroupBy(field string, fields ...string) *MatchRoundGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MatchRoundGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = matchround.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoundNo int `json:"round_no,omitempty"`
//	}
//
//	client.MatchRound.Query().
//		Select(matchround.FieldRoundNo).
//		Scan(ctx, &v)
func (_q *MatchRoundQuery) Select(fields ...string) *MatchRoundSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MatchRoundSelect{MatchRoundQuery: _q}
	sbuild.label = matchround.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MatchRoundSelect configured with the given aggregations.
func (_q *MatchRoundQuery) Aggregate(fns ...AggregateFunc) *MatchRoundSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MatchRoundQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !matchround.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MatchRoundQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MatchRound, error) {
	var (
		nodes       = []*MatchRound{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withMatch != nil,
			_q.withRecordTasks != nil,
			_q.withHighlightClips != nil,
			_q.withOcrTasks != nil,
		}
	)
	if _q.withMatch != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, matchround.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MatchRound).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MatchRound{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMatch; query != nil {
		if err := _q.loadMatch(ctx, query, nodes, nil,
			func(n *MatchRound, e *Match) { n.Edges.Match = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRecordTasks; query != nil {
		if err := _q.loadRecordTasks(ctx, query, nodes,
			func(n *MatchRound) { n.Edges.RecordTasks = []*RecordTask{} },
			func(n *MatchRound, e *RecordTask) { n.Edges.RecordTasks = append(n.Edges.RecordTasks, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withHighlightClips; query != nil {
		if err := _q.loadHighlightClips(ctx, query, nodes,
			func(n *MatchRound) { n.Edges.HighlightClips = []*HighlightClip{} },
			func(n *MatchRound, e *HighlightClip) { n.Edges.HighlightClips = append(n.Edges.HighlightClips, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOcrTasks; query != nil {
		if err := _q.loadOcrTasks(ctx, query, nodes,
			func(n *MatchRound) { n.Edges.OcrTasks = []*OCRTask{} },
			func(n *MatchRound, e *OCRTask) { n.Edges.OcrTasks = append(n.Edges.OcrTasks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MatchRoundQuery) loadMatch(ctx context.Context, query *MatchQuery, nodes []*MatchRound, init func(*MatchRound), assign func(*MatchRound, *Match)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*MatchRound)
	for i := range nodes {
		if nodes[i].match_rounds == nil {
			continue
		}
		fk := *nodes[i].match_rounds
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(match.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "match_rounds" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MatchRoundQuery) loadRecordTasks(ctx context.Context, query *RecordTaskQuery, nodes []*MatchRound, init func(*MatchRound), assign func(*MatchRound, *RecordTask)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*MatchRound)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.RecordTask(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(matchround.RecordTasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.match_round_record_tasks
		if fk == nil {
			return fmt.Errorf(`foreign-key "match_round_record_tasks" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "match_round_record_tasks" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MatchRoundQuery) loadHighlightClips(ctx context.Context, query *HighlightClipQuery, nodes []*MatchRound, init func(*MatchRound), assign func(*MatchRound, *HighlightClip)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*MatchRound)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.HighlightClip(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(matchround.HighlightClipsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.match_round_highlight_clips
		if fk == nil {
			return fmt.Errorf(`foreign-key "match_round_highlight_clips" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "match_round_highlight_clips" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MatchRoundQuery) loadOcrTasks(ctx context.Context, query *OCRTaskQuery, nodes []*MatchRound, init func(*MatchRound), assign func(*MatchRound, *OCRTask)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*MatchRound)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.OCRTask(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(matchround.OcrTasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.match_round_ocr_tasks
		if fk == nil {
			return fmt.Errorf(`foreign-key "match_round_ocr_tasks" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "match_round_ocr_tasks" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *MatchRoundQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MatchRoundQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(matchround.Table, matchround.Columns, sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, matchround.FieldID)
		for i := range fields {
			if fields[i] != matchround.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MatchRoundQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(matchround.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = matchround.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MatchRoundGroupBy is the group-by builder for MatchRound entities.
type MatchRoundGroupBy struct {
	selector
	build *MatchRoundQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MatchRoundGroupBy) Aggregate(fns ...AggregateFunc) *MatchRoundGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MatchRoundGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MatchRoundQuery, *MatchRoundGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MatchRoundGroupBy) sqlScan(ctx context.Context, root *MatchRoundQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MatchRoundSelect is the builder for selecting fields of MatchRound entities.
type MatchRoundSelect struct {
	*MatchRoundQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MatchRoundSelect) Aggregate(fns ...AggregateFunc) *MatchRoundSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MatchRoundSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MatchRoundQuery, *MatchRoundSelect](ctx, _s.MatchRoundQuery, _s, _s.inters, v)
}

func (_s *MatchRoundSelect) sqlScan(ctx context.Context, root *MatchRoundQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
