// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"scutbot.cn/web/rm-monitor/ent/highlightclip"
	"scutbot.cn/web/rm-monitor/ent/match"
	"scutbot.cn/web/rm-monitor/ent/matchround"
	"scutbot.cn/web/rm-monitor/ent/predicate"
	"scutbot.cn/web/rm-monitor/ent/recordtask"
)

// MatchRoundUpdate is the builder for updating MatchRound entities.
type MatchRoundUpdate struct {
	config
	hooks    []Hook
	mutation *MatchRoundMutation
}

// Where appends a list predicates to the MatchRoundUpdate builder.
func (_u *MatchRoundUpdate) Where(ps ...predicate.MatchRound) *MatchRoundUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoundNo sets the "round_no" field.
func (_u *MatchRoundUpdate) SetRoundNo(v int) *MatchRoundUpdate {
	_u.mutation.ResetRoundNo()
	_u.mutation.SetRoundNo(v)
	return _u
}

// SetNillableRoundNo sets the "round_no" field if the given value is not nil.
func (_u *MatchRoundUpdate) SetNillableRoundNo(v *int) *MatchRoundUpdate {
	if v != nil {
		_u.SetRoundNo(*v)
	}
	return _u
}

// AddRoundNo adds value to the "round_no" field.
func (_u *MatchRoundUpdate) AddRoundNo(v int) *MatchRoundUpdate {
	_u.mutation.AddRoundNo(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MatchRoundUpdate) SetStatus(v matchround.Status) *MatchRoundUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MatchRoundUpdate) SetNillableStatus(v *matchround.Status) *MatchRoundUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWinner sets the "winner" field.
func (_u *MatchRoundUpdate) SetWinner(v matchround.Winner) *MatchRoundUpdate {
	_u.mutation.SetWinner(v)
	return _u
}

// SetNillableWinner sets the "winner" field if the given value is not nil.
func (_u *MatchRoundUpdate) SetNillableWinner(v *matchround.Winner) *MatchRoundUpdate {
	if v != nil {
		_u.SetWinner(*v)
	}
	return _u
}

// ClearWinner clears the value of the "winner" field.
func (_u *MatchRoundUpdate) ClearWinner() *MatchRoundUpdate {
	_u.mutation.ClearWinner()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *MatchRoundUpdate) SetStartedAt(v time.Time) *MatchRoundUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *MatchRoundUpdate) SetNillableStartedAt(v *time.Time) *MatchRoundUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *MatchRoundUpdate) SetEndedAt(v time.Time) *MatchRoundUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *MatchRoundUpdate) SetNillableEndedAt(v *time.Time) *MatchRoundUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *MatchRoundUpdate) ClearEndedAt() *MatchRoundUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MatchRoundUpdate) SetUpdatedAt(v time.Time) *MatchRoundUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMatchID sets the "match" edge to the Match entity by ID.
func (_u *MatchRoundUpdate) SetMatchID(id string) *MatchRoundUpdate {
	_u.mutation.SetMatchID(id)
	return _u
}

// SetMatch sets the "match" edge to the Match entity.
func (_u *MatchRoundUpdate) SetMatch(v *Match) *MatchRoundUpdate {
	return _u.SetMatchID(v.ID)
}

// AddRecordTaskIDs adds the "record_tasks" edge to the RecordTask entity by IDs.
func (_u *MatchRoundUpdate) AddRecordTaskIDs(ids ...int) *MatchRoundUpdate {
	_u.mutation.AddRecordTaskIDs(ids...)
	return _u
}

// AddRecordTasks adds the "record_tasks" edges to the RecordTask entity.
func (_u *MatchRoundUpdate) AddRecordTasks(v ...*RecordTask) *MatchRoundUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordTaskIDs(ids...)
}

// AddHighlightClipIDs adds the "highlight_clips" edge to the HighlightClip entity by IDs.
func (_u *MatchRoundUpdate) AddHighlightClipIDs(ids ...int) *MatchRoundUpdate {
	_u.mutation.AddHighlightClipIDs(ids...)
	return _u
}

// AddHighlightClips adds the "highlight_clips" edges to the HighlightClip entity.
func (_u *MatchRoundUpdate) AddHighlightClips(v ...*HighlightClip) *MatchRoundUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHighlightClipIDs(ids...)
}

// Mutation returns the MatchRoundMutation object of the builder.
func (_u *MatchRoundUpdate) Mutation() *MatchRoundMutation {
	return _u.mutation
}

// ClearMatch clears the "match" edge to the Match entity.
func (_u *MatchRoundUpdate) ClearMatch() *MatchRoundUpdate {
	_u.mutation.ClearMatch()
	return _u
}

// ClearRecordTasks clears all "record_tasks" edges to the RecordTask entity.
func (_u *MatchRoundUpdate) ClearRecordTasks() *MatchRoundUpdate {
	_u.mutation.ClearRecordTasks()
	return _u
}

// RemoveRecordTaskIDs removes the "record_tasks" edge to RecordTask entities by IDs.
func (_u *MatchRoundUpdate) RemoveRecordTaskIDs(ids ...int) *MatchRoundUpdate {
	_u.mutation.RemoveRecordTaskIDs(ids...)
	return _u
}

// RemoveRecordTasks removes "record_tasks" edges to RecordTask entities.
func (_u *MatchRoundUpdate) RemoveRecordTasks(v ...*RecordTask) *MatchRoundUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordTaskIDs(ids...)
}

// ClearHighlightClips clears all "highlight_clips" edges to the HighlightClip entity.
func (_u *MatchRoundUpdate) ClearHighlightClips() *MatchRoundUpdate {
	_u.mutation.ClearHighlightClips()
	return _u
}

// RemoveHighlightClipIDs removes the "highlight_clips" edge to HighlightClip entities by IDs.
func (_u *MatchRoundUpdate) RemoveHighlightClipIDs(ids ...int) *MatchRoundUpdate {
	_u.mutation.RemoveHighlightClipIDs(ids...)
	return _u
}

// RemoveHighlightClips removes "highlight_clips" edges to HighlightClip entities.
func (_u *MatchRoundUpdate) RemoveHighlightClips(v ...*HighlightClip) *MatchRoundUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHighlightClipIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MatchRoundUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MatchRoundUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MatchRoundUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MatchRoundUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MatchRoundUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := matchround.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MatchRoundUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := matchround.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MatchRound.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Winner(); ok {
		if err := matchround.WinnerValidator(v); err != nil {
			return &ValidationError{Name: "winner", err: fmt.Errorf(`ent: validator failed for field "MatchRound.winner": %w`, err)}
		}
	}
	if _u.mutation.MatchCleared() && len(_u.mutation.MatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MatchRound.match"`)
	}
	return nil
}

func (_u *MatchRoundUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(matchround.Table, matchround.Columns, sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoundNo(); ok {
		_spec.SetField(matchround.FieldRoundNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoundNo(); ok {
		_spec.AddField(matchround.FieldRoundNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(matchround.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Winner(); ok {
		_spec.SetField(matchround.FieldWinner, field.TypeEnum, value)
	}
	if _u.mutation.WinnerCleared() {
		_spec.ClearField(matchround.FieldWinner, field.TypeEnum)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(matchround.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(matchround.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(matchround.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(matchround.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   matchround.MatchTable,
			Columns: []string{matchround.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   matchround.MatchTable,
			Columns: []string{matchround.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecordTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.RecordTasksTable,
			Columns: []string{matchround.RecordTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordtask.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordTasksIDs(); len(nodes) > 0 && !_u.mutation.RecordTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.RecordTasksTable,
			Columns: []string{matchround.RecordTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.RecordTasksTable,
			Columns: []string{matchround.RecordTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HighlightClipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.HighlightClipsTable,
			Columns: []string{matchround.HighlightClipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlightclip.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHighlightClipsIDs(); len(nodes) > 0 && !_u.mutation.HighlightClipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.HighlightClipsTable,
			Columns: []string{matchround.HighlightClipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlightclip.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HighlightClipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.HighlightClipsTable,
			Columns: []string{matchround.HighlightClipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlightclip.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{matchround.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MatchRoundUpdateOne is the builder for updating a single MatchRound entity.
type MatchRoundUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MatchRoundMutation
}

// SetRoundNo sets the "round_no" field.
func (_u *MatchRoundUpdateOne) SetRoundNo(v int) *MatchRoundUpdateOne {
	_u.mutation.ResetRoundNo()
	_u.mutation.SetRoundNo(v)
	return _u
}

// SetNillableRoundNo sets the "round_no" field if the given value is not nil.
func (_u *MatchRoundUpdateOne) SetNillableRoundNo(v *int) *MatchRoundUpdateOne {
	if v != nil {
		_u.SetRoundNo(*v)
	}
	return _u
}

// AddRoundNo adds value to the "round_no" field.
func (_u *MatchRoundUpdateOne) AddRoundNo(v int) *MatchRoundUpdateOne {
	_u.mutation.AddRoundNo(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MatchRoundUpdateOne) SetStatus(v matchround.Status) *MatchRoundUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MatchRoundUpdateOne) SetNillableStatus(v *matchround.Status) *MatchRoundUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWinner sets the "winner" field.
func (_u *MatchRoundUpdateOne) SetWinner(v matchround.Winner) *MatchRoundUpdateOne {
	_u.mutation.SetWinner(v)
	return _u
}

// SetNillableWinner sets the "winner" field if the given value is not nil.
func (_u *MatchRoundUpdateOne) SetNillableWinner(v *matchround.Winner) *MatchRoundUpdateOne {
	if v != nil {
		_u.SetWinner(*v)
	}
	return _u
}

// ClearWinner clears the value of the "winner" field.
func (_u *MatchRoundUpdateOne) ClearWinner() *MatchRoundUpdateOne {
	_u.mutation.ClearWinner()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *MatchRoundUpdateOne) SetStartedAt(v time.Time) *MatchRoundUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *MatchRoundUpdateOne) SetNillableStartedAt(v *time.Time) *MatchRoundUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *MatchRoundUpdateOne) SetEndedAt(v time.Time) *MatchRoundUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *MatchRoundUpdateOne) SetNillableEndedAt(v *time.Time) *MatchRoundUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *MatchRoundUpdateOne) ClearEndedAt() *MatchRoundUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MatchRoundUpdateOne) SetUpdatedAt(v time.Time) *MatchRoundUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMatchID sets the "match" edge to the Match entity by ID.
func (_u *MatchRoundUpdateOne) SetMatchID(id string) *MatchRoundUpdateOne {
	_u.mutation.SetMatchID(id)
	return _u
}

// SetMatch sets the "match" edge to the Match entity.
func (_u *MatchRoundUpdateOne) SetMatch(v *Match) *MatchRoundUpdateOne {
	return _u.SetMatchID(v.ID)
}

// AddRecordTaskIDs adds the "record_tasks" edge to the RecordTask entity by IDs.
func (_u *MatchRoundUpdateOne) AddRecordTaskIDs(ids ...int) *MatchRoundUpdateOne {
	_u.mutation.AddRecordTaskIDs(ids...)
	return _u
}

// AddRecordTasks adds the "record_tasks" edges to the RecordTask entity.
func (_u *MatchRoundUpdateOne) AddRecordTasks(v ...*RecordTask) *MatchRoundUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordTaskIDs(ids...)
}

// AddHighlightClipIDs adds the "highlight_clips" edge to the HighlightClip entity by IDs.
func (_u *MatchRoundUpdateOne) AddHighlightClipIDs(ids ...int) *MatchRoundUpdateOne {
	_u.mutation.AddHighlightClipIDs(ids...)
	return _u
}

// AddHighlightClips adds the "highlight_clips" edges to the HighlightClip entity.
func (_u *MatchRoundUpdateOne) AddHighlightClips(v ...*HighlightClip) *MatchRoundUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHighlightClipIDs(ids...)
}

// Mutation returns the MatchRoundMutation object of the builder.
func (_u *MatchRoundUpdateOne) Mutation() *MatchRoundMutation {
	return _u.mutation
}

// ClearMatch clears the "match" edge to the Match entity.
func (_u *MatchRoundUpdateOne) ClearMatch() *MatchRoundUpdateOne {
	_u.mutation.ClearMatch()
	return _u
}

// ClearRecordTasks clears all "record_tasks" edges to the RecordTask entity.
func (_u *MatchRoundUpdateOne) ClearRecordTasks() *MatchRoundUpdateOne {
	_u.mutation.ClearRecordTasks()
	return _u
}

// RemoveRecordTaskIDs removes the "record_tasks" edge to RecordTask entities by IDs.
func (_u *MatchRoundUpdateOne) RemoveRecordTaskIDs(ids ...int) *MatchRoundUpdateOne {
	_u.mutation.RemoveRecordTaskIDs(ids...)
	return _u
}

// RemoveRecordTasks removes "record_tasks" edges to RecordTask entities.
func (_u *MatchRoundUpdateOne) RemoveRecordTasks(v ...*RecordTask) *MatchRoundUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordTaskIDs(ids...)
}

// ClearHighlightClips clears all "highlight_clips" edges to the HighlightClip entity.
func (_u *MatchRoundUpdateOne) ClearHighlightClips() *MatchRoundUpdateOne {
	_u.mutation.ClearHighlightClips()
	return _u
}

// RemoveHighlightClipIDs removes the "highlight_clips" edge to HighlightClip entities by IDs.
func (_u *MatchRoundUpdateOne) RemoveHighlightClipIDs(ids ...int) *MatchRoundUpdateOne {
	_u.mutation.RemoveHighlightClipIDs(ids...)
	return _u
}

// RemoveHighlightClips removes "highlight_clips" edges to HighlightClip entities.
func (_u *MatchRoundUpdateOne) RemoveHighlightClips(v ...*HighlightClip) *MatchRoundUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHighlightClipIDs(ids...)
}

// Where appends a list predicates to the MatchRoundUpdate builder.
func (_u *MatchRoundUpdateOne) Where(ps ...predicate.MatchRound) *MatchRoundUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MatchRoundUpdateOne) Select(field string, fields ...string) *MatchRoundUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MatchRound entity.
func (_u *MatchRoundUpdateOne) Save(ctx context.Context) (*MatchRound, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MatchRoundUpdateOne) SaveX(ctx context.Context) *MatchRound {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MatchRoundUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MatchRoundUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MatchRoundUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := matchround.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MatchRoundUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := matchround.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MatchRound.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Winner(); ok {
		if err := matchround.WinnerValidator(v); err != nil {
			return &ValidationError{Name: "winner", err: fmt.Errorf(`ent: validator failed for field "MatchRound.winner": %w`, err)}
		}
	}
	if _u.mutation.MatchCleared() && len(_u.mutation.MatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MatchRound.match"`)
	}
	return nil
}

func (_u *MatchRoundUpdateOne) sqlSave(ctx context.Context) (_node *MatchRound, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(matchround.Table, matchround.Columns, sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MatchRound.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, matchround.FieldID)
		for _, f := range fields {
			if !matchround.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != matchround.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoundNo(); ok {
		_spec.SetField(matchround.FieldRoundNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoundNo(); ok {
		_spec.AddField(matchround.FieldRoundNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(matchround.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Winner(); ok {
		_spec.SetField(matchround.FieldWinner, field.TypeEnum, value)
	}
	if _u.mutation.WinnerCleared() {
		_spec.ClearField(matchround.FieldWinner, field.TypeEnum)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(matchround.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(matchround.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(matchround.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(matchround.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   matchround.MatchTable,
			Columns: []string{matchround.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   matchround.MatchTable,
			Columns: []string{matchround.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecordTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.RecordTasksTable,
			Columns: []string{matchround.RecordTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordtask.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordTasksIDs(); len(nodes) > 0 && !_u.mutation.RecordTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.RecordTasksTable,
			Columns: []string{matchround.RecordTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.RecordTasksTable,
			Columns: []string{matchround.RecordTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HighlightClipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.HighlightClipsTable,
			Columns: []string{matchround.HighlightClipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlightclip.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHighlightClipsIDs(); len(nodes) > 0 && !_u.mutation.HighlightClipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.HighlightClipsTable,
			Columns: []string{matchround.HighlightClipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlightclip.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HighlightClipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.HighlightClipsTable,
			Columns: []string{matchround.HighlightClipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(highlightclip.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MatchRound{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{matchround.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
