// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"scutbot.cn/web/rm-monitor/ent/match"
	"scutbot.cn/web/rm-monitor/ent/matchround"
	"scutbot.cn/web/rm-monitor/ent/recordtask"
)

// MatchRoundCreate is the builder for creating a MatchRound entity.
type MatchRoundCreate struct {
	config
	mutation *MatchRoundMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRoundNo sets the "round_no" field.
func (_c *MatchRoundCreate) SetRoundNo(v int) *MatchRoundCreate {
	_c.mutation.SetRoundNo(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MatchRoundCreate) SetStatus(v matchround.Status) *MatchRoundCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetWinner sets the "winner" field.
func (_c *MatchRoundCreate) SetWinner(v matchround.Winner) *MatchRoundCreate {
	_c.mutation.SetWinner(v)
	return _c
}

// SetNillableWinner sets the "winner" field if the given value is not nil.
func (_c *MatchRoundCreate) SetNillableWinner(v *matchround.Winner) *MatchRoundCreate {
	if v != nil {
		_c.SetWinner(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *MatchRoundCreate) SetStartedAt(v time.Time) *MatchRoundCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *MatchRoundCreate) SetNillableStartedAt(v *time.Time) *MatchRoundCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *MatchRoundCreate) SetEndedAt(v time.Time) *MatchRoundCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *MatchRoundCreate) SetNillableEndedAt(v *time.Time) *MatchRoundCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MatchRoundCreate) SetCreatedAt(v time.Time) *MatchRoundCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MatchRoundCreate) SetNillableCreatedAt(v *time.Time) *MatchRoundCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MatchRoundCreate) SetUpdatedAt(v time.Time) *MatchRoundCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MatchRoundCreate) SetNillableUpdatedAt(v *time.Time) *MatchRoundCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMatchID sets the "match" edge to the Match entity by ID.
func (_c *MatchRoundCreate) SetMatchID(id string) *MatchRoundCreate {
	_c.mutation.SetMatchID(id)
	return _c
}

// SetMatch sets the "match" edge to the Match entity.
func (_c *MatchRoundCreate) SetMatch(v *Match) *MatchRoundCreate {
	return _c.SetMatchID(v.ID)
}

// AddRecordTaskIDs adds the "record_tasks" edge to the RecordTask entity by IDs.
func (_c *MatchRoundCreate) AddRecordTaskIDs(ids ...int) *MatchRoundCreate {
	_c.mutation.AddRecordTaskIDs(ids...)
	return _c
}

// AddRecordTasks adds the "record_tasks" edges to the RecordTask entity.
func (_c *MatchRoundCreate) AddRecordTasks(v ...*RecordTask) *MatchRoundCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecordTaskIDs(ids...)
}

// Mutation returns the MatchRoundMutation object of the builder.
func (_c *MatchRoundCreate) Mutation() *MatchRoundMutation {
	return _c.mutation
}

// Save creates the MatchRound in the database.
func (_c *MatchRoundCreate) Save(ctx context.Context) (*MatchRound, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MatchRoundCreate) SaveX(ctx context.Context) *MatchRound {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MatchRoundCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MatchRoundCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MatchRoundCreate) defaults() {
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := matchround.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := matchround.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := matchround.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MatchRoundCreate) check() error {
	if _, ok := _c.mutation.RoundNo(); !ok {
		return &ValidationError{Name: "round_no", err: errors.New(`ent: missing required field "MatchRound.round_no"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MatchRound.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := matchround.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MatchRound.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Winner(); ok {
		if err := matchround.WinnerValidator(v); err != nil {
			return &ValidationError{Name: "winner", err: fmt.Errorf(`ent: validator failed for field "MatchRound.winner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "MatchRound.started_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MatchRound.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MatchRound.updated_at"`)}
	}
	if len(_c.mutation.MatchIDs()) == 0 {
		return &ValidationError{Name: "match", err: errors.New(`ent: missing required edge "MatchRound.match"`)}
	}
	return nil
}

func (_c *MatchRoundCreate) sqlSave(ctx context.Context) (*MatchRound, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MatchRoundCreate) createSpec() (*MatchRound, *sqlgraph.CreateSpec) {
	var (
		_node = &MatchRound{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(matchround.Table, sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RoundNo(); ok {
		_spec.SetField(matchround.FieldRoundNo, field.TypeInt, value)
		_node.RoundNo = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(matchround.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Winner(); ok {
		_spec.SetField(matchround.FieldWinner, field.TypeEnum, value)
		_node.Winner = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(matchround.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(matchround.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(matchround.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(matchround.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   matchround.MatchTable,
			Columns: []string{matchround.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.match_rounds = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecordTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   matchround.RecordTasksTable,
			Columns: []string{matchround.RecordTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MatchRound.Create().
//		SetRoundNo(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MatchRoundUpsert) {
//			SetRoundNo(v+v).
//		}).
//		Exec(ctx)
func (_c *MatchRoundCreate) OnConflict(opts ...sql.ConflictOption) *MatchRoundUpsertOne {
	_c.conflict = opts
	return &MatchRoundUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MatchRound.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MatchRoundCreate) OnConflictColumns(columns ...string) *MatchRoundUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MatchRoundUpsertOne{
		create: _c,
	}
}

type (
	// MatchRoundUpsertOne is the builder for "upsert"-ing
	//  one MatchRound node.
	MatchRoundUpsertOne struct {
		create *MatchRoundCreate
	}

	// MatchRoundUpsert is the "OnConflict" setter.
	MatchRoundUpsert struct {
		*sql.UpdateSet
	}
)

// SetRoundNo sets the "round_no" field.
func (u *MatchRoundUpsert) SetRoundNo(v int) *MatchRoundUpsert {
	u.Set(matchround.FieldRoundNo, v)
	return u
}

// UpdateRoundNo sets the "round_no" field to the value that was provided on create.
func (u *MatchRoundUpsert) UpdateRoundNo() *MatchRoundUpsert {
	u.SetExcluded(matchround.FieldRoundNo)
	return u
}

// AddRoundNo adds v to the "round_no" field.
func (u *MatchRoundUpsert) AddRoundNo(v int) *MatchRoundUpsert {
	u.Add(matchround.FieldRoundNo, v)
	return u
}

// SetStatus sets the "status" field.
func (u *MatchRoundUpsert) SetStatus(v matchround.Status) *MatchRoundUpsert {
	u.Set(matchround.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MatchRoundUpsert) UpdateStatus() *MatchRoundUpsert {
	u.SetExcluded(matchround.FieldStatus)
	return u
}

// SetWinner sets the "winner" field.
func (u *MatchRoundUpsert) SetWinner(v matchround.Winner) *MatchRoundUpsert {
	u.Set(matchround.FieldWinner, v)
	return u
}

// UpdateWinner sets the "winner" field to the value that was provided on create.
func (u *MatchRoundUpsert) UpdateWinner() *MatchRoundUpsert {
	u.SetExcluded(matchround.FieldWinner)
	return u
}

// ClearWinner clears the value of the "winner" field.
func (u *MatchRoundUpsert) ClearWinner() *MatchRoundUpsert {
	u.SetNull(matchround.FieldWinner)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *MatchRoundUpsert) SetStartedAt(v time.Time) *MatchRoundUpsert {
	u.Set(matchround.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *MatchRoundUpsert) UpdateStartedAt() *MatchRoundUpsert {
	u.SetExcluded(matchround.FieldStartedAt)
	return u
}

// SetEndedAt sets the "ended_at" field.
func (u *MatchRoundUpsert) SetEndedAt(v time.Time) *MatchRoundUpsert {
	u.Set(matchround.FieldEndedAt, v)
	return u
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *MatchRoundUpsert) UpdateEndedAt() *MatchRoundUpsert {
	u.SetExcluded(matchround.FieldEndedAt)
	return u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *MatchRoundUpsert) ClearEndedAt() *MatchRoundUpsert {
	u.SetNull(matchround.FieldEndedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MatchRoundUpsert) SetUpdatedAt(v time.Time) *MatchRoundUpsert {
	u.Set(matchround.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MatchRoundUpsert) UpdateUpdatedAt() *MatchRoundUpsert {
	u.SetExcluded(matchround.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MatchRound.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MatchRoundUpsertOne) UpdateNewValues() *MatchRoundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(matchround.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MatchRound.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MatchRoundUpsertOne) Ignore() *MatchRoundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MatchRoundUpsertOne) DoNothing() *MatchRoundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MatchRoundCreate.OnConflict
// documentation for more info.
func (u *MatchRoundUpsertOne) Update(set func(*MatchRoundUpsert)) *MatchRoundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MatchRoundUpsert{UpdateSet: update})
	}))
	return u
}

// SetRoundNo sets the "round_no" field.
func (u *MatchRoundUpsertOne) SetRoundNo(v int) *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetRoundNo(v)
	})
}

// AddRoundNo adds v to the "round_no" field.
func (u *MatchRoundUpsertOne) AddRoundNo(v int) *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.AddRoundNo(v)
	})
}

// UpdateRoundNo sets the "round_no" field to the value that was provided on create.
func (u *MatchRoundUpsertOne) UpdateRoundNo() *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateRoundNo()
	})
}

// SetStatus sets the "status" field.
func (u *MatchRoundUpsertOne) SetStatus(v matchround.Status) *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MatchRoundUpsertOne) UpdateStatus() *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateStatus()
	})
}

// SetWinner sets the "winner" field.
func (u *MatchRoundUpsertOne) SetWinner(v matchround.Winner) *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetWinner(v)
	})
}

// UpdateWinner sets the "winner" field to the value that was provided on create.
func (u *MatchRoundUpsertOne) UpdateWinner() *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateWinner()
	})
}

// ClearWinner clears the value of the "winner" field.
func (u *MatchRoundUpsertOne) ClearWinner() *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.ClearWinner()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *MatchRoundUpsertOne) SetStartedAt(v time.Time) *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *MatchRoundUpsertOne) UpdateStartedAt() *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *MatchRoundUpsertOne) SetEndedAt(v time.Time) *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *MatchRoundUpsertOne) UpdateEndedAt() *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *MatchRoundUpsertOne) ClearEndedAt() *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.ClearEndedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MatchRoundUpsertOne) SetUpdatedAt(v time.Time) *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MatchRoundUpsertOne) UpdateUpdatedAt() *MatchRoundUpsertOne {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MatchRoundUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MatchRoundCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MatchRoundUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MatchRoundUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MatchRoundUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MatchRoundCreateBulk is the builder for creating many MatchRound entities in bulk.
type MatchRoundCreateBulk struct {
	config
	err      error
	builders []*MatchRoundCreate
	conflict []sql.ConflictOption
}

// Save creates the MatchRound entities in the database.
func (_c *MatchRoundCreateBulk) Save(ctx context.Context) ([]*MatchRound, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MatchRound, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MatchRoundMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MatchRoundCreateBulk) SaveX(ctx context.Context) []*MatchRound {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MatchRoundCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MatchRoundCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MatchRound.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MatchRoundUpsert) {
//			SetRoundNo(v+v).
//		}).
//		Exec(ctx)
func (_c *MatchRoundCreateBulk) OnConflict(opts ...sql.ConflictOption) *MatchRoundUpsertBulk {
	_c.conflict = opts
	return &MatchRoundUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MatchRound.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MatchRoundCreateBulk) OnConflictColumns(columns ...string) *MatchRoundUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MatchRoundUpsertBulk{
		create: _c,
	}
}

// MatchRoundUpsertBulk is the builder for "upsert"-ing
// a bulk of MatchRound nodes.
type MatchRoundUpsertBulk struct {
	create *MatchRoundCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MatchRound.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MatchRoundUpsertBulk) UpdateNewValues() *MatchRoundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(matchround.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MatchRound.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MatchRoundUpsertBulk) Ignore() *MatchRoundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MatchRoundUpsertBulk) DoNothing() *MatchRoundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MatchRoundCreateBulk.OnConflict
// documentation for more info.
func (u *MatchRoundUpsertBulk) Update(set func(*MatchRoundUpsert)) *MatchRoundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MatchRoundUpsert{UpdateSet: update})
	}))
	return u
}

// SetRoundNo sets the "round_no" field.
func (u *MatchRoundUpsertBulk) SetRoundNo(v int) *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetRoundNo(v)
	})
}

// AddRoundNo adds v to the "round_no" field.
func (u *MatchRoundUpsertBulk) AddRoundNo(v int) *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.AddRoundNo(v)
	})
}

// UpdateRoundNo sets the "round_no" field to the value that was provided on create.
func (u *MatchRoundUpsertBulk) UpdateRoundNo() *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateRoundNo()
	})
}

// SetStatus sets the "status" field.
func (u *MatchRoundUpsertBulk) SetStatus(v matchround.Status) *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MatchRoundUpsertBulk) UpdateStatus() *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateStatus()
	})
}

// SetWinner sets the "winner" field.
func (u *MatchRoundUpsertBulk) SetWinner(v matchround.Winner) *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetWinner(v)
	})
}

// UpdateWinner sets the "winner" field to the value that was provided on create.
func (u *MatchRoundUpsertBulk) UpdateWinner() *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateWinner()
	})
}

// ClearWinner clears the value of the "winner" field.
func (u *MatchRoundUpsertBulk) ClearWinner() *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.ClearWinner()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *MatchRoundUpsertBulk) SetStartedAt(v time.Time) *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *MatchRoundUpsertBulk) UpdateStartedAt() *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *MatchRoundUpsertBulk) SetEndedAt(v time.Time) *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *MatchRoundUpsertBulk) UpdateEndedAt() *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *MatchRoundUpsertBulk) ClearEndedAt() *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.ClearEndedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MatchRoundUpsertBulk) SetUpdatedAt(v time.Time) *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MatchRoundUpsertBulk) UpdateUpdatedAt() *MatchRoundUpsertBulk {
	return u.Update(func(s *MatchRoundUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MatchRoundUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MatchRoundCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MatchRoundCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MatchRoundUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
