// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"scutbot.cn/web/rm-monitor/ent/mediaartifact"
	"scutbot.cn/web/rm-monitor/ent/recordtask"
	"scutbot.cn/web/rm-monitor/ent/transcodetask"
	"scutbot.cn/web/rm-monitor/ent/uploadtask"
)

// MediaArtifact is the model entity for the MediaArtifact schema.
type MediaArtifact struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind mediaartifact.Kind `json:"kind,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Format holds the value of the "format" field.
	Format mediaartifact.Format `json:"format,omitempty"`
	// Codec holds the value of the "codec" field.
	Codec mediaartifact.Codec `json:"codec,omitempty"`
	// FileSize holds the value of the "file_size" field.
	FileSize *int64 `json:"file_size,omitempty"`
	// Checksum holds the value of the "checksum" field.
	Checksum *string `json:"checksum,omitempty"`
	// Status holds the value of the "status" field.
	Status mediaartifact.Status `json:"status,omitempty"`
	// DeletableAt holds the value of the "deletable_at" field.
	DeletableAt *time.Time `json:"deletable_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MediaArtifactQuery when eager-loading is set.
	Edges                       MediaArtifactEdges `json:"edges"`
	record_task_media_artifacts *int
	selectValues                sql.SelectValues
}

// MediaArtifactEdges holds the relations/edges for other nodes in the graph.
type MediaArtifactEdges struct {
	// RecordTask holds the value of the record_task edge.
	RecordTask *RecordTask `json:"record_task,omitempty"`
	// UploadTask holds the value of the upload_task edge.
	UploadTask *UploadTask `json:"upload_task,omitempty"`
	// SourceTranscodeTask holds the value of the source_transcode_task edge.
	SourceTranscodeTask *TranscodeTask `json:"source_transcode_task,omitempty"`
	// ArchiveTranscodeTask holds the value of the archive_transcode_task edge.
	ArchiveTranscodeTask *TranscodeTask `json:"archive_transcode_task,omitempty"`
	// HighlightClips holds the value of the highlight_clips edge.
	HighlightClips []*HighlightClip `json:"highlight_clips,omitempty"`
	// OcrTasks holds the value of the ocr_tasks edge.
	OcrTasks []*OCRTask `json:"ocr_tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// RecordTaskOrErr returns the RecordTask value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaArtifactEdges) RecordTaskOrErr() (*RecordTask, error) {
	if e.RecordTask != nil {
		return e.RecordTask, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: recordtask.Label}
	}
	return nil, &NotLoadedError{edge: "record_task"}
}

// UploadTaskOrErr returns the UploadTask value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaArtifactEdges) UploadTaskOrErr() (*UploadTask, error) {
	if e.UploadTask != nil {
		return e.UploadTask, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: uploadtask.Label}
	}
	return nil, &NotLoadedError{edge: "upload_task"}
}

// SourceTranscodeTaskOrErr returns the SourceTranscodeTask value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaArtifactEdges) SourceTranscodeTaskOrErr() (*TranscodeTask, error) {
	if e.SourceTranscodeTask != nil {
		return e.SourceTranscodeTask, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: transcodetask.Label}
	}
	return nil, &NotLoadedError{edge: "source_transcode_task"}
}

// ArchiveTranscodeTaskOrErr returns the ArchiveTranscodeTask value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaArtifactEdges) ArchiveTranscodeTaskOrErr() (*TranscodeTask, error) {
	if e.ArchiveTranscodeTask != nil {
		return e.ArchiveTranscodeTask, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: transcodetask.Label}
	}
	return nil, &NotLoadedError{edge: "archive_transcode_task"}
}

// HighlightClipsOrErr returns the HighlightClips value or an error if the edge
// was not loaded in eager-loading.
func (e MediaArtifactEdges) HighlightClipsOrErr() ([]*HighlightClip, error) {
	if e.loadedTypes[4] {
		return e.HighlightClips, nil
	}
	return nil, &NotLoadedError{edge: "highlight_clips"}
}

// OcrTasksOrErr returns the OcrTasks value or an error if the edge
// was not loaded in eager-loading.
func (e MediaArtifactEdges) OcrTasksOrErr() ([]*OCRTask, error) {
	if e.loadedTypes[5] {
		return e.OcrTasks, nil
	}
	return nil, &NotLoadedError{edge: "ocr_tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaArtifact) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediaartifact.FieldID, mediaartifact.FieldFileSize:
			values[i] = new(sql.NullInt64)
		case mediaartifact.FieldKind, mediaartifact.FieldPath, mediaartifact.FieldFormat, mediaartifact.FieldCodec, mediaartifact.FieldChecksum, mediaartifact.FieldStatus:
			values[i] = new(sql.NullString)
		case mediaartifact.FieldDeletableAt, mediaartifact.FieldDeletedAt, mediaartifact.FieldCreatedAt, mediaartifact.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case mediaartifact.ForeignKeys[0]: // record_task_media_artifacts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaArtifact fields.
func (_m *MediaArtifact) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediaartifact.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mediaartifact.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = mediaartifact.Kind(value.String)
			}
		case mediaartifact.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case mediaartifact.FieldFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field format", values[i])
			} else if value.Valid {
				_m.Format = mediaartifact.Format(value.String)
			}
		case mediaartifact.FieldCodec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field codec", values[i])
			} else if value.Valid {
				_m.Codec = mediaartifact.Codec(value.String)
			}
		case mediaartifact.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = new(int64)
				*_m.FileSize = value.Int64
			}
		case mediaartifact.FieldChecksum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checksum", values[i])
			} else if value.Valid {
				_m.Checksum = new(string)
				*_m.Checksum = value.String
			}
		case mediaartifact.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = mediaartifact.Status(value.String)
			}
		case mediaartifact.FieldDeletableAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deletable_at", values[i])
			} else if value.Valid {
				_m.DeletableAt = new(time.Time)
				*_m.DeletableAt = value.Time
			}
		case mediaartifact.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case mediaartifact.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mediaartifact.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mediaartifact.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field record_task_media_artifacts", value)
			} else if value.Valid {
				_m.record_task_media_artifacts = new(int)
				*_m.record_task_media_artifacts = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaArtifact.
// This includes values selected through modifiers, order, etc.
func (_m *MediaArtifact) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRecordTask queries the "record_task" edge of the MediaArtifact entity.
func (_m *MediaArtifact) QueryRecordTask() *RecordTaskQuery {
	return NewMediaArtifactClient(_m.config).QueryRecordTask(_m)
}

// QueryUploadTask queries the "upload_task" edge of the MediaArtifact entity.
func (_m *MediaArtifact) QueryUploadTask() *UploadTaskQuery {
	return NewMediaArtifactClient(_m.config).QueryUploadTask(_m)
}

// QuerySourceTranscodeTask queries the "source_transcode_task" edge of the MediaArtifact entity.
func (_m *MediaArtifact) QuerySourceTranscodeTask() *TranscodeTaskQuery {
	return NewMediaArtifactClient(_m.config).QuerySourceTranscodeTask(_m)
}

// QueryArchiveTranscodeTask queries the "archive_transcode_task" edge of the MediaArtifact entity.
func (_m *MediaArtifact) QueryArchiveTranscodeTask() *TranscodeTaskQuery {
	return NewMediaArtifactClient(_m.config).QueryArchiveTranscodeTask(_m)
}

// QueryHighlightClips queries the "highlight_clips" edge of the MediaArtifact entity.
func (_m *MediaArtifact) QueryHighlightClips() *HighlightClipQuery {
	return NewMediaArtifactClient(_m.config).QueryHighlightClips(_m)
}

// QueryOcrTasks queries the "ocr_tasks" edge of the MediaArtifact entity.
func (_m *MediaArtifact) QueryOcrTasks() *OCRTaskQuery {
	return NewMediaArtifactClient(_m.config).QueryOcrTasks(_m)
}

// Update returns a builder for updating this MediaArtifact.
// Note that you need to call MediaArtifact.Unwrap() before calling this method if this MediaArtifact
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaArtifact) Update() *MediaArtifactUpdateOne {
	return NewMediaArtifactClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaArtifact entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaArtifact) Unwrap() *MediaArtifact {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaArtifact is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaArtifact) String() string {
	var builder strings.Builder
	builder.WriteString("MediaArtifact(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("format=")
	builder.WriteString(fmt.Sprintf("%v", _m.Format))
	builder.WriteString(", ")
	builder.WriteString("codec=")
	builder.WriteString(fmt.Sprintf("%v", _m.Codec))
	builder.WriteString(", ")
	if v := _m.FileSize; v != nil {
		builder.WriteString("file_size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Checksum; v != nil {
		builder.WriteString("checksum=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.DeletableAt; v != nil {
		builder.WriteString("deletable_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MediaArtifacts is a parsable slice of MediaArtifact.
type MediaArtifacts []*MediaArtifact
