// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"scutbot.cn/web/rm-monitor/ent/matchround"
	"scutbot.cn/web/rm-monitor/ent/mediaartifact"
	"scutbot.cn/web/rm-monitor/ent/recordtask"
	"scutbot.cn/web/rm-monitor/ent/uploadtask"
)

// RecordTaskCreate is the builder for creating a RecordTask entity.
type RecordTaskCreate struct {
	config
	mutation *RecordTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRole sets the "role" field.
func (_c *RecordTaskCreate) SetRole(v string) *RecordTaskCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *RecordTaskCreate) SetSourceURL(v string) *RecordTaskCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetOutputPath sets the "output_path" field.
func (_c *RecordTaskCreate) SetOutputPath(v string) *RecordTaskCreate {
	_c.mutation.SetOutputPath(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RecordTaskCreate) SetStatus(v recordtask.Status) *RecordTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableStatus(v *recordtask.Status) *RecordTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetK8sJobName sets the "k8s_job_name" field.
func (_c *RecordTaskCreate) SetK8sJobName(v string) *RecordTaskCreate {
	_c.mutation.SetK8sJobName(v)
	return _c
}

// SetNillableK8sJobName sets the "k8s_job_name" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableK8sJobName(v *string) *RecordTaskCreate {
	if v != nil {
		_c.SetK8sJobName(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *RecordTaskCreate) SetAttempts(v int) *RecordTaskCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableAttempts(v *int) *RecordTaskCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *RecordTaskCreate) SetPriority(v int) *RecordTaskCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillablePriority(v *int) *RecordTaskCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *RecordTaskCreate) SetFileSize(v int64) *RecordTaskCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableFileSize(v *int64) *RecordTaskCreate {
	if v != nil {
		_c.SetFileSize(*v)
	}
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *RecordTaskCreate) SetChecksum(v string) *RecordTaskCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableChecksum(v *string) *RecordTaskCreate {
	if v != nil {
		_c.SetChecksum(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *RecordTaskCreate) SetErrorMessage(v string) *RecordTaskCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableErrorMessage(v *string) *RecordTaskCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *RecordTaskCreate) SetStartedAt(v time.Time) *RecordTaskCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableStartedAt(v *time.Time) *RecordTaskCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *RecordTaskCreate) SetCompletedAt(v time.Time) *RecordTaskCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableCompletedAt(v *time.Time) *RecordTaskCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RecordTaskCreate) SetCreatedAt(v time.Time) *RecordTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableCreatedAt(v *time.Time) *RecordTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RecordTaskCreate) SetUpdatedAt(v time.Time) *RecordTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableUpdatedAt(v *time.Time) *RecordTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMatchRoundID sets the "match_round" edge to the MatchRound entity by ID.
func (_c *RecordTaskCreate) SetMatchRoundID(id int) *RecordTaskCreate {
	_c.mutation.SetMatchRoundID(id)
	return _c
}

// SetMatchRound sets the "match_round" edge to the MatchRound entity.
func (_c *RecordTaskCreate) SetMatchRound(v *MatchRound) *RecordTaskCreate {
	return _c.SetMatchRoundID(v.ID)
}

// SetUploadTaskID sets the "upload_task" edge to the UploadTask entity by ID.
func (_c *RecordTaskCreate) SetUploadTaskID(id int) *RecordTaskCreate {
	_c.mutation.SetUploadTaskID(id)
	return _c
}

// SetNillableUploadTaskID sets the "upload_task" edge to the UploadTask entity by ID if the given value is not nil.
func (_c *RecordTaskCreate) SetNillableUploadTaskID(id *int) *RecordTaskCreate {
	if id != nil {
		_c = _c.SetUploadTaskID(*id)
	}
	return _c
}

// SetUploadTask sets the "upload_task" edge to the UploadTask entity.
func (_c *RecordTaskCreate) SetUploadTask(v *UploadTask) *RecordTaskCreate {
	return _c.SetUploadTaskID(v.ID)
}

// AddMediaArtifactIDs adds the "media_artifacts" edge to the MediaArtifact entity by IDs.
func (_c *RecordTaskCreate) AddMediaArtifactIDs(ids ...int) *RecordTaskCreate {
	_c.mutation.AddMediaArtifactIDs(ids...)
	return _c
}

// AddMediaArtifacts adds the "media_artifacts" edges to the MediaArtifact entity.
func (_c *RecordTaskCreate) AddMediaArtifacts(v ...*MediaArtifact) *RecordTaskCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMediaArtifactIDs(ids...)
}

// Mutation returns the RecordTaskMutation object of the builder.
func (_c *RecordTaskCreate) Mutation() *RecordTaskMutation {
	return _c.mutation
}

// Save creates the RecordTask in the database.
func (_c *RecordTaskCreate) Save(ctx context.Context) (*RecordTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecordTaskCreate) SaveX(ctx context.Context) *RecordTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecordTaskCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := recordtask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := recordtask.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := recordtask.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := recordtask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := recordtask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecordTaskCreate) check() error {
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "RecordTask.role"`)}
	}
	if _, ok := _c.mutation.SourceURL(); !ok {
		return &ValidationError{Name: "source_url", err: errors.New(`ent: missing required field "RecordTask.source_url"`)}
	}
	if _, ok := _c.mutation.OutputPath(); !ok {
		return &ValidationError{Name: "output_path", err: errors.New(`ent: missing required field "RecordTask.output_path"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RecordTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := recordtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RecordTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "RecordTask.attempts"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "RecordTask.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RecordTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RecordTask.updated_at"`)}
	}
	if len(_c.mutation.MatchRoundIDs()) == 0 {
		return &ValidationError{Name: "match_round", err: errors.New(`ent: missing required edge "RecordTask.match_round"`)}
	}
	return nil
}

func (_c *RecordTaskCreate) sqlSave(ctx context.Context) (*RecordTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecordTaskCreate) createSpec() (*RecordTask, *sqlgraph.CreateSpec) {
	var (
		_node = &RecordTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recordtask.Table, sqlgraph.NewFieldSpec(recordtask.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(recordtask.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(recordtask.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.OutputPath(); ok {
		_spec.SetField(recordtask.FieldOutputPath, field.TypeString, value)
		_node.OutputPath = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(recordtask.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.K8sJobName(); ok {
		_spec.SetField(recordtask.FieldK8sJobName, field.TypeString, value)
		_node.K8sJobName = &value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(recordtask.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(recordtask.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(recordtask.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = &value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(recordtask.FieldChecksum, field.TypeString, value)
		_node.Checksum = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(recordtask.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(recordtask.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(recordtask.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(recordtask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(recordtask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MatchRoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recordtask.MatchRoundTable,
			Columns: []string{recordtask.MatchRoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchround.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.match_round_record_tasks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UploadTaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   recordtask.UploadTaskTable,
			Columns: []string{recordtask.UploadTaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uploadtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MediaArtifactsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recordtask.MediaArtifactsTable,
			Columns: []string{recordtask.MediaArtifactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaartifact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RecordTask.Create().
//		SetRole(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RecordTaskUpsert) {
//			SetRole(v+v).
//		}).
//		Exec(ctx)
func (_c *RecordTaskCreate) OnConflict(opts ...sql.ConflictOption) *RecordTaskUpsertOne {
	_c.conflict = opts
	return &RecordTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RecordTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RecordTaskCreate) OnConflictColumns(columns ...string) *RecordTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RecordTaskUpsertOne{
		create: _c,
	}
}

type (
	// RecordTaskUpsertOne is the builder for "upsert"-ing
	//  one RecordTask node.
	RecordTaskUpsertOne struct {
		create *RecordTaskCreate
	}

	// RecordTaskUpsert is the "OnConflict" setter.
	RecordTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetRole sets the "role" field.
func (u *RecordTaskUpsert) SetRole(v string) *RecordTaskUpsert {
	u.Set(recordtask.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateRole() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldRole)
	return u
}

// SetSourceURL sets the "source_url" field.
func (u *RecordTaskUpsert) SetSourceURL(v string) *RecordTaskUpsert {
	u.Set(recordtask.FieldSourceURL, v)
	return u
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateSourceURL() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldSourceURL)
	return u
}

// SetOutputPath sets the "output_path" field.
func (u *RecordTaskUpsert) SetOutputPath(v string) *RecordTaskUpsert {
	u.Set(recordtask.FieldOutputPath, v)
	return u
}

// UpdateOutputPath sets the "output_path" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateOutputPath() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldOutputPath)
	return u
}

// SetStatus sets the "status" field.
func (u *RecordTaskUpsert) SetStatus(v recordtask.Status) *RecordTaskUpsert {
	u.Set(recordtask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateStatus() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldStatus)
	return u
}

// SetK8sJobName sets the "k8s_job_name" field.
func (u *RecordTaskUpsert) SetK8sJobName(v string) *RecordTaskUpsert {
	u.Set(recordtask.FieldK8sJobName, v)
	return u
}

// UpdateK8sJobName sets the "k8s_job_name" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateK8sJobName() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldK8sJobName)
	return u
}

// ClearK8sJobName clears the value of the "k8s_job_name" field.
func (u *RecordTaskUpsert) ClearK8sJobName() *RecordTaskUpsert {
	u.SetNull(recordtask.FieldK8sJobName)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *RecordTaskUpsert) SetAttempts(v int) *RecordTaskUpsert {
	u.Set(recordtask.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateAttempts() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *RecordTaskUpsert) AddAttempts(v int) *RecordTaskUpsert {
	u.Add(recordtask.FieldAttempts, v)
	return u
}

// SetPriority sets the "priority" field.
func (u *RecordTaskUpsert) SetPriority(v int) *RecordTaskUpsert {
	u.Set(recordtask.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdatePriority() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *RecordTaskUpsert) AddPriority(v int) *RecordTaskUpsert {
	u.Add(recordtask.FieldPriority, v)
	return u
}

// SetFileSize sets the "file_size" field.
func (u *RecordTaskUpsert) SetFileSize(v int64) *RecordTaskUpsert {
	u.Set(recordtask.FieldFileSize, v)
	return u
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateFileSize() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldFileSize)
	return u
}

// AddFileSize adds v to the "file_size" field.
func (u *RecordTaskUpsert) AddFileSize(v int64) *RecordTaskUpsert {
	u.Add(recordtask.FieldFileSize, v)
	return u
}

// ClearFileSize clears the value of the "file_size" field.
func (u *RecordTaskUpsert) ClearFileSize() *RecordTaskUpsert {
	u.SetNull(recordtask.FieldFileSize)
	return u
}

// SetChecksum sets the "checksum" field.
func (u *RecordTaskUpsert) SetChecksum(v string) *RecordTaskUpsert {
	u.Set(recordtask.FieldChecksum, v)
	return u
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateChecksum() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldChecksum)
	return u
}

// ClearChecksum clears the value of the "checksum" field.
func (u *RecordTaskUpsert) ClearChecksum() *RecordTaskUpsert {
	u.SetNull(recordtask.FieldChecksum)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *RecordTaskUpsert) SetErrorMessage(v string) *RecordTaskUpsert {
	u.Set(recordtask.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateErrorMessage() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RecordTaskUpsert) ClearErrorMessage() *RecordTaskUpsert {
	u.SetNull(recordtask.FieldErrorMessage)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *RecordTaskUpsert) SetStartedAt(v time.Time) *RecordTaskUpsert {
	u.Set(recordtask.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateStartedAt() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *RecordTaskUpsert) ClearStartedAt() *RecordTaskUpsert {
	u.SetNull(recordtask.FieldStartedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *RecordTaskUpsert) SetCompletedAt(v time.Time) *RecordTaskUpsert {
	u.Set(recordtask.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateCompletedAt() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RecordTaskUpsert) ClearCompletedAt() *RecordTaskUpsert {
	u.SetNull(recordtask.FieldCompletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RecordTaskUpsert) SetUpdatedAt(v time.Time) *RecordTaskUpsert {
	u.Set(recordtask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RecordTaskUpsert) UpdateUpdatedAt() *RecordTaskUpsert {
	u.SetExcluded(recordtask.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RecordTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RecordTaskUpsertOne) UpdateNewValues() *RecordTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(recordtask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RecordTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RecordTaskUpsertOne) Ignore() *RecordTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RecordTaskUpsertOne) DoNothing() *RecordTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RecordTaskCreate.OnConflict
// documentation for more info.
func (u *RecordTaskUpsertOne) Update(set func(*RecordTaskUpsert)) *RecordTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RecordTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetRole sets the "role" field.
func (u *RecordTaskUpsertOne) SetRole(v string) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateRole() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateRole()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *RecordTaskUpsertOne) SetSourceURL(v string) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateSourceURL() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateSourceURL()
	})
}

// SetOutputPath sets the "output_path" field.
func (u *RecordTaskUpsertOne) SetOutputPath(v string) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetOutputPath(v)
	})
}

// UpdateOutputPath sets the "output_path" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateOutputPath() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateOutputPath()
	})
}

// SetStatus sets the "status" field.
func (u *RecordTaskUpsertOne) SetStatus(v recordtask.Status) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateStatus() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetK8sJobName sets the "k8s_job_name" field.
func (u *RecordTaskUpsertOne) SetK8sJobName(v string) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetK8sJobName(v)
	})
}

// UpdateK8sJobName sets the "k8s_job_name" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateK8sJobName() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateK8sJobName()
	})
}

// ClearK8sJobName clears the value of the "k8s_job_name" field.
func (u *RecordTaskUpsertOne) ClearK8sJobName() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearK8sJobName()
	})
}

// SetAttempts sets the "attempts" field.
func (u *RecordTaskUpsertOne) SetAttempts(v int) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *RecordTaskUpsertOne) AddAttempts(v int) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateAttempts() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateAttempts()
	})
}

// SetPriority sets the "priority" field.
func (u *RecordTaskUpsertOne) SetPriority(v int) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *RecordTaskUpsertOne) AddPriority(v int) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdatePriority() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdatePriority()
	})
}

// SetFileSize sets the "file_size" field.
func (u *RecordTaskUpsertOne) SetFileSize(v int64) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *RecordTaskUpsertOne) AddFileSize(v int64) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateFileSize() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateFileSize()
	})
}

// ClearFileSize clears the value of the "file_size" field.
func (u *RecordTaskUpsertOne) ClearFileSize() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearFileSize()
	})
}

// SetChecksum sets the "checksum" field.
func (u *RecordTaskUpsertOne) SetChecksum(v string) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateChecksum() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateChecksum()
	})
}

// ClearChecksum clears the value of the "checksum" field.
func (u *RecordTaskUpsertOne) ClearChecksum() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearChecksum()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RecordTaskUpsertOne) SetErrorMessage(v string) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateErrorMessage() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RecordTaskUpsertOne) ClearErrorMessage() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearErrorMessage()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *RecordTaskUpsertOne) SetStartedAt(v time.Time) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateStartedAt() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *RecordTaskUpsertOne) ClearStartedAt() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *RecordTaskUpsertOne) SetCompletedAt(v time.Time) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateCompletedAt() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RecordTaskUpsertOne) ClearCompletedAt() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RecordTaskUpsertOne) SetUpdatedAt(v time.Time) *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RecordTaskUpsertOne) UpdateUpdatedAt() *RecordTaskUpsertOne {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RecordTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RecordTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RecordTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RecordTaskUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RecordTaskUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RecordTaskCreateBulk is the builder for creating many RecordTask entities in bulk.
type RecordTaskCreateBulk struct {
	config
	err      error
	builders []*RecordTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the RecordTask entities in the database.
func (_c *RecordTaskCreateBulk) Save(ctx context.Context) ([]*RecordTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RecordTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecordTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecordTaskCreateBulk) SaveX(ctx context.Context) []*RecordTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RecordTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RecordTaskUpsert) {
//			SetRole(v+v).
//		}).
//		Exec(ctx)
func (_c *RecordTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *RecordTaskUpsertBulk {
	_c.conflict = opts
	return &RecordTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RecordTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RecordTaskCreateBulk) OnConflictColumns(columns ...string) *RecordTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RecordTaskUpsertBulk{
		create: _c,
	}
}

// RecordTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of RecordTask nodes.
type RecordTaskUpsertBulk struct {
	create *RecordTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RecordTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RecordTaskUpsertBulk) UpdateNewValues() *RecordTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(recordtask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RecordTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RecordTaskUpsertBulk) Ignore() *RecordTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RecordTaskUpsertBulk) DoNothing() *RecordTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RecordTaskCreateBulk.OnConflict
// documentation for more info.
func (u *RecordTaskUpsertBulk) Update(set func(*RecordTaskUpsert)) *RecordTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RecordTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetRole sets the "role" field.
func (u *RecordTaskUpsertBulk) SetRole(v string) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateRole() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateRole()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *RecordTaskUpsertBulk) SetSourceURL(v string) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateSourceURL() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateSourceURL()
	})
}

// SetOutputPath sets the "output_path" field.
func (u *RecordTaskUpsertBulk) SetOutputPath(v string) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetOutputPath(v)
	})
}

// UpdateOutputPath sets the "output_path" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateOutputPath() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateOutputPath()
	})
}

// SetStatus sets the "status" field.
func (u *RecordTaskUpsertBulk) SetStatus(v recordtask.Status) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateStatus() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetK8sJobName sets the "k8s_job_name" field.
func (u *RecordTaskUpsertBulk) SetK8sJobName(v string) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetK8sJobName(v)
	})
}

// UpdateK8sJobName sets the "k8s_job_name" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateK8sJobName() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateK8sJobName()
	})
}

// ClearK8sJobName clears the value of the "k8s_job_name" field.
func (u *RecordTaskUpsertBulk) ClearK8sJobName() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearK8sJobName()
	})
}

// SetAttempts sets the "attempts" field.
func (u *RecordTaskUpsertBulk) SetAttempts(v int) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *RecordTaskUpsertBulk) AddAttempts(v int) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateAttempts() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateAttempts()
	})
}

// SetPriority sets the "priority" field.
func (u *RecordTaskUpsertBulk) SetPriority(v int) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *RecordTaskUpsertBulk) AddPriority(v int) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdatePriority() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdatePriority()
	})
}

// SetFileSize sets the "file_size" field.
func (u *RecordTaskUpsertBulk) SetFileSize(v int64) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *RecordTaskUpsertBulk) AddFileSize(v int64) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateFileSize() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateFileSize()
	})
}

// ClearFileSize clears the value of the "file_size" field.
func (u *RecordTaskUpsertBulk) ClearFileSize() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearFileSize()
	})
}

// SetChecksum sets the "checksum" field.
func (u *RecordTaskUpsertBulk) SetChecksum(v string) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateChecksum() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateChecksum()
	})
}

// ClearChecksum clears the value of the "checksum" field.
func (u *RecordTaskUpsertBulk) ClearChecksum() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearChecksum()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RecordTaskUpsertBulk) SetErrorMessage(v string) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateErrorMessage() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RecordTaskUpsertBulk) ClearErrorMessage() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearErrorMessage()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *RecordTaskUpsertBulk) SetStartedAt(v time.Time) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateStartedAt() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *RecordTaskUpsertBulk) ClearStartedAt() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *RecordTaskUpsertBulk) SetCompletedAt(v time.Time) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateCompletedAt() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RecordTaskUpsertBulk) ClearCompletedAt() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RecordTaskUpsertBulk) SetUpdatedAt(v time.Time) *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RecordTaskUpsertBulk) UpdateUpdatedAt() *RecordTaskUpsertBulk {
	return u.Update(func(s *RecordTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RecordTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RecordTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RecordTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RecordTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
