// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"scutbot.cn/web/rm-monitor/ent/team"
)

// Team is the model entity for the Team schema.
type Team struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SchoolName holds the value of the "school_name" field.
	SchoolName string `json:"school_name,omitempty"`
	// SchoolLogo holds the value of the "school_logo" field.
	SchoolLogo string `json:"school_logo,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamQuery when eager-loading is set.
	Edges        TeamEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamEdges holds the relations/edges for other nodes in the graph.
type TeamEdges struct {
	// RedMatches holds the value of the red_matches edge.
	RedMatches []*Match `json:"red_matches,omitempty"`
	// BlueMatches holds the value of the blue_matches edge.
	BlueMatches []*Match `json:"blue_matches,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RedMatchesOrErr returns the RedMatches value or an error if the edge
// was not loaded in eager-loading.
func (e TeamEdges) RedMatchesOrErr() ([]*Match, error) {
	if e.loadedTypes[0] {
		return e.RedMatches, nil
	}
	return nil, &NotLoadedError{edge: "red_matches"}
}

// BlueMatchesOrErr returns the BlueMatches value or an error if the edge
// was not loaded in eager-loading.
func (e TeamEdges) BlueMatchesOrErr() ([]*Match, error) {
	if e.loadedTypes[1] {
		return e.BlueMatches, nil
	}
	return nil, &NotLoadedError{edge: "blue_matches"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Team) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case team.FieldID, team.FieldName, team.FieldSchoolName, team.FieldSchoolLogo:
			values[i] = new(sql.NullString)
		case team.FieldCreatedAt, team.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Team fields.
func (_m *Team) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case team.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case team.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case team.FieldSchoolName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field school_name", values[i])
			} else if value.Valid {
				_m.SchoolName = value.String
			}
		case team.FieldSchoolLogo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field school_logo", values[i])
			} else if value.Valid {
				_m.SchoolLogo = value.String
			}
		case team.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case team.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Team.
// This includes values selected through modifiers, order, etc.
func (_m *Team) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRedMatches queries the "red_matches" edge of the Team entity.
func (_m *Team) QueryRedMatches() *MatchQuery {
	return NewTeamClient(_m.config).QueryRedMatches(_m)
}

// QueryBlueMatches queries the "blue_matches" edge of the Team entity.
func (_m *Team) QueryBlueMatches() *MatchQuery {
	return NewTeamClient(_m.config).QueryBlueMatches(_m)
}

// Update returns a builder for updating this Team.
// Note that you need to call Team.Unwrap() before calling this method if this Team
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Team) Update() *TeamUpdateOne {
	return NewTeamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Team entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Team) Unwrap() *Team {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Team is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Team) String() string {
	var builder strings.Builder
	builder.WriteString("Team(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("school_name=")
	builder.WriteString(_m.SchoolName)
	builder.WriteString(", ")
	builder.WriteString("school_logo=")
	builder.WriteString(_m.SchoolLogo)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Teams is a parsable slice of Team.
type Teams []*Team
