// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"scutbot.cn/web/rm-monitor/ent/mediaartifact"
	"scutbot.cn/web/rm-monitor/ent/predicate"
	"scutbot.cn/web/rm-monitor/ent/transcodetask"
)

// TranscodeTaskUpdate is the builder for updating TranscodeTask entities.
type TranscodeTaskUpdate struct {
	config
	hooks    []Hook
	mutation *TranscodeTaskMutation
}

// Where appends a list predicates to the TranscodeTaskUpdate builder.
func (_u *TranscodeTaskUpdate) Where(ps ...predicate.TranscodeTask) *TranscodeTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TranscodeTaskUpdate) SetStatus(v transcodetask.Status) *TranscodeTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TranscodeTaskUpdate) SetNillableStatus(v *transcodetask.Status) *TranscodeTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetK8sJobName sets the "k8s_job_name" field.
func (_u *TranscodeTaskUpdate) SetK8sJobName(v string) *TranscodeTaskUpdate {
	_u.mutation.SetK8sJobName(v)
	return _u
}

// SetNillableK8sJobName sets the "k8s_job_name" field if the given value is not nil.
func (_u *TranscodeTaskUpdate) SetNillableK8sJobName(v *string) *TranscodeTaskUpdate {
	if v != nil {
		_u.SetK8sJobName(*v)
	}
	return _u
}

// ClearK8sJobName clears the value of the "k8s_job_name" field.
func (_u *TranscodeTaskUpdate) ClearK8sJobName() *TranscodeTaskUpdate {
	_u.mutation.ClearK8sJobName()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *TranscodeTaskUpdate) SetAttempts(v int) *TranscodeTaskUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *TranscodeTaskUpdate) SetNillableAttempts(v *int) *TranscodeTaskUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *TranscodeTaskUpdate) AddAttempts(v int) *TranscodeTaskUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TranscodeTaskUpdate) SetPriority(v int) *TranscodeTaskUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TranscodeTaskUpdate) SetNillablePriority(v *int) *TranscodeTaskUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TranscodeTaskUpdate) AddPriority(v int) *TranscodeTaskUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *TranscodeTaskUpdate) SetErrorMessage(v string) *TranscodeTaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *TranscodeTaskUpdate) SetNillableErrorMessage(v *string) *TranscodeTaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *TranscodeTaskUpdate) ClearErrorMessage() *TranscodeTaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TranscodeTaskUpdate) SetStartedAt(v time.Time) *TranscodeTaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TranscodeTaskUpdate) SetNillableStartedAt(v *time.Time) *TranscodeTaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *TranscodeTaskUpdate) ClearStartedAt() *TranscodeTaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TranscodeTaskUpdate) SetCompletedAt(v time.Time) *TranscodeTaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TranscodeTaskUpdate) SetNillableCompletedAt(v *time.Time) *TranscodeTaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TranscodeTaskUpdate) ClearCompletedAt() *TranscodeTaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TranscodeTaskUpdate) SetUpdatedAt(v time.Time) *TranscodeTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSourceArtifactID sets the "source_artifact" edge to the MediaArtifact entity by ID.
func (_u *TranscodeTaskUpdate) SetSourceArtifactID(id int) *TranscodeTaskUpdate {
	_u.mutation.SetSourceArtifactID(id)
	return _u
}

// SetSourceArtifact sets the "source_artifact" edge to the MediaArtifact entity.
func (_u *TranscodeTaskUpdate) SetSourceArtifact(v *MediaArtifact) *TranscodeTaskUpdate {
	return _u.SetSourceArtifactID(v.ID)
}

// SetArchiveArtifactID sets the "archive_artifact" edge to the MediaArtifact entity by ID.
func (_u *TranscodeTaskUpdate) SetArchiveArtifactID(id int) *TranscodeTaskUpdate {
	_u.mutation.SetArchiveArtifactID(id)
	return _u
}

// SetNillableArchiveArtifactID sets the "archive_artifact" edge to the MediaArtifact entity by ID if the given value is not nil.
func (_u *TranscodeTaskUpdate) SetNillableArchiveArtifactID(id *int) *TranscodeTaskUpdate {
	if id != nil {
		_u = _u.SetArchiveArtifactID(*id)
	}
	return _u
}

// SetArchiveArtifact sets the "archive_artifact" edge to the MediaArtifact entity.
func (_u *TranscodeTaskUpdate) SetArchiveArtifact(v *MediaArtifact) *TranscodeTaskUpdate {
	return _u.SetArchiveArtifactID(v.ID)
}

// Mutation returns the TranscodeTaskMutation object of the builder.
func (_u *TranscodeTaskUpdate) Mutation() *TranscodeTaskMutation {
	return _u.mutation
}

// ClearSourceArtifact clears the "source_artifact" edge to the MediaArtifact entity.
func (_u *TranscodeTaskUpdate) ClearSourceArtifact() *TranscodeTaskUpdate {
	_u.mutation.ClearSourceArtifact()
	return _u
}

// ClearArchiveArtifact clears the "archive_artifact" edge to the MediaArtifact entity.
func (_u *TranscodeTaskUpdate) ClearArchiveArtifact() *TranscodeTaskUpdate {
	_u.mutation.ClearArchiveArtifact()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TranscodeTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TranscodeTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TranscodeTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TranscodeTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TranscodeTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := transcodetask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TranscodeTaskUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := transcodetask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TranscodeTask.status": %w`, err)}
		}
	}
	if _u.mutation.SourceArtifactCleared() && len(_u.mutation.SourceArtifactIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TranscodeTask.source_artifact"`)
	}
	return nil
}

func (_u *TranscodeTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transcodetask.Table, transcodetask.Columns, sqlgraph.NewFieldSpec(transcodetask.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transcodetask.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.K8sJobName(); ok {
		_spec.SetField(transcodetask.FieldK8sJobName, field.TypeString, value)
	}
	if _u.mutation.K8sJobNameCleared() {
		_spec.ClearField(transcodetask.FieldK8sJobName, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(transcodetask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(transcodetask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(transcodetask.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(transcodetask.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(transcodetask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(transcodetask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(transcodetask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(transcodetask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(transcodetask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(transcodetask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transcodetask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SourceArtifactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transcodetask.SourceArtifactTable,
			Columns: []string{transcodetask.SourceArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaartifact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceArtifactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transcodetask.SourceArtifactTable,
			Columns: []string{transcodetask.SourceArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaartifact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArchiveArtifactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transcodetask.ArchiveArtifactTable,
			Columns: []string{transcodetask.ArchiveArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaartifact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArchiveArtifactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transcodetask.ArchiveArtifactTable,
			Columns: []string{transcodetask.ArchiveArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaartifact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transcodetask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TranscodeTaskUpdateOne is the builder for updating a single TranscodeTask entity.
type TranscodeTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TranscodeTaskMutation
}

// SetStatus sets the "status" field.
func (_u *TranscodeTaskUpdateOne) SetStatus(v transcodetask.Status) *TranscodeTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TranscodeTaskUpdateOne) SetNillableStatus(v *transcodetask.Status) *TranscodeTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetK8sJobName sets the "k8s_job_name" field.
func (_u *TranscodeTaskUpdateOne) SetK8sJobName(v string) *TranscodeTaskUpdateOne {
	_u.mutation.SetK8sJobName(v)
	return _u
}

// SetNillableK8sJobName sets the "k8s_job_name" field if the given value is not nil.
func (_u *TranscodeTaskUpdateOne) SetNillableK8sJobName(v *string) *TranscodeTaskUpdateOne {
	if v != nil {
		_u.SetK8sJobName(*v)
	}
	return _u
}

// ClearK8sJobName clears the value of the "k8s_job_name" field.
func (_u *TranscodeTaskUpdateOne) ClearK8sJobName() *TranscodeTaskUpdateOne {
	_u.mutation.ClearK8sJobName()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *TranscodeTaskUpdateOne) SetAttempts(v int) *TranscodeTaskUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *TranscodeTaskUpdateOne) SetNillableAttempts(v *int) *TranscodeTaskUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *TranscodeTaskUpdateOne) AddAttempts(v int) *TranscodeTaskUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TranscodeTaskUpdateOne) SetPriority(v int) *TranscodeTaskUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TranscodeTaskUpdateOne) SetNillablePriority(v *int) *TranscodeTaskUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TranscodeTaskUpdateOne) AddPriority(v int) *TranscodeTaskUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *TranscodeTaskUpdateOne) SetErrorMessage(v string) *TranscodeTaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *TranscodeTaskUpdateOne) SetNillableErrorMessage(v *string) *TranscodeTaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *TranscodeTaskUpdateOne) ClearErrorMessage() *TranscodeTaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TranscodeTaskUpdateOne) SetStartedAt(v time.Time) *TranscodeTaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TranscodeTaskUpdateOne) SetNillableStartedAt(v *time.Time) *TranscodeTaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *TranscodeTaskUpdateOne) ClearStartedAt() *TranscodeTaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TranscodeTaskUpdateOne) SetCompletedAt(v time.Time) *TranscodeTaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TranscodeTaskUpdateOne) SetNillableCompletedAt(v *time.Time) *TranscodeTaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TranscodeTaskUpdateOne) ClearCompletedAt() *TranscodeTaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TranscodeTaskUpdateOne) SetUpdatedAt(v time.Time) *TranscodeTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSourceArtifactID sets the "source_artifact" edge to the MediaArtifact entity by ID.
func (_u *TranscodeTaskUpdateOne) SetSourceArtifactID(id int) *TranscodeTaskUpdateOne {
	_u.mutation.SetSourceArtifactID(id)
	return _u
}

// SetSourceArtifact sets the "source_artifact" edge to the MediaArtifact entity.
func (_u *TranscodeTaskUpdateOne) SetSourceArtifact(v *MediaArtifact) *TranscodeTaskUpdateOne {
	return _u.SetSourceArtifactID(v.ID)
}

// SetArchiveArtifactID sets the "archive_artifact" edge to the MediaArtifact entity by ID.
func (_u *TranscodeTaskUpdateOne) SetArchiveArtifactID(id int) *TranscodeTaskUpdateOne {
	_u.mutation.SetArchiveArtifactID(id)
	return _u
}

// SetNillableArchiveArtifactID sets the "archive_artifact" edge to the MediaArtifact entity by ID if the given value is not nil.
func (_u *TranscodeTaskUpdateOne) SetNillableArchiveArtifactID(id *int) *TranscodeTaskUpdateOne {
	if id != nil {
		_u = _u.SetArchiveArtifactID(*id)
	}
	return _u
}

// SetArchiveArtifact sets the "archive_artifact" edge to the MediaArtifact entity.
func (_u *TranscodeTaskUpdateOne) SetArchiveArtifact(v *MediaArtifact) *TranscodeTaskUpdateOne {
	return _u.SetArchiveArtifactID(v.ID)
}

// Mutation returns the TranscodeTaskMutation object of the builder.
func (_u *TranscodeTaskUpdateOne) Mutation() *TranscodeTaskMutation {
	return _u.mutation
}

// ClearSourceArtifact clears the "source_artifact" edge to the MediaArtifact entity.
func (_u *TranscodeTaskUpdateOne) ClearSourceArtifact() *TranscodeTaskUpdateOne {
	_u.mutation.ClearSourceArtifact()
	return _u
}

// ClearArchiveArtifact clears the "archive_artifact" edge to the MediaArtifact entity.
func (_u *TranscodeTaskUpdateOne) ClearArchiveArtifact() *TranscodeTaskUpdateOne {
	_u.mutation.ClearArchiveArtifact()
	return _u
}

// Where appends a list predicates to the TranscodeTaskUpdate builder.
func (_u *TranscodeTaskUpdateOne) Where(ps ...predicate.TranscodeTask) *TranscodeTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TranscodeTaskUpdateOne) Select(field string, fields ...string) *TranscodeTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TranscodeTask entity.
func (_u *TranscodeTaskUpdateOne) Save(ctx context.Context) (*TranscodeTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TranscodeTaskUpdateOne) SaveX(ctx context.Context) *TranscodeTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TranscodeTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TranscodeTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TranscodeTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := transcodetask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TranscodeTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := transcodetask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TranscodeTask.status": %w`, err)}
		}
	}
	if _u.mutation.SourceArtifactCleared() && len(_u.mutation.SourceArtifactIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TranscodeTask.source_artifact"`)
	}
	return nil
}

func (_u *TranscodeTaskUpdateOne) sqlSave(ctx context.Context) (_node *TranscodeTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transcodetask.Table, transcodetask.Columns, sqlgraph.NewFieldSpec(transcodetask.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TranscodeTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transcodetask.FieldID)
		for _, f := range fields {
			if !transcodetask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transcodetask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transcodetask.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.K8sJobName(); ok {
		_spec.SetField(transcodetask.FieldK8sJobName, field.TypeString, value)
	}
	if _u.mutation.K8sJobNameCleared() {
		_spec.ClearField(transcodetask.FieldK8sJobName, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(transcodetask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(transcodetask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(transcodetask.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(transcodetask.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(transcodetask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(transcodetask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(transcodetask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(transcodetask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(transcodetask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(transcodetask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transcodetask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SourceArtifactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transcodetask.SourceArtifactTable,
			Columns: []string{transcodetask.SourceArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaartifact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceArtifactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transcodetask.SourceArtifactTable,
			Columns: []string{transcodetask.SourceArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaartifact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArchiveArtifactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transcodetask.ArchiveArtifactTable,
			Columns: []string{transcodetask.ArchiveArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaartifact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArchiveArtifactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transcodetask.ArchiveArtifactTable,
			Columns: []string{transcodetask.ArchiveArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaartifact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TranscodeTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transcodetask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
