// Code generated by ent, DO NOT EDIT.

package highlightclip

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the highlightclip type in the database.
	Label = "highlight_clip"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHighlightIndex holds the string denoting the highlight_index field in the database.
	FieldHighlightIndex = "highlight_index"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldAlgorithmVersion holds the string denoting the algorithm_version field in the database.
	FieldAlgorithmVersion = "algorithm_version"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldK8sJobName holds the string denoting the k8s_job_name field in the database.
	FieldK8sJobName = "k8s_job_name"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldStartSeconds holds the string denoting the start_seconds field in the database.
	FieldStartSeconds = "start_seconds"
	// FieldEndSeconds holds the string denoting the end_seconds field in the database.
	FieldEndSeconds = "end_seconds"
	// FieldPeakSeconds holds the string denoting the peak_seconds field in the database.
	FieldPeakSeconds = "peak_seconds"
	// FieldOutputDir holds the string denoting the output_dir field in the database.
	FieldOutputDir = "output_dir"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldModelPayload holds the string denoting the model_payload field in the database.
	FieldModelPayload = "model_payload"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMatchRound holds the string denoting the match_round edge name in mutations.
	EdgeMatchRound = "match_round"
	// EdgeSourceArtifact holds the string denoting the source_artifact edge name in mutations.
	EdgeSourceArtifact = "source_artifact"
	// EdgePublishTasks holds the string denoting the publish_tasks edge name in mutations.
	EdgePublishTasks = "publish_tasks"
	// Table holds the table name of the highlightclip in the database.
	Table = "highlight_clips"
	// MatchRoundTable is the table that holds the match_round relation/edge.
	MatchRoundTable = "highlight_clips"
	// MatchRoundInverseTable is the table name for the MatchRound entity.
	// It exists in this package in order to avoid circular dependency with the "matchround" package.
	MatchRoundInverseTable = "match_rounds"
	// MatchRoundColumn is the table column denoting the match_round relation/edge.
	MatchRoundColumn = "match_round_highlight_clips"
	// SourceArtifactTable is the table that holds the source_artifact relation/edge.
	SourceArtifactTable = "highlight_clips"
	// SourceArtifactInverseTable is the table name for the MediaArtifact entity.
	// It exists in this package in order to avoid circular dependency with the "mediaartifact" package.
	SourceArtifactInverseTable = "media_artifacts"
	// SourceArtifactColumn is the table column denoting the source_artifact relation/edge.
	SourceArtifactColumn = "media_artifact_highlight_clips"
	// PublishTasksTable is the table that holds the publish_tasks relation/edge.
	PublishTasksTable = "highlight_publish_tasks"
	// PublishTasksInverseTable is the table name for the HighlightPublishTask entity.
	// It exists in this package in order to avoid circular dependency with the "highlightpublishtask" package.
	PublishTasksInverseTable = "highlight_publish_tasks"
	// PublishTasksColumn is the table column denoting the publish_tasks relation/edge.
	PublishTasksColumn = "highlight_clip_publish_tasks"
)

// Columns holds all SQL columns for highlightclip fields.
var Columns = []string{
	FieldID,
	FieldHighlightIndex,
	FieldRole,
	FieldAlgorithmVersion,
	FieldStatus,
	FieldPriority,
	FieldK8sJobName,
	FieldAttempts,
	FieldStartSeconds,
	FieldEndSeconds,
	FieldPeakSeconds,
	FieldOutputDir,
	FieldTitle,
	FieldDescription,
	FieldTags,
	FieldScore,
	FieldModelPayload,
	FieldErrorMessage,
	FieldStartedAt,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "highlight_clips"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"match_round_highlight_clips",
	"media_artifact_highlight_clips",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// DefaultScore holds the default value on creation for the "score" field.
	DefaultScore float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING     Status = "PENDING"
	StatusDISPATCHING Status = "DISPATCHING"
	StatusRUNNING     Status = "RUNNING"
	StatusSUCCEEDED   Status = "SUCCEEDED"
	StatusFAILED      Status = "FAILED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusDISPATCHING, StatusRUNNING, StatusSUCCEEDED, StatusFAILED:
		return nil
	default:
		return fmt.Errorf("highlightclip: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the HighlightClip queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHighlightIndex orders the results by the highlight_index field.
func ByHighlightIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHighlightIndex, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByAlgorithmVersion orders the results by the algorithm_version field.
func ByAlgorithmVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlgorithmVersion, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByK8sJobName orders the results by the k8s_job_name field.
func ByK8sJobName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldK8sJobName, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByStartSeconds orders the results by the start_seconds field.
func ByStartSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartSeconds, opts...).ToFunc()
}

// ByEndSeconds orders the results by the end_seconds field.
func ByEndSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndSeconds, opts...).ToFunc()
}

// ByPeakSeconds orders the results by the peak_seconds field.
func ByPeakSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakSeconds, opts...).ToFunc()
}

// ByOutputDir orders the results by the output_dir field.
func ByOutputDir(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputDir, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByModelPayload orders the results by the model_payload field.
func ByModelPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelPayload, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMatchRoundField orders the results by match_round field.
func ByMatchRoundField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMatchRoundStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceArtifactField orders the results by source_artifact field.
func BySourceArtifactField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceArtifactStep(), sql.OrderByField(field, opts...))
	}
}

// ByPublishTasksCount orders the results by publish_tasks count.
func ByPublishTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPublishTasksStep(), opts...)
	}
}

// ByPublishTasks orders the results by publish_tasks terms.
func ByPublishTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPublishTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMatchRoundStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MatchRoundInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MatchRoundTable, MatchRoundColumn),
	)
}
func newSourceArtifactStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceArtifactInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceArtifactTable, SourceArtifactColumn),
	)
}
func newPublishTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PublishTasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PublishTasksTable, PublishTasksColumn),
	)
}
