// Code generated by ent, DO NOT EDIT.

package mediaartifact

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"scutbot.cn/web/rm-monitor/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLTE(FieldID, id))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldPath, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int64) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldFileSize, v))
}

// Checksum applies equality check predicate on the "checksum" field. It's identical to ChecksumEQ.
func Checksum(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldChecksum, v))
}

// DeletableAt applies equality check predicate on the "deletable_at" field. It's identical to DeletableAtEQ.
func DeletableAt(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldDeletableAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldKind, vs...))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldContainsFold(FieldPath, v))
}

// FormatEQ applies the EQ predicate on the "format" field.
func FormatEQ(v Format) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldFormat, v))
}

// FormatNEQ applies the NEQ predicate on the "format" field.
func FormatNEQ(v Format) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldFormat, v))
}

// FormatIn applies the In predicate on the "format" field.
func FormatIn(vs ...Format) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldFormat, vs...))
}

// FormatNotIn applies the NotIn predicate on the "format" field.
func FormatNotIn(vs ...Format) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldFormat, vs...))
}

// CodecEQ applies the EQ predicate on the "codec" field.
func CodecEQ(v Codec) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldCodec, v))
}

// CodecNEQ applies the NEQ predicate on the "codec" field.
func CodecNEQ(v Codec) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldCodec, v))
}

// CodecIn applies the In predicate on the "codec" field.
func CodecIn(vs ...Codec) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldCodec, vs...))
}

// CodecNotIn applies the NotIn predicate on the "codec" field.
func CodecNotIn(vs ...Codec) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldCodec, vs...))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int64) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int64) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int64) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int64) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int64) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int64) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int64) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int64) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLTE(FieldFileSize, v))
}

// FileSizeIsNil applies the IsNil predicate on the "file_size" field.
func FileSizeIsNil() predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIsNull(FieldFileSize))
}

// FileSizeNotNil applies the NotNil predicate on the "file_size" field.
func FileSizeNotNil() predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotNull(FieldFileSize))
}

// ChecksumEQ applies the EQ predicate on the "checksum" field.
func ChecksumEQ(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldChecksum, v))
}

// ChecksumNEQ applies the NEQ predicate on the "checksum" field.
func ChecksumNEQ(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldChecksum, v))
}

// ChecksumIn applies the In predicate on the "checksum" field.
func ChecksumIn(vs ...string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldChecksum, vs...))
}

// ChecksumNotIn applies the NotIn predicate on the "checksum" field.
func ChecksumNotIn(vs ...string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldChecksum, vs...))
}

// ChecksumGT applies the GT predicate on the "checksum" field.
func ChecksumGT(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGT(FieldChecksum, v))
}

// ChecksumGTE applies the GTE predicate on the "checksum" field.
func ChecksumGTE(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGTE(FieldChecksum, v))
}

// ChecksumLT applies the LT predicate on the "checksum" field.
func ChecksumLT(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLT(FieldChecksum, v))
}

// ChecksumLTE applies the LTE predicate on the "checksum" field.
func ChecksumLTE(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLTE(FieldChecksum, v))
}

// ChecksumContains applies the Contains predicate on the "checksum" field.
func ChecksumContains(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldContains(FieldChecksum, v))
}

// ChecksumHasPrefix applies the HasPrefix predicate on the "checksum" field.
func ChecksumHasPrefix(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldHasPrefix(FieldChecksum, v))
}

// ChecksumHasSuffix applies the HasSuffix predicate on the "checksum" field.
func ChecksumHasSuffix(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldHasSuffix(FieldChecksum, v))
}

// ChecksumIsNil applies the IsNil predicate on the "checksum" field.
func ChecksumIsNil() predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIsNull(FieldChecksum))
}

// ChecksumNotNil applies the NotNil predicate on the "checksum" field.
func ChecksumNotNil() predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotNull(FieldChecksum))
}

// ChecksumEqualFold applies the EqualFold predicate on the "checksum" field.
func ChecksumEqualFold(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEqualFold(FieldChecksum, v))
}

// ChecksumContainsFold applies the ContainsFold predicate on the "checksum" field.
func ChecksumContainsFold(v string) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldContainsFold(FieldChecksum, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldStatus, vs...))
}

// DeletableAtEQ applies the EQ predicate on the "deletable_at" field.
func DeletableAtEQ(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldDeletableAt, v))
}

// DeletableAtNEQ applies the NEQ predicate on the "deletable_at" field.
func DeletableAtNEQ(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldDeletableAt, v))
}

// DeletableAtIn applies the In predicate on the "deletable_at" field.
func DeletableAtIn(vs ...time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldDeletableAt, vs...))
}

// DeletableAtNotIn applies the NotIn predicate on the "deletable_at" field.
func DeletableAtNotIn(vs ...time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldDeletableAt, vs...))
}

// DeletableAtGT applies the GT predicate on the "deletable_at" field.
func DeletableAtGT(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGT(FieldDeletableAt, v))
}

// DeletableAtGTE applies the GTE predicate on the "deletable_at" field.
func DeletableAtGTE(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGTE(FieldDeletableAt, v))
}

// DeletableAtLT applies the LT predicate on the "deletable_at" field.
func DeletableAtLT(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLT(FieldDeletableAt, v))
}

// DeletableAtLTE applies the LTE predicate on the "deletable_at" field.
func DeletableAtLTE(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLTE(FieldDeletableAt, v))
}

// DeletableAtIsNil applies the IsNil predicate on the "deletable_at" field.
func DeletableAtIsNil() predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIsNull(FieldDeletableAt))
}

// DeletableAtNotNil applies the NotNil predicate on the "deletable_at" field.
func DeletableAtNotNil() predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotNull(FieldDeletableAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasRecordTask applies the HasEdge predicate on the "record_task" edge.
func HasRecordTask() predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RecordTaskTable, RecordTaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecordTaskWith applies the HasEdge predicate on the "record_task" edge with a given conditions (other predicates).
func HasRecordTaskWith(preds ...predicate.RecordTask) predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := newRecordTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUploadTask applies the HasEdge predicate on the "upload_task" edge.
func HasUploadTask() predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, UploadTaskTable, UploadTaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUploadTaskWith applies the HasEdge predicate on the "upload_task" edge with a given conditions (other predicates).
func HasUploadTaskWith(preds ...predicate.UploadTask) predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := newUploadTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSttTasks applies the HasEdge predicate on the "stt_tasks" edge.
func HasSttTasks() predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SttTasksTable, SttTasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSttTasksWith applies the HasEdge predicate on the "stt_tasks" edge with a given conditions (other predicates).
func HasSttTasksWith(preds ...predicate.STTTask) predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := newSttTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceTranscodeTask applies the HasEdge predicate on the "source_transcode_task" edge.
func HasSourceTranscodeTask() predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, SourceTranscodeTaskTable, SourceTranscodeTaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceTranscodeTaskWith applies the HasEdge predicate on the "source_transcode_task" edge with a given conditions (other predicates).
func HasSourceTranscodeTaskWith(preds ...predicate.TranscodeTask) predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := newSourceTranscodeTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasArchiveTranscodeTask applies the HasEdge predicate on the "archive_transcode_task" edge.
func HasArchiveTranscodeTask() predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ArchiveTranscodeTaskTable, ArchiveTranscodeTaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArchiveTranscodeTaskWith applies the HasEdge predicate on the "archive_transcode_task" edge with a given conditions (other predicates).
func HasArchiveTranscodeTaskWith(preds ...predicate.TranscodeTask) predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := newArchiveTranscodeTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHighlightClips applies the HasEdge predicate on the "highlight_clips" edge.
func HasHighlightClips() predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HighlightClipsTable, HighlightClipsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHighlightClipsWith applies the HasEdge predicate on the "highlight_clips" edge with a given conditions (other predicates).
func HasHighlightClipsWith(preds ...predicate.HighlightClip) predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := newHighlightClipsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOcrTasks applies the HasEdge predicate on the "ocr_tasks" edge.
func HasOcrTasks() predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OcrTasksTable, OcrTasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOcrTasksWith applies the HasEdge predicate on the "ocr_tasks" edge with a given conditions (other predicates).
func HasOcrTasksWith(preds ...predicate.OCRTask) predicate.MediaArtifact {
	return predicate.MediaArtifact(func(s *sql.Selector) {
		step := newOcrTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaArtifact) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaArtifact) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaArtifact) predicate.MediaArtifact {
	return predicate.MediaArtifact(sql.NotPredicates(p))
}
