WhisperServerUrls:
  - http://172.30.162.40:48088/inference
  - http://172.30.162.41:48088/inference
DifyConf:
  BaseURL: ""
  TimeoutSeconds: 180
STTQualityConf:
  UseQuality: false
  WorkflowAPIKey: ""
RecordConf:
  Res: middle
  BaseDir: /records
  STTRole: "主视角"
  PathTemplate: "{{.Event}}/{{.Zone}}/{{.MatchName}}/Round-{{.RoundNo}}/{{.Role}}.flv"
  MatchDirTemplate: "{{.Event}}/{{.Zone}}/{{.MatchName}}"
  MatchNameTemplate: "{{.Order}}. {{.RedSchool}}-{{.RedName}} VS {{.BlueSchool}}-{{.BlueName}}"
